### ISSUE TITLE
Run cfn-lint on test outputs without causing circular dependency

### ISSUE THREAD

**Issue by keetonian** [aws/serverless-application-model#1042]
**Description:**

Adding in cfn-lint as a test dependency caused dependency issues as noted in #1008. We are removing cfn-lint as a dependency in #1034, but it can be a valuable testing tool.

I'm opening this issue to track adding it back in such a way that it does not cause circular dependency issues and allows us to use it as part of our testing suite.

**Comment by jlhood** [comment]
Suggestion: We could install it separately as part of the Travis run and then just run it against all output templates. That way it's not part of our dependency closure. We'd need to update our developer guide so people know they need to have it installed as a prerequisite to running make pr.
