### ISSUE TITLE
AWS cli sam model An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [TableNameParameter] must have values

### ISSUE THREAD

**Issue by aws-adjustmentbureau** [aws/serverless-application-model#1107]
**Description:**

**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Comment by praneetap** [comment]
@aws-adjustmentbureau Can you please tell us what example you are trying to run and the command you are using?

**Comment by sriram-mv** [comment]
Please comment with more details if this is still an issue, closing this issue.
