### ISSUE TITLE
python3.6 sqlachemy dependency not correctly installed

### ISSUE THREAD

**Issue by cedric05** [aws/serverless-application-model#1123]
**Description:**

**Steps to reproduce the issue:**
1. SQLAlchemy
2. python 3.6
3. failing 

**Observed result:**

**Expected result:**

**Comment by keetonian** [comment]
@cedric05 is this from `sam build` or when deploying this template via CloudFormation? How can we recreate this?

**Comment by mgrandis** [comment]
Closing as this does not seem related to SAM and is lacking details.
Please re-open with additional details if you still encounter the issue.
