### ISSUE TITLE
SAM JSON schema

### ISSUE THREAD

**Issue by jlhood** [aws/serverless-application-model#1133]
**Description:**

Today, SAM's spec is a document meant for human consumption only. SAM should also have an authoritative, machine-readable spec (schema). This would be beneficial in multiple ways:

1. This would allow cfn-lint to remove its dependency on the SAM translator code, which can cause dependency conflicts with other modules if they depend on a different version of SAM translator. cfn-lint could keep a copy the SAM schema similar to what it does for [CloudFormation schemas](https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/data/CloudSpecs). Then there would no longer be a dependency conflict.
    1. Somewhat tangential: I'd prefer for SAM CLI's `sam validate` command to just run cfn-lint against the template. I think this would be far more valuable than what the current `sam validate` command offers. Removing cfn-lint's dependency on SAM translator would unblock this.
1. If we could embed the documentation of the current spec into the schema, this could lead to the human-readable version of the spec being auto-generated. This would allow us to auto-generate the SAM spec in the official [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html) after each SAM release.

**Comment by kddejong** [comment]
From a cfn lint perspective I like this idea. sam  translator is currently essential to us being able to lint serverless templates. Having a shema could remove us from that requirement and allow us to directly lint the original file.

**Comment by nija-at** [comment]
+1 to this. 

[AWS CDK](https://github.com/aws/aws-cdk) is currently using [the spec for awslabs/goformation](https://github.com/awslabs/goformation/blob/master/generate/sam-2016-10-31.json) to auto-generate CDK L1 resources (i.e. language bindings) and we're seeing a couple of cases where the handcrafted spec deviates from SAM's spec, specifically in terms of required and optional attributes, that blocks our customers from doing the right thing. 

Referencing https://github.com/aws/aws-cdk/issues/3841 and https://github.com/awslabs/goformation/issues/87.

**Comment by stilvoid** [comment]
Another +1. I'd like to add SAM resource types to https://github.com/aws-cloudformation/rain :)

**Comment by tj** [comment]
There's https://github.com/aws/serverless-application-model/blob/develop/samtranslator/validator/sam_schema/schema.json , but it doesn't seem up-to-date, it's missing HttpApi.

**Comment by jfuss** [comment]
Pining to clear the `maintainer/need-response` label. The team is looking at a better validation experience through jsonschema but none of that work is in progress or fully designed. 

We did some work on this already: https://github.com/aws/serverless-application-model/pull/2195 and https://github.com/aws/serverless-application-model/pull/2032

**Comment by hoffa** [comment]
Some initial work in https://github.com/aws/serverless-application-model/pull/2616. All test templates will have to pass the schema validation, and we'll be replacing those `Unknown`s with the correct types over time. The JSON schema is in https://github.com/aws/serverless-application-model/blob/develop/samtranslator/schema/schema.json, but it's still very early stages so no guarantees.

**Comment by hoffa** [comment]
Relevant: https://github.com/aws/serverless-application-model/discussions/2645

**Comment by hoffa** [comment]
Resolving; done in PRs above.

See https://github.com/aws/serverless-application-model/blob/develop/samtranslator/schema/schema.json and https://github.com/aws/serverless-application-model/discussions/2645.
