### ISSUE TITLE
Serverless-application-model is widely used and many apps are dependent on it, can it be promoted out of awslabs and into the first-class aws repo?

### ISSUE THREAD

**Issue by ajhool** [aws/serverless-application-model#1237]
My understanding of awslabs is that it holds code that receives second class support from aws. Other awslabs products like https://github.com/awslabs/dynamodb-data-mapper-js/tree/master/packages/dynamodb-data-mapper-annotations have been left to languish and have forced us to remove the package from our code. We're worried that the same thing could happen to SAM unless it is "promoted" to the main repo.

Please consider this!

**Comment by keetonian** [comment]
Thank you for the feedback! It's on our roadmap to do this, any feedback like this will help us in prioritizing it.
