### ISSUE TITLE
'Error from cloudfront' after API method has changed

### ISSUE THREAD

**Issue by Schtevy** [aws/serverless-application-model#1246]
**Description:**

After several changes I always got the response code 500 (internal server error). Furthermore the header the response contains "x-cache: Error from cloudfront".

After some internet search I found out, that this is kind of common problem with CloudFormation.

- https://forums.aws.amazon.com/thread.jspa?threadID=223774
- https://medium.com/@ngchiwang/aws-apigateway-deployment-not-update-

To fix that problem I simply deleted the Stack and re-created it.
After that it worked as expected.

My hypothesis is that I changed the method of my function from GET to POST but this change did not update the API GW.

**Steps to reproduce the issue:**
I guess a simply change of the method of a function in an already deployed stack?

Does anybody had that issue before me?

**Comment by ShreyaGangishetty** [comment]
@SteffenBurger If the swagger was generated by SAM then changing the method from GET to POST would have redeployed your API. It is hard to debug your issue without the template you have used. Could you add your sample template here?

**Comment by Luke1298** [comment]
> * https://medium.com/@ngchiwang/aws-apigateway-deployment-not-update-


For reference this can now be found: https://ngchiwa.medium.com/aws-apigateway-deployment-not-update-3e04fcffe85b
