### ISSUE TITLE
translator.py made capability mandatory

### ISSUE THREAD

**Issue by dxunix** [aws/serverless-application-model#1292]
**Description:**

translator.py made capability mandatory.  this option is optional in CloudFormation deploy

**Steps to reproduce the issue:**
N/A

**Observed result:**
N/A
**Expected result:**
Should be optional as there are deployment using existing iam roles.

**Comment by keetonian** [comment]
@dxunix Are you talking about recent changes to `sam deploy`? Can you provide steps or a template to reproduce this issue? It is true that in some cases, deploying with capabilities are mandatory, but not in every case.

**Comment by sriram-mv** [comment]
you can go through sam deploy --guided process and after that you cli args are saved within samconfig.toml.
