### ISSUE TITLE
Question: Does ImportValue intrinsic function work for Layers property of AWS::Serverless::Function? 

### ISSUE THREAD

**Issue by Jun711** [aws/serverless-application-model#1302]
I found this caveat for using `ImportValue` intrinsic function but it doesn't include Layers property of AWS::Serverless::Function. Is it not updated or I did something incorrect? 

I tried using ImportValue for Layers and it didn't seem to work. It works when I use layer ARN. Fyi, I tried with AWS SAM CLI version 0.32.0 and 0.37.0 

**Description:**

**Steps to reproduce the issue:**
1. Create Output from a stack
2. Go to CloudFormation console to get stack ExportName 
3. Use `!ImportValue ExportName` to get Output value at Layers property (didn't work)
4. Use `Fn::ImportValue: ExportName` to get Output value at Layers property (didn't work)
5. Use Output value directly (Layers ARN) at Layers property (it worked)

**Observed result:**
Function from layer cannot be imported
```
[ERROR] Runtime.ImportModuleError:   
Unable to import module 'index':   
cannot import name 'function1' from 'utils' (unknown location)
```

**Expected result:**
Able to import output value at Layers property and then import function from a layer

**Comment by dalumiller** [comment]
Looks like it can't be done: https://github.com/awslabs/aws-sam-cli/issues/1489. I ran into this as well. Ended up creating a separate repo/sam temp for a layer so I can manage the layer that gets used in several other CF stacks.

**Comment by hoffa** [comment]
Closing in favor of https://github.com/aws/serverless-application-model/issues/2533.
