### ISSUE TITLE
Support DLQ for SNS subscriptions

### ISSUE THREAD

**Issue by michaelwittig** [aws/serverless-application-model#1397]
**Description:**
SNS subscriptions support DLQs using a so called RedrivePolicy https://docs.aws.amazon.com/sns/latest/dg/sns-configure-dead-letter-queue.html

**Observed result:**
The SNS event type does not allow to define a RedrivePolicy  https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sns

**Expected result:**
Support RedrivePolicy

**Comment by keetonian** [comment]
Great idea!

We can add `RedrivePolicy` here to the subscription definition: https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/sns.py#L6

Add it to the SNS event definition and make sure it gets plumbed through this section: https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L367

Add/update tests, and this should be good to go!

**Comment by frankleng** [comment]
@keetonian any update on this?

**Comment by timoschilling** [comment]
`RedrivePolicy` seams to be supported now

**Comment by keetonian** [comment]
Crossed out my comment that it's not supported in CloudFormation, it looks like we can go forward with this feature.

**Comment by ssenchenko** [comment]
Re-openning till we change the docs
