### ISSUE TITLE
Documentation for EventBusRule missing EventBusName property

### ISSUE THREAD

**Issue by ljacobsson** [aws/serverless-application-model#1427]
*Description:*

In [2016-10-31md](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent), `CloudWatchEvent` references the newer [EventBridgeRule](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#eventbridgerule)

The `EventBridgeRule` does not list `EventBusName` as one of its properties.  However, if I add it to my template I can indeed use a custom event bus.

I assume the property is meant to be present.

**Comment by jfuss** [comment]
Docs are updated: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html

Closing
