### ISSUE TITLE
EndpointConfiguration not honoured

### ISSUE THREAD

**Issue by henrytk** [aws/serverless-application-model#1428]
**Description:**

I've added `EndpointConfiguration: REGIONAL` as per the documentation[1], but the rest API is being created as EDGE.

[1] https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-endpointconfiguration

**Steps to reproduce the issue:**

Using version 0.40.0:

```bash
$ sam --version
SAM CLI, version 0.40.0
```

```yaml
  ServerlessRestApi:
    DependsOn: HelloWorldFunction
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        openapi: "3.0.2"
        info:
          version: 1.0.0
        paths:
          /hello:
            get:
              operationId: hello
              responses:
                '200':
                  description: |-
                    200 response
                  content:
                    text/html: {}
```

**Observed result:**

Rest API is created with endpoint type EDGE

**Expected result:**

Rest API is created with endpoint type REGIONAL

**Comment by sriram-mv** [comment]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-endpointconfiguration.html as shown in the example, you need to add an explicit Type.
