### ISSUE TITLE
executing sam validate fails on serverless-application-model/examples/2016-10-31/api_backend/template.yaml

### ISSUE THREAD

**Issue by tim-pugh** [aws/serverless-application-model#1442]
**Description:**

executing sam validate fails on serverless-application-model/examples/2016-10-31/api_backend/template.yaml

**Steps to reproduce the issue:**
1.execute "sam validate" on serverless-application-model/examples/2016-10-31/api_backend/template.yaml

**Observed result:**
sam template fails validation with following:

Error: [InvalidResourceException('GetFunction', "Policy at index 0 in the 'Policies' property is not valid"), InvalidResourceException('PutFunction', "Policy at index 0 in the 'Policies' property is not valid"), InvalidResourceException('DeleteFunction', "Policy at index 0 in the 'Policies' property is not valid")] ('DeleteFunction', "Policy at index 0 in the 'Policies' property is not valid") ('GetFunction', "Policy at index 0 in the 'Policies' property is not valid") ('PutFunction', "Policy at index 0 in the 'Policies' property is not valid")

**Expected result:**
sam template succeeds validation

**Comment by tim-pugh** [comment]
additionally the package.json is missing, which may/or may not confuse some novice users.

It may be useful to include a README.md similiar to the api_cognito_auth example.

**Comment by Ghoul-SSZ** [comment]
The indentation is not correct.

`      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table`

Then the validation will pass through

**Comment by Smlep** [comment]
This issue should be closed, as it is not relevant anymore since this example was removed (https://github.com/aws/serverless-application-model/pull/1680).

**Comment by laurencefinny** [comment]
> The indentation is not correct. if you add one more tab at TableName
> e.g.
> 
> ```
> Policies:
>   - DynamoDBReadPolicy:
>       TableName: !Ref Table
> ```
> 
> Then the validation will pass through

Still its giving a error
