### ISSUE TITLE
AWS::Serverless::Api Custom Domain TLS version

### ISSUE THREAD

**Issue by darylounet** [aws/serverless-application-model#1445]
Hi,
When I create a AWS::Serverless::Api resource with custom domain I can't specify the TLS version, TLS 1.0 is the default.
It would be great to have the [SecurityPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#cfn-apigateway-domainname-securitypolicy) parameter in order to specify TLS_1_2.

**Comment by sc-alscient** [comment]
For anybody watching, there is a PR here: https://github.com/awslabs/serverless-application-model/pull/1546

**Comment by kirnberger1980** [comment]
As we do have regulatory requirements to use TLS 1.2 this feature is needed for automated deployment.

**Comment by boonew2** [comment]
Seems like this feature request got merged with https://github.com/aws/serverless-application-model/pull/1725

Just tested though and it didn't work so i'm guessing that the code hasn't been pushed live yet

**Comment by xavier-thomas** [comment]
Tested this now and it seems to be fixed. I'm able to enable TLS 1.2 on the API gateways via SAM.
