### ISSUE TITLE
AWS::Serverless::Api Property "RestApiId" does not support If, Map Functions

### ISSUE THREAD

**Issue by colinbjohnson** [aws/serverless-application-model#1470]
**Description:**

The `AWS::Serverless::Api` does not support particular functions such as `Fn::If` and `Fn::FindInMap`. My use case is that particular `AWS::Serverless::Function` resources my SAM template may have events coming from different API Gateways depending on a parameter I pass in.

**Steps to reproduce the issue:**

Given the following template:

```
AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Conditions:

  IsProd:
    Fn::Equals:
      - !Ref Environment
      - prod

Parameters:

    Environment:
      Type: String
      Default: prod
      AllowedValues: 
        - prod

Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:

  PublicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Public AWS Api Gateway
      StageName: Staging

  PrivateAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Private AWS Api Gateway
      StageName: Staging

  HelloWorldFunctionPrivate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !If [ IsProd, !Ref PublicAWSApiGateway, !Ref PrivateAWSApiGateway ]

Outputs: {}
```

Run the command:

`sam validate --debug`

**Observed result:**

The following result is returned:

```
Error: [InvalidResourceException('HelloWorldFunctionPrivate', 'Event with id [HelloWorld] is invalid. Api Event must reference an Api in the same template.'), InvalidResourceException('HelloWorldFunctionPublic', 'Event with id [HelloWorld] is invalid. Api Event must reference an Api in the same template.')] ('HelloWorldFunctionPrivate', 'Event with id [HelloWorld] is invalid. Api Event must reference an Api in the same template.') ('HelloWorldFunctionPublic', 'Event with id [HelloWorld] is invalid. Api Event must reference an Api in the same template.')
```

**Expected result:**

1. Expected result is that the given `AWS::Serverless::Function` would be associated with the given API Gateway returned by the `If` or `FindInMap` function.

**Comment by ShreyaGangishetty** [comment]
Thanks for the feature request! We have passed this along to our product team for possible prioritization. Please +1 on the feature to help with prioritization.

**Comment by ayozemr** [comment]
I was going crazy with this error until found this issue... Thanks for looking into it!

**Comment by sandun-rezg** [comment]
I have the same issue. 
RestApiId property of Api event must reference a valid resource in the same template.
Any update on this issue?

**Comment by si3mshady** [comment]
I am unable to import an exported RestApi from a CFN template to a SAM template (which is CFN under the hood)

Stack A - excerpt 

Outputs:
    SandboxApiOutput:
      Description: Description of value to be outputted 
      Value: !Ref booksapiE1885304
      Export:
        Name: "BookAPI-Reference-for-lambda-function"



 MyLambda:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: I-DID-IT-MyLambda
        Handler: index.Handler
        # CodeUri: 
        Events:
          MyLambda:
                Type: Api
                Properties:
                    Path: /example
                    Method: post
                    RestApiId:
                        Fn::ImportValue:
                          "BookAPI-Reference-for-lambda-function"


 [InvalidResourceException('MyLambda', 'Event with id [MyLambda] is invalid. Api Event must reference an Api in the same template.')] ('MyLambda', 'Event with id [MyLambda] is invalid. Api Event must reference an Api in the same template.')

**Comment by Kanakala** [comment]
hi @si3mshady Have you figured it out on how to use a restAPI resource over cross templates?

**Comment by smohadjer** [comment]
No solution found yet?

**Comment by urko-b** [comment]
> you figured it out on how to use a restAPI resource over cross

Hi any new information about this problem? Is it available to use an api in cross template?

**Comment by hoffa** [comment]
You might be able to get this to work by adding [`AWS::LanguageExtensions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html) to `Transform` as such:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

`AWS::LanguageExtensions` [resolves intrinsic functions](https://aws.amazon.com/blogs/mt/introducing-new-language-extensions-in-aws-cloudformation/) if the value is known when `Transform`s are run.

See https://github.com/aws/serverless-application-model/issues/2533 for more information.

**Comment by hoffa** [comment]
Closing in favor of https://github.com/aws/serverless-application-model/issues/2533.
