### ISSUE TITLE
FindInMap does not work in AllowOrigins (CorsConfiguration)

### ISSUE THREAD

**Issue by adrai** [aws/serverless-application-model#1515]
**Description:** The new feature https://github.com/awslabs/serverless-application-model/pull/1381 (cors for http-api) does not resolve FindInMap

**Steps to reproduce the issue:**
this works:
```json
        "CorsConfiguration": {
          "AllowOrigins": [
            "http://localhost:3001"
          ],
          "AllowHeaders": [
            "Authorization",
            "Content-Type"
          ],
          "AllowMethods": [
            "GET",
            "HEAD",
            "PUT",
            "PATCH",
            "POST",
            "DELETE"
          ],
          "ExposeHeaders": [
            "X-Next-Page"
          ]
        }
```

this not:
```json
"Mappings": {
    "EnvMap": {
      "dev": {
        "origins": [
          "http://localhost:3000"
        ]
      }
    }
  }
...
        "CorsConfiguration": {
          "AllowOrigins": {
            "Fn::FindInMap": [
              "EnvMap",
              {
                "Ref": "Environment"
              },
              "origins"
            ]
          },
          "AllowHeaders": [
            "Authorization",
            "Content-Type"
          ],
          "AllowMethods": [
            "GET",
            "HEAD",
            "PUT",
            "PATCH",
            "POST",
            "DELETE"
          ],
          "ExposeHeaders": [
            "X-Next-Page"
          ]
        }
```

**Comment by ShreyaGangishetty** [comment]
@adrai Thank you for reporting this! This will be fixed in #1529 PR

**Comment by dannymoscoso** [comment]
might as well call it AllowOrigin as it does not allow multiple origins

**Comment by hoffa** [comment]
You might be able to get this to work by adding [`AWS::LanguageExtensions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html) to `Transform` as such:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

`AWS::LanguageExtensions` [resolves intrinsic functions](https://aws.amazon.com/blogs/mt/introducing-new-language-extensions-in-aws-cloudformation/) if the value is known when `Transform`s are run.

See https://github.com/aws/serverless-application-model/issues/2533 for more information.

**Comment by hoffa** [comment]
Closing in favor of https://github.com/aws/serverless-application-model/issues/2533.
