### ISSUE TITLE
How to use AdditionalVersionWeights and AutoPublishAlias at the same time

### ISSUE THREAD

**Issue by devend123** [aws/serverless-application-model#1527]
I want to use the 'AutoPublishAlias' ​​property of `AWS::Serverless::Function` resource, because every time CodeUri changes, the version will be automatically released, and Alias ​​will automatically point to the latest version. This is more convenient than using `AWS::Lambda::Alias` ​​resources directly.

But I also noticed that the AdditionalVersionWeights property is missing when using AutoPublishAlias ​​compared to using `AWS::Lambda::Alias`.

My case is like this: use `sam deploy --parameter-overrides weight=90` to manually specify the traffic ratio of the new version and if test ok, gradually migrate the traffic to 100% .

So, for a stack, I have to deploy it at the beginning without specify the traffic ration. Then modify the code, deploy it again, and specify the traffic ratio to the previous version.

I have two questions here:

1. How to configure AdditionalVersionWeights for Alias ​​while using AutoPublishAlias?
2. The `AutoPublishAlias` transformed `AWS::Lambda::Version` resource logicId is random.
How can I get previous or latest version of my function?

**Comment by ShreyaGangishetty** [comment]
@devend123  Thanks for the feature request! We have passed this along to our product team for possible prioritization. Please +1 on the feature to help with prioritization.

It is not possible to get the previous version of function in SAM because SAM is stateless

**Comment by devend123** [comment]
If I can't get the latest version, Does it mean that I must manually specify another version when using AutoPublishAlias and AdditionalVersionWeights?

**Comment by sriram-mv** [comment]
AutoPublishAlias is unique to SAM and does not have a way to input AdditionalVersionWeights directly. I will log this as a request.

**Comment by jfuss** [comment]
Thanks for the feature request but this creates a weird deployment model within CloudFormation. Instead of specifying a weight, deploy, test, update weight, deploy, test, repeat, you should use DeploymentPreferences. This is specifically designed for this use-case and allows you to weight traffic through CodeDeploy while the stack is being updated.

Closing as DeploymentPreferences is the way to do this request in SAM/CloudFormation.
