### ISSUE TITLE
SAM deployment resets the Cognito User pool settings for custom email messages

### ISSUE THREAD

**Issue by dattatrayhkulkarni** [aws/serverless-application-model#1548]
We are using SAM for deploying our stacks on AWS.

In one of the stacks, we create the Cognito User Pool and the App client , etc.

We manually configure the custom e-mail message and the FROM email address ARN, for the User verification messages.

When we re-deploy our stacks, this stack is also deployed. In the re-deployment, there are no changes in the Cognito User pool. 

There is no impact on the Cognito User pools or the app client IDs, after the re-deployment. Bu  the custom e-mail message and the From e-mail message is  reset.

Is there any solution for this issue?

**Comment by sriram-mv** [comment]
@dattatrayhkulkarni could give an example of a template? need additional information to answer your question.

**Comment by CoshUS** [comment]
Closing as investigation is blocked without template.
Feel free to provide more information below and I will reopen this issue.
