### ISSUE TITLE
Feature Request: AWS SAM does not support Description property for AWS::Serverless::Api

### ISSUE THREAD

**Issue by piersf** [aws/serverless-application-model#1552]
**Description:**
This is not a bug or an issue. It is more like a feature request.

I noticed while creating an API today that AWS SAM does not support a `Description` property for `AWS::Serverless::Api` resource.

Can this property be added to AWS SAM? We have many APIs created and currently, it's not easy to tell their usage. So, being able to set the `Description` property would be a very nice ability to have.

**Expected result:**

`AWS::Serverless::Api` has a `Description` property where we set a custom description:

```
MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "MyApi"
      StageName: "v1"
      Description: "This is my API"
```

Thank you

**Comment by piersf** [comment]
If somebody could point me the right direction about where to start, I'd be happy to try adding support for this myself and then submit a pull request. 

I tried to look in the repo but could find a starting point(some type of function/class or file where I should start)

**Comment by fvant** [comment]
Is there a reason why it was not added from the start ?  CFN supports it... and it looks straightforward enough to add, what issue are we running into ?

**Comment by piersf** [comment]
Hi there,

Are there any updates on this feature request?

Thank you in advance!

**Comment by fvant** [comment]
It needs to be added here and probably some test cases:
-  https://github.com/aws/serverless-application-model/blob/02ec8bf95e33d8e5da536a75ad16cb9c6ff69d09/samtranslator/validator/sam_schema/schema.json 
- https://github.com/aws/serverless-application-model/blob/97dbedfeb2551633f32b02b14e271cc84fd3c5a1/samtranslator/model/sam_resources.py
