### ISSUE TITLE
CloudFront throws temporary errors on GET requests after deploy is complete

### ISSUE THREAD

**Issue by Santiago8888** [aws/serverless-application-model#1598]
**Description:**
After deploying SAM, when invoking a GET lambda call, CloudFront issues me an error:  *User is not authorized to access this resource*. Naturally, no logs are available as the lambda was not triggered at all. After a couple of minutes the function is available, but the CI/CD pipeline failed. 

**Steps to reproduce the issue:**
1. Deploy a SAM Application with API Gateway in EDGE model. 
2. Build a GET Lambda function.
3. Create a pipeline that tests the created endpoint after the CloudFormation stack was deployed.

**Observed Headers response result:**
```
{ 
    ...
    'x-cache': 'Error from cloudfront',
}
```

**Expected Headers response  result:**
```
{
    ...
    'x-cache': 'Miss from cloudfront',
}

```

**Comment by sriram-mv** [comment]
If the deployment succeeded succesfully, this could possibly be an issue with cloud front caching? (such as doing origin pulls).

Can you reproduce this in a consistent manner? even when not using SAM.

**Comment by jfuss** [comment]
Closing given no response. If this is still something that needs attention, please create a new Github Issue.
