### ISSUE TITLE
api gateway get endpoint returns 404 with swagger integration

### ISSUE THREAD

**Issue by abMatillion** [aws/serverless-application-model#1626]
[swagger.yaml](https://pastebin.com/Fj7tvcDs)

[template.yaml](https://pastebin.com/tnj3JHbJ)

Where am I going wrong configuring a get request with swagger integration?

I get a 404 page not found error in testing post deployment.

I think x-amazon-apigateway-integration is to blame as when I do a post request then it works fine but fails on a get request, I've seen many examples online from the official aws-sam examples where a get request to a lambda uses httpMethod=POST within x-amazon-apigateway-integration.
[example](https://github.com/aws-samples/lambda-apigateway-twilio-tutorial/tree/master/sam)
Locally running aws-sam works fine with the get request though I'm not using cloud formation which is parsing the external swagger.xml file I think

Where am I going wrong?

**Comment by jfuss** [comment]
Closing given the age. If this is something you still need help with, please create a new Github Issue. Thanks.
