### ISSUE TITLE
Support SecurityPolicy in DomainConfiguration

### ISSUE THREAD

**Issue by shawnduxy** [aws/serverless-application-model#1629]
Currently, DomainConfiguration model in AWS::Serverless::Api does not support SecurityPolicy property, so all custom domains are created with TLS 1.0. It's better to support this property so we can create custom domains with TLS 1.0.

**Comment by timoschilling** [comment]
Duplicate of #1445

There is already a PR for this feature. https://github.com/awslabs/serverless-application-model/pull/1546
