### ISSUE TITLE
Add Support for State in CloudWatchEvent/EventBridgeRule/Schedule events for AWS::Serverless::Lambda

### ISSUE THREAD

**Issue by nmoutschen** [aws/serverless-application-model#1630]
**Description:**

When creating an EventBridge rule for a Lambda function through AWS::Serverless::Events, it's not possible to specify a State. This means that rules will always default to the ENABLED state.

**Steps to reproduce the issue:**
1. Create a template with an AWS::Serverless::Lambda resource containing an EventBridgeRule event with a State property.
2. Run cfn-lint

**Observed result:**

cfn-lint fails with the following error message:

```E0001 Error transforming template: Resource with id [OnEventsFunctionEvent] is invalid. property State not defined for resource of type CloudWatchEvent```

**Expected result:**

No error.

**Comment by valerena** [comment]
It looks like this was addressed in #2497

**Comment by hoffa** [comment]
@valerena Thanks for noticing; indeed:

- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-cloudwatchevent.html#sam-function-cloudwatchevent-state
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html#sam-function-eventbridgerule-state
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html#sam-function-schedule-state

Resolving as done.
