### ISSUE TITLE
"errorMessage":"incorrect header check" facing this issue when decompress a gzip file using zlib in nodejs

### ISSUE THREAD

**Issue by daniyalkukda90** [aws/serverless-application-model#1646]
getting this issue "errorMessage":"incorrect header check" when decompress a gzip file using zlib in nodejs

my code is

const zlib = require("zlib")
const WriteStream = require("../export/createWriteStream")

module.exports.gzip = async (params) => {
    try {
        const feedResponse = await s3.getObject({ Bucket: feedBucket, Key: feedFile }).createReadStream()
        const bucket = params.bucket
        const key = params.key
        const { writeStream, uploadPromise } = WriteStream.createWriteStream(bucket, key)
        const unzip = zlib.createGunzip();
        feedResponse .pipe(unzip).pipe(writeStream)
        const res = await uploadPromise
    } catch (error) {
        console.log(error.message);
    }
}

**Comment by elbayaaa** [comment]
Thanks a lot @daniyalkukda90 for reaching out. Would you please clarify why do you think this is a SAM issue.

**Comment by elbayaaa** [comment]
Closing as no response. please reopen if you still have any questions.
