### ISSUE TITLE
AWS Serverless Application Repository Quotas: s3 artifacts cannot exceed 104857600 bytes

### ISSUE THREAD

**Issue by rumeshkrish** [aws/serverless-application-model#1653]
**Description:**

The combined size of your application version s3 artifacts cannot exceed 104857600 bytes. Please try reducing the combined size of your artifacts and try again. Contact AWS Support for further help.

**Comment by jhonnymertz** [comment]
Hey @rumeshkrish, did you find a solution to this problem? I'm facing the same issue at this moment.

**Comment by mgrandis** [comment]
This issue is not coming from the serverless-application-model itself.
If you are still having this issue, please contact the support through the AWS console.
