### ISSUE TITLE
All Policy Templates example template file is missing results in 404 when following link from docs/policy_templates.rst 

### ISSUE THREAD

**Issue by patrickgreenwell** [aws/serverless-application-model#1677]
**Description:**
With PR #1694  the all policy template examples file  /2016-10-31/policy_templates/all_policy_templates.yaml has been removed breaking a link in one of the docs. 

Vi in the docs the link to the all_policy_templates.yaml example is broken. resulting in a 404.

**Steps to reproduce the issue:**
1. View https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
2. Click the link to all_policy_templates.yaml

**Observed result:**
Link results in 404.

**Expected result:**
A link to the document that was originally at [ef92c3f](https://github.com/awslabs/serverless-application-model/blob/ef92c3f/examples/2016-10-31/policy_templates/all_policy_templates.yaml)

Note this example template is not available in https://github.com/aws-samples/serverless-app-examples either

**Comment by jfuss** [comment]
Thanks for bringing this up. Would you be interesting it providing a PR that updates the link to https://github.com/awslabs/serverless-application-model/blob/develop/tests/translator/input/all_policy_templates.yaml

**Comment by patrickgreenwell** [comment]
@jfuss Submitted the PR #1682

**Comment by jfuss** [comment]
@patrickgreenwell Thanks for the fix. I merged this into develop. I am going to leave this open until we do our next release and merge into our master branch.

**Comment by imoby** [comment]
This is broken in a lot of the documentation, even the one here I was trying to reference: https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/api_gateway_responses is this something that is planned on being added eventually?

**Comment by wchengru** [comment]
This is released. Close.
