### ISSUE TITLE
Prevent parameter overrides from logging into the console

### ISSUE THREAD

**Issue by nandita121189** [aws/serverless-application-model#1691]
When sam deploy command is run, it logs something like this

    Deploying with following values

	===============================

	Stack name                 : stack-name

	Region                     :  us-west-1

	Confirm changeset          :  False

	Deployment s3 bucket       :  ABCDEF

	Capabilities               : ["CAPABILITY_IAM"]

	Parameter overrides        : {'AppBucket': 'ASDFASDF', 'param2':'val2'}

I have some sensitive information in the parameter overrides. I have created a pipeline to deploy my SAM application.So every time a build is run this log entry gets logged in my codebuild logs. Now due to this log, my values of the parameter overrides are being logged into my codebuild cloudwatch logs group. And any person with access to cloudwatch logs can see that information in the logs. I can obviously set the retention period of logs to a very small time so that they are automatically deleted after that time. But still it doesn't solve the root cause of the problem that I do not want the parameters overrides to be logged in the first place. Can this be avoided in any way. I tried searching a lot of options of doing so but couldn't find anything. One option is to stop logging for a command using bash script but that way none of the logs are logged that is needed for checking the progress/status of a sam deploy command.

Does anyone have any ideas on how to prevent the parameter overrides from logging or some workaround that I can try?

**Comment by sriram-mv** [comment]
If you are passing in anything sensitive as a parameter, I recommend moving that logic to secrets manager. Otherwise you can look at making your parameter a NoEcho.
