### ISSUE TITLE
Slack invite link is broken in README.md

### ISSUE THREAD

**Issue by jeremywmoore** [aws/serverless-application-model#1692]
Description:

While carefully and optimistically navigating into the GitHub landing page of the SAM project, scrolling through the text and finding URL "Join the SAM developers channel (#samdev)" and clicking on it, leads to an expired Slack URL.

Have the community moved somewhere else? which slack? or everybody migrating to Teams?

Steps to reproduce the issue:

Navigate to https://github.com/awslabs/serverless-application-model
Press on "Join the SAM developers channel (#samdev)"
Observed result:
This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available.

Expected result:
🍺

h/t to @vladibb for the last time this was filed

**Comment by misk0** [comment]
Can someone please replace this link with valid one? I can not find way to join awsdevelopers on slack channel. Thanks

**Comment by HIJUMPER** [comment]
The Slack invite link is broken again. Can someone please share the link?
