### ISSUE TITLE
Current release not matching msi in documentation link....

### ISSUE THREAD

**Issue by MHacker9404** [aws/serverless-application-model#1693]
The repo is showing the current release is 1,26, but the [https://github.com/awslabs/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi](url) installs version 1.1.0?

**Description:**

**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Comment by awood45** [comment]
The AWS SAM CLI is currently version `1.2.0`, and at the time this was posted, was on `1.1.0`, so there is no issue here. The AWS SAM CLI depends on the SAM Transform package, which is at version 1.26.0 and can also be directly installed via `pip`, for example.
