### ISSUE TITLE
AWS::Serverless::HttpApi not implemented in AWS CDK

### ISSUE THREAD

**Issue by juancpgo** [aws/serverless-application-model#1694]
Looking at the AWS CDK reference under "aws-sam", there's no construct matching SAM's "**AWS::Serverless::HttpApi**", there's only the construct for REST APIs:

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sam-readme.html

Is that something we'll have to wait to be implemented, or can we already use it somehow?

**Comment by jfuss** [comment]
Hey @juancpgo, This repo is centered around the SAM Spec. CDK looks to be behind (we don't maintain the cdk constructs). Please see https://github.com/aws/aws-cdk/issues/7493

Closing as this is not related to this repo.
