### ISSUE TITLE
Cannot set Api Event function timeout

### ISSUE THREAD

**Issue by popart** [aws/serverless-application-model#1701]
**Description:**

The "Api" event type spec in "AWS::Serverless::Function" doesn't have a way to set the timeout. Can you add a way to set the "Integration Request" timeout that API Gateway uses when invoking the Lambda function?

**Comment by meetsushantpatil** [comment]
This is already addressed and available publicly:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html

**Comment by aaythapa** [comment]
Thats for the `HttpApi` event I think the OP meant the `Api` event (this [doc](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html)). There is another discussion opened for this request #3287. Closing this and tracking it there
