### ISSUE TITLE
sam command throws errors after install (linux)

### ISSUE THREAD

**Issue by kuba-gaj** [aws/serverless-application-model#1722]
**Description:**

After following installation steps I end up with errors when invoking sam command.
I used official installation guide and installed using `homebrew`, I'm on ArchLinux.

**Steps to reproduce the issue:**
1. `brew tap aws/tap`
2. `brew install aws-sam-cli`
3. `sam --version`

**Observed result:**
```
/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

**Expected result:**
No errors

**Comment by flyinprogrammer** [comment]
the dependencies are all goofed. you need to `brew install python@3.7`

on top of that -- why isn't it installing a more recent version of SAM CLI? 1.4.0 for OSX and 1.2.0 for linux? what happened?

**Comment by flyinprogrammer** [comment]
Turns out I am dumb, and this isn't the right place to ask this question/issue:

https://github.com/aws/aws-sam-cli <-- is where we want to ask questions like this, and 1.4.0 is latest. So much to learn, pardon my mistake.

**Comment by flyinprogrammer** [comment]
Also I suspect https://github.com/aws/homebrew-tap/pull/138 will fix our problems.

**Comment by mndeveci** [comment]
Sorry for the inconvenience, this was created during an issue with homebrew bottle creation. Please re-open this if you still have some issues.
