### ISSUE TITLE
Make EventBridgeRule support retry policy and DLQ config

### ISSUE THREAD

**Issue by ljacobsson** [aws/serverless-application-model#1738]
EventBridge now supports retry policies and DLQ config.

In addition to [InputTransforms](https://github.com/aws/serverless-application-model/issues/1535) it'd be good to get support for these.

The current state of `EventBrideRule` is very counterproductive to developers as one often starts off quick and easy using the SAM transform and later realise they need to transform the input or add resilience

**Comment by aaythapa** [comment]
Closing this as support for retry policy and DLQ config was added with [this PR](https://github.com/aws/serverless-application-model/pull/1842)
