### ISSUE TITLE
AWS::Serverless::HttpApi does not support DisableExecuteApiEndpoint

### ISSUE THREAD

**Issue by kmkale** [aws/serverless-application-model#1750]
**Description:**
CloudFormation resource AWS::ApiGatewayV2::Api supports the [DisableExecuteApiEndpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#cfn-apigatewayv2-api-disableexecuteapiendpoint) property. But the AWS::Serverless::HttpApi resource does not.

This property is useful when using custom domain with the api. Especially when using the new MTLS feature.

**Steps to reproduce the issue:**
1. Add `DisableExecuteApiEndpoint: true` to properties of a Type: AWS::Serverless::HttpApi resource in template.yaml
2. Run `sam validate`

**Observed result:**
$sam validate            
Template provided at '/path/to/template.yaml' was invalid SAM Template.
Error: [InvalidResourceException('HttpApi', 'property DisableExecuteApiEndpoint not defined for resource of type AWS::Serverless::HttpApi')] ('HttpApi', 'property DisableExecuteApiEndpoint not defined for resource of type AWS::Serverless::HttpApi')
**Expected result:**
AWS::Serverless::HttpApi resource supports the DisableExecuteApiEndpoint property, validation and deploy succeeds.

**Comment by wchengru** [comment]
We will release #1725 to support it.

**Comment by wchengru** [comment]
This feature is released in SAM 1.29.0.

**Comment by pankajagrawal16** [comment]
Getting this error when trying to use it now as soon as I set  DisableExecuteApiEndpoint: True in my SAM template

![image](https://user-images.githubusercontent.com/8058415/98382665-c3876b00-204b-11eb-8e5c-75faf52ee049.png)
