### ISSUE TITLE
AWS::Serverless::HttpApi property HttpApiDomainConfiguration does not support MutualTlsAuthentication

### ISSUE THREAD

**Issue by kmkale** [aws/serverless-application-model#1751]
**Description:**
The AWS::ApiGatewayV2::DomainName resource supports [MutualTlsAuthentication](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-domainname-mutualtlsauthentication.html) property, but AWS::Serverless::HttpApi resource [HttpApiDomainConfiguration](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapidomainconfiguration.html) does not.

As a result we have to resort to adding CloudFormation resources AWS::ApiGatewayV2::DomainName and AWS::ApiGatewayV2::ApiMapping to the SAM template. Also we then have to add AWS::Route53::RecordSet to map the custom domain to a DNS A record.

Would love to see the new Mutual TLS feature fully supported in SAM.

**Comment by wchengru** [comment]
We will release #1725 to support it.

**Comment by wchengru** [comment]
This feature is released in SAM 1.29.0.
