### ISSUE TITLE
Link in Safe Deployments documentation is outdated

### ISSUE THREAD

**Issue by pcolazurdo** [aws/serverless-application-model#1755]
**Description:**
I'm trying to follow the documentation for Safe Deployments but found a broken link 
In https://github.com/aws/serverless-application-model/blame/master/docs/safe_lambda_deployments.rst#L293 the link  
is broken and can't find any similar content.

The line says:
```
Checkout the lambda_safe_deployments folder for an example for how to create SAM template that contains a hook function.
```

hope this helps

**Comment by qingchm** [comment]
@pcolazurdo Hey I'll take a look at what this folder is referring to, meanwhile please check out this repo to see if you find helpful examples: https://github.com/amazon-archives/serverless-app-examples

**Comment by qingchm** [comment]
@pcolazurdo the document you are looking for is still available here: https://github.com/aws/serverless-application-model/tree/release/v1.7.0/examples/2016-10-31/lambda_safe_deployments, but let me check with the team on why the documentation contains outdated links
