### ISSUE TITLE
Service: AmazonCloudFront; Status Code: 503; Error Code: ServiceUnavailable; 

### ISSUE THREAD

**Issue by mikezang** [aws/serverless-application-model#1763]
**Description:**

**Steps to reproduce the issue:**
1. I create a LambdaEdgae with CloudFront and S3 with template
2. if I set `TrustedSigners` to self and run `sam deploy`, LambdaEdge function, s3 bucket and cloudfront are created without any problems
![behaviorsOK](https://user-images.githubusercontent.com/1030268/97777851-301ae980-1bb6-11eb-83a4-846004d6857b.jpg)
3. I if  only change `TrustedSigners` to key group what I defined on cloudfront console and run the same `sam deploy`,
![keygroup jog](https://user-images.githubusercontent.com/1030268/97777336-dc5ad100-1bb2-11eb-8a74-4928eb1e18b1.JPG)

**Observed result:**
 I got error as below:
> CloudFront encountered an internal error. Please try again. (Service: AmazonCloudFront; Status Code: 503; Error Code: ServiceUnavailable;
 
**Expected result:**
Here is what I set manual on CloudFront console
![behaviorsKeyGroup](https://user-images.githubusercontent.com/1030268/97777892-7e2fed00-1bb6-11eb-8a3b-50622c74a64e.jpg)

Is this a bug? how can I use key group in cloudformation to deploy coudfront?

**Comment by sriram-mv** [comment]
Q: Are you using SAM resources? from your description it seems like you are using sam deploy to deploy your cloudformation stack. Please comment and we can re-open this issue if it's SAM related and add more detail with respect to the template.
