### ISSUE TITLE
DeletionPolicy:Retain on SNS Topic doesn't get cleaned up in Rollback

### ISSUE THREAD

**Issue by dougmolineux** [aws/serverless-application-model#1819]
**Description:**

DeletionPolicy:Retain on SNS Topic doesn't get cleaned up in Rollback, but it also doesn't get added to the stack. So future deployments fail with "SNS Topic already exists". We've been getting around this by manually deleting the SNS Topic, but I would imagine that if it was created successfully, it should still be added to the Cloudformation stack, so that the deployment can succeed again in the future.

**Steps to reproduce the issue:**
1. Create a template that has an SNS Topic with DeletionPolicy: Retain
2. Deploy template but have it fail somehow so that a Rollback is started
3. Logs will show that the Deletion was skipped
4. Stack doesn't contain SNS Topic, but it still exists
5. Subsequent deployments fail due to SNS Topic already existing

**Observed result:**
SNS Topic will exist, but not inside cloudformation stack.

**Expected result:**
SNS Topic will exist, and the stack will contain reference to the created topic. Or the topic gets deleted in Rollback.

**Comment by sriram-mv** [comment]
@dougmolineux is this a SAM template? or a general cloudformation template? Just ensuring, before routing this internally.

**Comment by dougmolineux** [comment]
Sorry for the slow reply, yes it was a SAM template. 

It does seem to "clash" when a new stack is built. Thank you!
