### ISSUE TITLE
Failed to create CloudFormation change set: Received malformed response

### ISSUE THREAD

**Issue by Douglas0n** [aws/serverless-application-model#1834]
**Description:**
Trying to deploy sam application end receiving an error 

**Steps to reproduce the issue:**
1. sam build
2. sam deploy --guided

**Observed result:**

        Configuring SAM deploy
        ======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]: validesk-events
        AWS Region [us-east-1]: 
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: y
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: y
        Save arguments to configuration file [Y/n]: y
        SAM configuration file [samconfig.toml]: 
        SAM configuration environment [default]: 

        Looking for resources needed for deployment: Not found.
        Creating the required resources...
        Error: Failed to create managed resources: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state

and in cloudFormation:

* stack event: aws-sam-cli-managed-default = REVIEW_IN_PROGRESS
* change set: initialCreation = FAILED

**Expected result:**

aws-sam-cli-managed-default = CREATE_COMPLETE

**Comment by rmarable** [comment]
I'm seeing the same behavior.  This is most likely associated with today's ongoing service disruption in us-east-1.  Moving to another Region should resolve your issues, assuming your infrastructure has been architected to use multiple Regions.

**Comment by Douglas0n** [comment]
> I'm seeing the same behavior. This is most likely associated with today's ongoing Kinesis service disruption in us-east-1. Moving to another Region should resolve your issues, assuming your infrastructure has been architected to use multiple Regions.

problem solved! today 11/26/2020, thank you for your help.

**Comment by CoshUS** [comment]
Closing as issue is solved.
