### ISSUE TITLE
AWS::Serverless::HttpApi does not inherit stack tags

### ISSUE THREAD

**Issue by iRoachie** [aws/serverless-application-model#1838]
### Description:

AWS::Serverless::HttpApi resource does not inherit tags created at the stack level. Tags specified for the stack should be added to all resources of that stack. AWS::Serverless::HttpApi completely ignores these.

### Steps to reproduce:

- Create a new sam project
- Add `AWS::Serverless::HttpApi` in your template and reference to an `AWS::Serverless::Function` with a handler
- Create a samconfig.yml with `sam deploy --guided`
- Specify a tags property in your samconfig.yml and deploy

I've provided a repo https://github.com/iRoachie/sam-app

### Observed result:
The created Http Api does not have any tags, while the stack, and lambdas do.
<img width="990" alt="Screenshot 2020-11-25 at 7 41 54 AM" src="https://user-images.githubusercontent.com/5962998/100223312-b397d400-2ef1-11eb-95db-acffbaad2f51.png">

<img width="1032" alt="Screenshot 2020-11-25 at 7 42 21 AM" src="https://user-images.githubusercontent.com/5962998/100223355-c5797700-2ef1-11eb-9311-d258c2f6f943.png">

<img width="916" alt="Screenshot 2020-11-25 at 7 42 36 AM" src="https://user-images.githubusercontent.com/5962998/100223446-e346dc00-2ef1-11eb-9bd8-cd90fab218b3.png">

### Expected result:

- The Http Api should inherit the tags from the stack. For my example, it should have two additional tags `project=sam`, `environment=prod`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac 10.15.6
2. `sam --version`: 1.12.0 (I've also replicated on sam 1.10.0)

**Comment by iRoachie** [comment]
Hey @CoshUS how where can I start looking to implement this? Do you have any other PRs for reference?

**Comment by CoshUS** [comment]
Hi @iRoachie, after digging a bit more into the issue, it seems this is not related to SAM but on how CloudFormation passes stack level tag to resources. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
>Tagging implementations might vary by resource. For example, AWS::AutoScaling::AutoScalingGroup provides an additional, required PropagateAtLaunch property as part of its tagging scheme.

CFN doesn't propagate tags to AWS::ApiGatewayV2::Api whether the stack is deployed using SAM or not.

**Comment by iRoachie** [comment]
Ahh I see, is this something done intentionally then?

Is there another repo that manages which resources are allowed to inherit stack tags?

**Comment by CoshUS** [comment]
Not sure whether this is intentional or not as this is on API Gateway side. 
You can try contacting AWS support or the API Gateway forums https://forums.aws.amazon.com/forum.jspa?forumID=199.

**Comment by iRoachie** [comment]
Okay cool man, reached out to some persons from AWS on Twitter. Thanks for putting me in the right direction 💯

**Comment by akleiber** [comment]
@iRoachie have had any luck to get a response from AWS on this?

**Comment by iRoachie** [comment]
@akleiber Yes! It's being tracked internally https://twitter.com/roach_iam/status/1361844476541620224
