### ISSUE TITLE
Update Documentation- S3 Bucket Versioning for Code Signing

### ISSUE THREAD

**Issue by dontirun** [aws/serverless-application-model#1850]
**Description:**

I ran into an issue using Code Signing were I would run into the error

`Error: Unable to upload artifact lambda/functions/my-function referenced by CodeUri parameter of rMyFunction resource.
'VersionId'`

I eventually resolved the issue by enabling Bucket Versioning on my S3 bucket that I was using for deployments. I know that this is specific to Code Signer, but the [SAM documentation for configuring Code Signing](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/authoring-codesigning.html) does not mention this. I believe that the documentation should be updated to mention this since S3 upload buckets normally don't require versioning for SAM usage

**Comment by xazhao** [comment]
Hi @dontirun thanks for posting this documentation request. In the link you provided there is note section mentioning `versioning must be enabled for the Amazon S3 bucket`. 

Closing this issue since it has been fixed.
