### ISSUE TITLE
feat(policy-templates): add AcmGetCertificatePolicy

### ISSUE THREAD

**Issue by forzagreen** [aws/serverless-application-model#1854]
### Related Pull Request

#1853 

### Description of changes

Added a policy template `AcmGetCertificatePolicy` that give a permission to read a certificate from AWS Certificate Manager. 

- **Granted permission**: [GetCertificate](https://docs.aws.amazon.com/acm/latest/APIReference/API_GetCertificate.html) ( `acm:GetCertificate` )

- **Resource**: The certificate ARN. 
I pass the full certificate's ARN, not the id, because the CloudFormation resource [AWS::CertificateManager::Certificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html) returns only the ARN.

### Usecase

Lambda function in a private network making HTTPS requests to a private server. The Lambda needs to add the certificate chain to its CA Bundle.

**Comment by moelasmar** [comment]
this PR got deployed

**Comment by forzagreen** [comment]
@moelasmar I don't think this was deployed. There is no ACM policy in [Policy template list](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html).
Do you have the release number ?

**Comment by moelasmar** [comment]
@forzagreen it seems we need to update the Docs, but I can see that this PR was released in release [V1.35.0](https://github.com/aws/serverless-application-model/releases/tag/v1.35.0)

**Comment by forzagreen** [comment]
Thanks @moelasmar . I created a PR in https://github.com/awsdocs/aws-sam-developer-guide/pull/145 to update the docs.
