### ISSUE TITLE
Typo in serverless-application-model documentation?

### ISSUE THREAD

**Issue by Zanndorin** [aws/serverless-application-model#1861]
I got here from the AWS news for MSK events.

https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#msk

says `Type: Kinesis` instead of `Type: MSK`. I assume this to be a typo?

https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/
uses `Type: MSK`

**Comment by mndeveci** [comment]
Thanks for pointing out, I made the changes to the doc, it should be updated once it is merged.
