### ISSUE TITLE
Publish Failed Error: The template contains unsupported resource types. [AWS::CloudWatch::CompositeAlarm]

### ISSUE THREAD

**Issue by chgerkens** [aws/serverless-application-model#1864]
**Description:**

When I publish a serverless application that contains a AWS::CloudWatch::CompositeAlarm resource to the Serverless Application Repository (via sam-cli or console), it fails with the message:

> Publish Failed
> Error: The template contains unsupported resource types. [AWS::CloudWatch::CompositeAlarm]

**Steps to reproduce the issue:**
1. Create a SAM application template
2. Add a resource of type AWS::CloudWatch::CompositeAlarm
3. Publish SAM application, **incl. SemanticVersion**, either via SAM CLI or AWS console

**Observed result:**
Publish Failed

**Expected result:**
Publish Succeeded

**Comment by WooSung-Jung** [comment]
Can you upload template yaml file?

**Comment by chgerkens** [comment]
Sample SAM template:
[template.yml.txt](https://github.com/aws/serverless-application-model/files/5708323/template.yml.txt)

**Comment by mndeveci** [comment]
Hi @chgerkens ,

I tried to publish the template that you provided, and I was able to publish it by providing metadata section on the top. Something like this;
```
Metadata:
  AWS::ServerlessRepo::Application:
    Name: my-app
    Description: hello world
    Author: mndeveci
```

More information can be found here; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html

One thing that might be causing your issue is, if you are using one of the opt-in regions, this resource (`AWS::CloudWatch::CompositeAlarm`) might not be available in that feature, can you verify this as well?

Thanks

**Comment by chgerkens** [comment]
Hi @mndeveci,

the error only occurs if the metadata contains a  **SemanticVersion**:

```
Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-serverless-application-model-issues-1864
    Description: SAM Application incl. a Composite CloudWatch Alarm resource
    Author: chgerkens
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/aws/serverless-application-model/issues/1864
```

Updated [template.yml](https://github.com/aws/serverless-application-model/files/5726374/template.yml.txt)

Without the SemanticVersion, I was able to publish too.

**Comment by mndeveci** [comment]
@chgerkens I confirm that publish fails when you define `SemanticVersion` to the metadata. I also tried using `aws` CLI to publish this to SAR but that one failed as well.

The only possible way is to upload template directly to SAR Console through Web UI, and that one works as expected.

I will check with the SAR team about the failure here.

**Comment by hoffa** [comment]
Leaving crumb trail to another issue with publishing to SAR: https://github.com/aws/serverless-application-model/issues/1618

**Comment by sopel** [comment]
I'll note that `AWS::CloudWatch::CompositeAlarm` is indeed not listed within the (disappointingly limited) [List of Supported AWS Resources for the AWS Serverless Application Repository](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html), so I'm not surprised about the seemingly accurate error message, rather about the ability to upload the template via the console regardless 🤔

**Comment by xazhao** [comment]
Yep the error message accurate:
```
Error: The template contains unsupported resource types. [AWS::CloudWatch::CompositeAlarm]
```
Because `AWS::CloudWatch::CompositeAlarm` is not in the supported AWS resources list: https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html

**Comment by ssenchenko** [comment]
Closing it because it doesn't relate to SAM-T, it's SAR
