### ISSUE TITLE
Deprecate Python 2.7 on AWS SAM

### ISSUE THREAD

**Issue by hawflau** [aws/serverless-application-model#1872]
AWS SAM (Serverless Application Model) is an open source framework for building serverless applications. It provides shorthand templates to express lambda functions, APIs, event source mappings etc. With just a few lines per resource, you can define the application you want and model it using JSON or YAML. During deployment, SAM transforms and expands the SAM template into AWS CloudFormation, enabling developers to build serverless applications faster and more easily.

### What is the deprecation schedule?

Currently, AWS SAM can be installed in Python versions 2.7 and 3.6 or above. As of February 16th, 2021, we will drop support for Python 2.7 in AWS SAM.

### Am I impacted by this deprecation?

If you installed AWS SAM in Python 2.7, please consider installing AWS SAM in Python 3.6 or above.

**Comment by jfuss** [comment]
We have dropped support for Python 2.7 in develop and is waiting a release to PyPi.

**Comment by jfuss** [comment]
Was dropped in https://pypi.org/project/aws-sam-translator/1.43.0/ 

Closing.
