### ISSUE TITLE
Slack invite link is broken in README.md

### ISSUE THREAD

**Issue by cmurtaugh** [aws/serverless-application-model#1875]
Description:

While carefully and optimistically navigating into the GitHub landing page of the SAM project, scrolling through the text and finding URL "Join the SAM developers channel (#samdev)" and clicking on it, leads to an expired Slack URL.

Have the community moved somewhere else? which slack? or everybody migrating to Teams?

Steps to reproduce the issue:

Navigate to https://github.com/awslabs/serverless-application-model
Press on "Join the SAM developers channel (#samdev)"
Observed result:

The Slack registration page only allows email addresses in the `weave.works` and `netcracker.com` domains. Huh?

```
You can use any account with the domain:
weave.works
netcracker.com
Don’t have an email address from one of those domains? 
Contact the workspace administrator at AWS Developers for an invitation.
```

Expected result:
🍺

h/t to @jeremywmoore for the last time this was filed

**Comment by jfuss** [comment]
@cmurtaugh Sorry for the inconvenience. Our Slack URL does expire after a certain amount of time. I will get a new one generated and update the README.

**Comment by cmurtaugh** [comment]
Thanks! FWIW, the link is also broken in the `aws-sam-cli` readme.

**Comment by mgrandis** [comment]
Fixed in 1.34: https://github.com/aws/serverless-application-model/releases/tag/v1.34.0
Thanks @cmurtaugh!
We will fix the SAM CLI repo readme.

**Comment by pratikpc** [comment]
@mgrandis it seems the link broke again

![image](https://user-images.githubusercontent.com/28534575/107151142-0f1d1e00-6987-11eb-8483-fe496773bc9d.png)

**Comment by Petesta** [comment]
I clicked on the link to join the group but since I don't have an email with one of the listed domains, I can't. Do I reach out here for an invitation because of the output below? 

```
Don’t have an email address from one of those domains?
Contact the workspace administrator at AWS Developers for an invitation.
```

**Comment by Petesta** [comment]
> I clicked on the link to join the group but since I don't have an email with one of the listed domains, I can't. Do I reach out here for an invitation because of the output below?
> 
> ```
> Don’t have an email address from one of those domains?
> Contact the workspace administrator at AWS Developers for an invitation.
> ```

@jfuss

**Comment by krcm0209** [comment]
@jfuss Maybe something can be done to auto-update the slack link? It's broken again?
