### ISSUE TITLE
Add integration to non lambda backends

### ISSUE THREAD

**Issue by sdole** [aws/serverless-application-model#1880]
**Steps to reproduce the issue:**
1. Add a non-lambda, non-sam api gateway integration to a SAM template (we have an integration to cloudsearch)
2. run sam build, package and deploy.

**Observed result:**
The cloudsearch integration is dropped from the sam deployment to api gateway.

**Expected result:**
At the very least, sam should let the cloudsearch path to not be undeployed. Ideally, there should be a sam declaration to integrate from api gateway to backend services.

Potential work around:
a) do not intermix sam and non-sam resources in cloudformation (create separate stack with potentially a separate api gateway)
b) use cloudformation custom resource magic to effect whatever is needed.

**Comment by hoffa** [comment]
Thanks for the report. Could you share the SAM template that you used?

**Comment by CoshUS** [comment]
Closing as there is no new information provided.
