### ISSUE TITLE
Does SAM support creating API methods of mock integration type?

### ISSUE THREAD

**Issue by jojenreed** [aws/serverless-application-model#1886]
**Description:**
It is possible to create AWS API gateway methods of type 'mock' through the console and through pure cloudformation. Does SAM support this feature as well? I could not find any examples for this in the official docs.

**Comment by hoffa** [comment]
You can do so using [`type: mock`](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html) in the OpenAPI definition (e.g. [`DefinitionBody`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-definitionbody)).
