### ISSUE TITLE
[bug] Creating an MQ event without providing a Role

### ISSUE THREAD

**Issue by jfuss** [aws/serverless-application-model#1888]
**Description:**

If you configure an Event to create an MQ event source and do not provide a Role, SAM will generate a role with an invalid ManagedPolicy.

**Workaround:**
To use the MQ event, you will need to provide a Role to the `AWS::Serverless::Function` instead of relying on the generated Role from SAM.

**Comment by qingchm** [comment]
Fixed with https://github.com/aws/serverless-application-model/pull/1891
