### ISSUE TITLE
Runtime, Handler, Layers cannot be present when PackageType is of type `Image`

### ISSUE THREAD

**Issue by rockey5520** [aws/serverless-application-model#1890]
**Description:**

Runtime, Handler, Layers cannot be present when PackageType is of type `Image`

**Steps to reproduce the issue:**
1. SAM template with function resource and Image as packaging type and LambdaInsightsExtension as layer

**Observed result:**
Getting error as  Resource with id [XXXXX] is invalid. Runtime, Handler, Layers cannot be present when PackageType is of type `Image`

**Expected result:**
valid sam file

**Comment by jfuss** [comment]
@rockey5520 From the error message, what you are trying to do is invalid. Layers are not supported if the PackageType is Image. This is a restriction from Lambda itself and is there because with an Image you have full control over the filesystem and therefore do not need Layers at all (you can put them into the image yourself).

Closing as this is not supported.

**Comment by rockey5520** [comment]
@jfuss Here in this case i am trying to add layer:LambdaInsightsExtension as per the link https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-SAM-CLI.html

How would I achieve this with Image as PackageType ? 

Thanks in advance for your help

**Comment by jfuss** [comment]
Only `PackageType: Zip` supports layers. So if you are following those docs, the function MUST be `PackageType:Zip`. If you want to use Image, you will need to add the code to the image yourself. This can probably be done by, getting the zip of the Layer through [`get-layer-version-by-arn`](https://docs.aws.amazon.com/cli/latest/reference/lambda/get-layer-version-by-arn.html), downloading the zip, and then unzipping into the `/opt` (or whatever the directory Lambda looks for extensions in).

**Comment by smcpeck** [comment]
A great post about how to bring extensions into your lambda containers: https://aws.amazon.com/blogs/compute/working-with-lambda-layers-and-extensions-in-container-images/

Elaborates on what @jfuss recommends with specific details and examples.
