### ISSUE TITLE
question: does "sam local" now support HttpApi with DisableExecuteApiEndpoint ?

### ISSUE THREAD

**Issue by lancety** [aws/serverless-application-model#1898]
Hi there,
My project yaml just updated to use AWS::Serverless::HttpApi, which deployed to aws successfully. But my "sam local" start reporting the error 
_Error: [InvalidResourceException('MyApi', 'property DisableExecuteApiEndpoint not defined for resource of type AWS::Serverless::HttpApi')] ('MyApi
', 'property DisableExecuteApiEndpoint not defined for resource of type AWS::Serverless::HttpApi')
[1] cd entry.api.package/atlas_pub && sam local start-api -p 3010 -t template.json exited with code 1
--> Sending SIGTERM to other processes.._

After search this issue I found https://github.com/aws/serverless-application-model/issues/1750, which said fixed in 1.29,  I downloaded sam cli few days ago, the created date of that download file is 18/12/2020 11:02 AM, so it should be new version I guess.

Just want to confirm new version fixed the issue in 1750, or maybe I need to update my installed sam cli to a much newer version?

**Comment by aahung** [comment]
What does your template look like? And what version of sam-cli are you using? (`sam --version`)

**Comment by lancety** [comment]
hi @aahung It was about my aws-cli version too old.   there is no issue about httpApi or aws cli itself.   Sorry to reply this late.  And thanks for your help and good to see your sample HttpApi template which make me feel more confident what proper format it should looks like.  
I will close this ticket.

**Comment by aahung** [comment]
> hi @aahung It was about my aws-cli version too old. there is no issue about httpApi or aws cli itself. Sorry to reply this late. And thanks for your help and good to see your sample HttpApi template which make me feel more confident what proper format it should looks like.
> I will close this ticket.

That's great to know!
