### ISSUE TITLE
AutoPublishAlias makes sam deployments slow

### ISSUE THREAD

**Issue by formanojhr** [aws/serverless-application-model#1908]
We have added AutoPublishAlias: live to help preprovisioning our specific functions for warm up.  
```
AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 15
```

**Description:**

When we use sam deploy we are finding the above section consumes lot of time to finish deployment compared to without the above section. We understand that this is due pre warming of the lambdas for preprovisioning size requested (in this case 15). But, is there a way to avoid blocking the sam deploy from waiting for the lambdas to come up. This will drastically improve our deployment and development velocity. 

**Steps to reproduce the issue:**
1. Add the section above 
2. sam deploy takes in the order of 15 mins or more for deployment.

**Observed result:**

**Expected result:**
Avoid paying deployment time penalty to add the ProvisionedConcurrencyConfig section to the function definition.

**Comment by mgrandis** [comment]
@formanojhr 
This is unfortunately by design, we don't get a callback until all of the concurrent executions are provisioned.

**Comment by formanojhr** [comment]
ok thanks @mgrandis
