### ISSUE TITLE
Issues with Function Event Source EventBridgeRule

### ISSUE THREAD

**Issue by beck3905** [aws/serverless-application-model#1920]
### Description:

I have run into a couple of issues with the `EventBridgeRule` event source on an `AWS::Serverless::Function`.

1. Not providing `TargetId` in the properties means SAM will provide a default value.  However, SAM uses the `Function`'s logical ID + 'LambdaTarget' (https://github.com/aws/serverless-application-model/blob/6059c19258b97f67354ff0315d04a1a4d0683409/samtranslator/model/eventsources/push.py#L146).  This will fail if the logical ID of the `Function` is too long as there is a 64 character limit on the `TargetId` property.  Ideally, either the `LambdaTarget` suffix would not be added at all, or the entire logical ID + `LambdaTarget` would be shortened to make sure it is not more than 64 characters.

2. I provided a `TargetId` value in the properties of the event and my changeset failed with an error message
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyEvent] is invalid. property TargetId not defined for resource of type EventBridgeRule
```
After digging in the SAM source code I found that the `TargetId` property is not actually valid.  The source code is looking for 
```
Target:
    Id: MyTarget
```
rather than `TargetId: MyTarget`.
The documentation at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html#sam-function-eventbridgerule-targetid as well as the error messaging appears to not match what is expected by the SAM tranform.

### Steps to reproduce:

1. Create a SAM template with an `AWS::Serverless::Function` with a long resource name.  Add an `EventBridgeRule` event source to the `Function` without a `TargetId` property.  SAM deploy.

2. Create a SAM template with an `AWS::Serverless::Function`.  Add an `EventBridgeRule` event source to the `Function` with a `TargetId` property.  SAM deploy.

### Observed result:

1. CloudFormation showed error
```
1 validation error detected: Value 'MyFunctionMyEventLambdaTarget' at 'targets.1.member.id' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: efbe7081-8d9b-4052-91c1-ee09f889af84; Proxy: null)
```

2. CloudFormation showed error
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunctionMyEvent] is invalid. property TargetId not defined for resource of type EventBridgeRule
```
When `EventBridgeRule` event source properties in the template were updated from `TargetId: MyTarget` to
```
Target:
    Id: MyTarget
```
CloudFormation successfully deployed my stack.

### Expected result:

1. CloudFormation/SAM deploy succeeds with a shortened resource name for `EventBridgeRule` `Target`.
2. CloudFormation/SAM deploy succeeds with `TargetId` property on `EventBridgeRule` event source.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS X Catalina
2. If using SAM CLI, `sam --version`: N/A
3. AWS region: us-east-1

**Comment by elbayaaa** [comment]
Thanks a lot @beck3905 we fixed the documentation to reflect the code. Now you can set `{Target: {Id: "id"}}` to work around the 64 character limitation.

**Comment by beck3905** [comment]
@elbayaaa Is there anyway that the 64 character limit could be addressed so we wouldn't need the workaround of providing a targetId?  Perhaps, not using the `LambdaTarget` suffix or shortening the whole string before setting it in the template like what is done elsewhere in SAM?

**Comment by elbayaaa** [comment]
@beck3905 this issue of default-generated values exceeding the limit is common across SAM and the workaround is to give an explicit value. Fixing it here only will not solve the whole issue. Also, removing the `LambdaTarget` suffix will not solve the issue for longer logical IDs. Finally, truncating to 64 character may cause a collision(if truncating the last X chars) or result in an unclear value(if truncating from the middle). So, the decision was to let the user define an explicit value in this case.
