### ISSUE TITLE
Add Amazon Connect Policy template

### ISSUE THREAD

**Issue by tejasb09** [aws/serverless-application-model#1953]
### Describe your idea/feature/enhancement

Please can we add Amazon Connect policy templates. This should allow calling the Amazon Connect Service API from SAM applications.

**Comment by jfuss** [comment]
@tejasb09 What Policies are you looking to have as a Policy Template? We can add them if there is general value. 

You can always add your own Policies to an `AWS::Serverless::Function` using the `Policies` property. I know it is not as easy but still doable.

**Comment by CoshUS** [comment]
Closing as this is blocked by not enough details.
Feel free to provide more information below and I will reopen this issue.
