### ISSUE TITLE
[Feature Request] Allow Lambda Layers to be updated and exported in a shared stack as long as they are retained

### ISSUE THREAD

**Issue by rupe120** [aws/serverless-application-model#1956]
### Describe your idea/feature/enhancement

Currently, deploys of Lambda Layer updates fail if they are in a different stack than the function or functions that use them, and the reference to them is exported in the output parameters. 

It would be helpful if layers could be defined in a separate stack, their reference exported, and allow for a new version to be created, as long as the old version is retained.

### Proposal

Loosen the export/import validation rules

### Additional Details

Without this it is impossible to create a shared "library" stack to serve multiple function stacks. Templates become overwhelmingly large when everything is combined into a single template, and using nested stacks masks errors in the referenced stacks. 0

Alternatively, I would be OK if the error reporting of nested stacks actually reported what failed within the nested stack when it fails

**Comment by jfuss** [comment]
@rupe120 Thanks for the Request but SAM can't do much here as this is a restriction on how CloudFormation works. The best next step is to reach out on the [CloudFormation Public roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap) and create an issue there. 

Closing as this is not actionable by SAM.

**Comment by rupe120** [comment]
If anyone is interested in showing support, I submitted the CloudFormation request here https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/903
