### ISSUE TITLE
SAM mis-recognises https://Bucket.s3.Region.amazonaws.com TemplateURLs

### ISSUE THREAD

**Issue by athewsey** [aws/serverless-application-model#1977]
### Description:

When defining a `AWS::CloudFormation::Stack` resource that *already exists on S3*, SAM misinterprets some URL schemes as being local files - and then fails since it can't find the local file to upload.

Specifically I observed that URLs like this are accepted:

```text
https://{BucketName}.s3.{Region}.amazonaws.com/{Path}
```

...Whereas this triggers the error:

```text
https://s3.{Region}.amazonaws.com/{BucketName}/{Path}
```

In my case, I was **already using the former URL scheme** for a `AWS::ServiceCatalog::CloudFormationProduct` resource elsewhere in the stack (which I think SAM doesn't interpolate, so wasn't causing an error)... So the error was pretty confusing and I didn't see clear documentation for which URL schemes are supported.

I'd argue for making SAM a bit more liberal in its interpretation of what is clearly a URL and not a local file - surely we shouldn't be trying to interpret **anything** that starts with `http(s)://` as a local file path?

### Steps to reproduce:

- Create/find a CloudFormation template already uploaded to S3
- Create a SAM stack with a resource something like:

```
  DemoProjectInstance:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://my-bucket-name.s3.ap-southeast-1.amazonaws.com/my-path/template.yaml
```

- Run `sam build && sam package` on your SAM template

### Observed result:

```
2021-03-31 19:32:23,567 | Unable to export
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.10.0/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 287, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.10.0/libexec/lib/python3.8/site-packages/samcli/lib/package/artifact_exporter.py", line 498, in do_export
    raise exceptions.InvalidTemplateUrlParameterError(
samcli.commands.package.exceptions.InvalidTemplateUrlParameterError: TemplateURL parameter of DemoProjectInstance resource is invalid. It must be a S3 URL or path to CloudFormation template file. Actual: /Users/[...]/.aws-sam/build/https:/my-bucket-name.s3.ap-southeast-1.amazonaws.com/my-path/template.yaml
2021-03-31 19:32:23,581 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 3214, 'exitReason': 'ExportFailedError', 'exitCode': 1, 'requestId': 'f3add52a-62e2-41e8-b981-cc8802b7c3c1', 'installationId': 'af617857-8281-4fe5-94a7-45ae8e131779', 'sessionId': '57662b91-f1b6-41d9-ae03-eae46fe8cdc1', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.10.0'}}]}
2021-03-31 19:32:24,240 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Unable to upload artifact https://my-bucket-name.s3.ap-southeast-1.amazonaws.com/my-path/template.yaml referenced by TemplateURL parameter of DemoProjectInstance resource.
TemplateURL parameter of DemoProjectInstance resource is invalid. It must be a S3 URL or path to CloudFormation template file. /Users/[...]/.aws-sam/build/https:/my-bucket-name.s3.ap-southeast-1.amazonaws.com/my-path/template.yaml
make: *** [build.environment] Error 1
```

### Expected result:

SAM recognises that the `TemplateURL` is already an S3 URL, and leaves it unchanged.

(Maybe even resolves URIs to the required format, e.g. `s3://mybucket/path/template.yaml` to an https URL?)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina
2. If using SAM CLI, `sam --version`: 1.10.0
3. AWS region: `ap-northeast-2`

**Comment by mingkun2020** [comment]
link to a similar [issue](https://github.com/aws/aws-sam-cli/issues/2779)

**Comment by sriram-mv** [comment]
Closing this as a duplicate, the issue @mingkun2020 linked has am active PR against it which should solve this issue.
