### ISSUE TITLE
Use API DefinitionBody and Api EventSource Together

### ISSUE THREAD

**Issue by cmarshall10450** [aws/serverless-application-model#1981]
### Description:

I am trying to create an API which has routes to invoke Lambda functions but also routes to send data to a Kinesis Data Stream. I am using the AWS::Serverless::Function resource with an Api EventSource to add the route to the AWS::Serverless::Api resource that is also defined in my template. The AWS::Serverless::Api resource also has the `DefinitionBody` property defined to give a Swagger definition to define the routes for sending requests to Kinesis. This definition is based on the one from the AWS tutorial for sending data from API Gateway to Kinesis.

The deployed API only has the routes defined in the DefinitionBody and none of the routes defined in the Lambda functions.

### Steps to reproduce:
* Add definition from [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-as-kinesis-proxy-export-swagger-with-extensions.html) to DefinitionBody property of AWS::Serverless:Api resource
* Add EventSource of type Api to AWS::Serverless::Function resource
* Add RestApiId property to EventSource which references AWS::Serverless:Api resource

### Observed result:

The EventSource is not added to the Swagger definition.

### Expected result:

I expect both the Kinesis routes and the Lambda function routes to all be added to the API Gateway.

The [AWS::Serverless:Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-definitionbody) document suggests that SAM will add to the definition body before passing the template to CloudFormation

> If certain properties are provided, content may be inserted or modified into the DefinitionBody before being passed to CloudFormation. Properties include Auth, BinaryMediaTypes, Cors, GatewayResponses, Models, and an EventSource of type Api on for a corresponding AWS::Serverless::Function

**Comment by sriram-mv** [comment]
Looks to be related to an older bug: https://github.com/aws/serverless-application-model/issues/650. Closing this issue to track it there.
