### ISSUE TITLE
ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by yhor** [aws/serverless-application-model#1982]
**Description:**

why 2 week ago good work
sam deploy not deploy  

**Steps to reproduce the issue:**
1.  sam build
2.  sam deploy

**Observed result:**
OS - WINDOW

Error: Unable to upload artifact ExpressFunction referenced by CodeUri parameter of ExpressFunction resource.
ZIP does not support timestamps before 1980

**Expected result:**

Error: Unable to upload artifact ExpressFunction referenced by CodeUri parameter of ExpressFunction resource.
ZIP does not support timestamps before 1980

**Comment by sriram-mv** [comment]
Seems to be related to: https://github.com/aws/aws-cli/issues/2639 and underlying files changing.

**Comment by sriram-mv** [comment]
I'm closing this issue, feel free to comment here if it does not solve your issue and we can look at re-opening it.
