### ISSUE TITLE
LambdaAuthorizer is not recieving full path of the calling URL

### ISSUE THREAD

**Issue by rockey5520** [aws/serverless-application-model#2002]
### Description:
When Lambda is configured with HTTP API GW (with below routes structure) + Lambda Authorize payload 2.0, full path of the calling url is not available in the payload format as given in https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

![image](https://user-images.githubusercontent.com/1937561/116193460-b3fdfa80-a72f-11eb-925b-167b127f9ac5.png)

### Steps to reproduce:
Lambda is configured with HTTP API GW (with below routes structure) + Lambda Authorize payload 2.0 and attempt to log the payload in the lambda authorizer

### Observed result:
path: '/Prod/',

### Expected result:
path: '/Prod/users',

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. If using SAM CLI, `sam --version`: 1.20
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`
if this is not the right place to raise the issue for this problem, please do direct me to the right place. Thank you so much for the support.

**Comment by awood45** [comment]
I'm slightly confused about the issue here - is the issue that you're seeing what appears to be an invalid event in the Lambda function itself when running on AWS infrastructure?

This might be an AWS Support issue in that case, but if you're worried that the SAM template you're using might be misconfigured, we can look at that.

**Comment by rockey5520** [comment]
Hey Alex,

At the moment I trust the SAM template I configured is right, I will raise the issue with AWS support team. :)

Regards
Rakesh

**Comment by wchengru** [comment]
I will close this since the SAM template is correct. Please feel free to reopen it if you want.
