### ISSUE TITLE
Add `AWS::CloudFormation::ResourceVersion` & `AWS::CloudFormation::ResourceDefaultVersion` to SAR supported resources

### ISSUE THREAD

**Issue by jarreds** [aws/serverless-application-model#2013]
The new `AWS::CloudFormation::ResourceVersion` & `AWS::CloudFormation::ResourceDefaultVersion` are currently [not supported](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html) in AWS SAR.

Really bummed to have hit this. Any way to get them whitelisted ASAP?

Thanks!

**Comment by jfuss** [comment]
We (SAM) do not manage the Serverless Application Repository. So not anything we can directly do about this request. 

However, I forwarded this along to the SAR team. 

Closing as this is a request for SAR not SAM.
