### ISSUE TITLE
Adding Default Authorizer causes issues if combined with ANY method (API Gateway)

### ISSUE THREAD

**Issue by luketr03** [aws/serverless-application-model#2019]
### Description:
If in the template the any method is combined with the default authorizer, the following issue occurs upon updating the stack:

Waiting for changeset to be created..
Error: Failed to create changeset for the stack: ANYAPI, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Structure of the SAM template is invalid. Path '/test' contains method 'x-amazon-apigateway-any-method' which is not a supported method ['OPTIONS', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH']

### Steps to reproduce:

You can use the zip file I provided you with to see the issue. It contains a .yaml file. If the the default authorizer is commented and anything works fine. But if it is uncommented, it throws the above error.

[template.yml.py.zip](https://github.com/aws/serverless-application-model/files/6473603/template.yml.py.zip)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment]
Apologizes for the impact. We reverted the change yesterday and this should no longer be occurring (as of Yesterday afternoon).
