### ISSUE TITLE
Unable to publish AWS::CloudFront::Function

### ISSUE THREAD

**Issue by jplock** [aws/serverless-application-model#2052]
### Description:

I have a SAM project at https://github.com/smoketurner/sam-cdn that uses the new CloudFront Functions CloudFormation resources.  I'm not able to publish the project to the Serverless Application Repository.

```
Publish Failed
Error: The template contains unsupported resource types. [AWS::CloudFront::Function]
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Steps to reproduce:

```
git clone https://github.com/smoketurner/sam-cdn
cd sam-cdn
npm run build
npm run package --> executes sam package --template-file template.yml --output-template-file packaged.yml --s3-bucket mybucket
npm run publish --> executes sam publish --region us-east-1 --template packaged.yml
```

### Observed result:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/serverlessrepo/publish.py", line 66, in publish_application
    sar_client.create_application_version(**request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplicationVersion operation: The template contains unsupported resource types. [AWS::CloudFront::Function]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/samcli/commands/publish/command.py", line 86, in do_cli
    publish_output = publish_application(template_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/serverlessrepo/publish.py", line 70, in publish_application
    raise _wrap_client_error(e)
serverlessrepo.exceptions.ServerlessRepoClientError: The template contains unsupported resource types. [AWS::CloudFront::Function]
Error: The template contains unsupported resource types. [AWS::CloudFront::Function]
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Expected result:

Successfully able to publish

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.4
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.24.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by c2tarun** [comment]
`AWS::CloudFront::Function` is not currently a whitelisted resources, check [here](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html). Reaching out to SAR team to whitelist [AWS::CloudFront::Function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html).

**Comment by jplock** [comment]
Interesting, didn’t realize there was a whitelist. Thanks!

**Comment by jplock** [comment]
@moelasmar was the SAR whitelist updated?

**Comment by jplock** [comment]
@c2tarun can `AWS::CloudFront::ResponseHeadersPolicy` be added to the SAR team whitelist?

**Comment by yvele** [comment]
Why was this issue closed? Because `AWS::CloudFront::Function` will never be supported by AWS SAM?

My personal need is only to use SAW CloudFormation extension in order to use [FunctionCode](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html#cfn-cloudfront-function-functioncode) with a local path 🤔 is this possible right now?
