### ISSUE TITLE
Support mode property for Api

### ISSUE THREAD

**Issue by tkashi** [aws/serverless-application-model#2056]
### Describe your idea/feature/enhancement

As supported in CloudFormation, I wish SAM also support the mode property, which enables us to define how API Gateway handles resource updates by 'merge' or 'override'.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-mode

### Proposal

Add a 'mode' field to Api properties, whose value is either 'merge' or 'override'. And SAM passes its value to one in CloudFormation RestApi defenition.

Things to consider:
[ ] The [SAM documentation of Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) will need to be updated

**Comment by mndeveci** [comment]
We recently merged development for this support, you can find it here; https://github.com/aws/serverless-application-model/commit/c39d0a09623ea5eb47231682e20c97b7468ac481

**Comment by sriram-mv** [comment]
Closing as https://github.com/aws/serverless-application-model/releases/tag/v1.38.0 is out.
