### ISSUE TITLE
Is CI on travis-ci.com working?

### ISSUE THREAD

**Issue by shogo82148** [aws/serverless-application-model#2097]
### Description:

It looks that CI on travis-ci.com is not working.
What is that state?

### Steps to reproduce:
open https://travis-ci.com/github/aws/serverless-application-model/branches

### Observed result:

The latest build ran on https://github.com/aws/serverless-application-model/commit/e7a1496ab2e39b42bdddf5a7e6562cd8c5e170b4 about a month ago

![image](https://user-images.githubusercontent.com/1157344/126155812-f8d17cb4-5a56-4e2f-b795-b287e1bc825d.png)

### Expected result:

The latest commit on the develop branch is now https://github.com/aws/serverless-application-model/commit/f31309431090139b5a5c91a046d4337f967c7505
The build of this commit should be listed.

![image](https://user-images.githubusercontent.com/1157344/126156237-909bd342-4c2b-4cf9-b149-b6b0c18ee482.png)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

N/A

**Comment by jfuss** [comment]
We moved to appveyor: https://ci.appveyor.com/project/AWSSAMCLI/serverless-application-model/history

**Comment by shogo82148** [comment]
So, `.travis.yml` is no longer needed? https://github.com/aws/serverless-application-model/blob/f31309431090139b5a5c91a046d4337f967c7505/.travis.yml

**Comment by jfuss** [comment]
@shogo82148 Correct
