### ISSUE TITLE
Question: support for other APIGateway properties in SeverlessAPI

### ISSUE THREAD

**Issue by clippered** [aws/serverless-application-model#2110]
Hi,
I just want to ask how can I set other API gateway properties like "Default Endpoint disabled" and "Enable Cloudwatch logs" using Serverless::API resource?
Thanks

**Comment by sriram-mv** [comment]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html has DisableExecuteApiEndpoint

Don't see it directly on `AWS::Serverless::Api`
