### ISSUE TITLE
# [Codecov](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=h1) Report

### ISSUE THREAD

**Issue by adzney** [aws/serverless-application-model#2111]
# [Codecov](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=h1) Report
> Merging [#5969](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=desc) (36c34b6) into [develop](https://codecov.io/gh/aws/aws-cli/commit/f3998bf31020b2e0b57d3a6318f47edc81e308f7?el=desc) (f3998bf) will **not change** coverage.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/aws/aws-cli/pull/5969/graphs/tree.svg?width=650&height=150&src=pr&token=aKPbq1EbIm)](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=tree)

```diff
@@           Coverage Diff            @@
##           develop    #5969   +/-   ##
========================================
  Coverage    92.62%   92.62%           
========================================
  Files          203      203           
  Lines        16129    16129           
========================================
  Hits         14939    14939           
  Misses        1190     1190           
```

------

[Continue to review full report at Codecov](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=footer). Last update [f3998bf...36c34b6](https://codecov.io/gh/aws/aws-cli/pull/5969?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

_Originally posted by @codecov-io in https://github.com/aws/aws-cli/issues/5969#issuecomment-788156799_

**Comment by sriram-mv** [comment]
Unsure about what this issue is about. Closing this out, please re-open with more context if pertinent.
