### ISSUE TITLE
cloud formation sam output

### ISSUE THREAD

**Issue by autohandle** [aws/serverless-application-model#2120]
how do you display the sam cloud formation output so you can see the effect of macros/functions before deploying

**Comment by xazhao** [comment]
Hi @autohandle thanks for posting the questions. 

I think what you're looking for is option `--no-execute-changeset`. 
Description: Indicates whether to execute the changeset. Specify this option if you want to view your stack changes before executing the changeset. This command creates an AWS CloudFormation changeset and then exits without executing the changeset. To execute the changeset, run the same command without this option. 

Feel free to check the page if you want to look at other options: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html

**Comment by sriram-mv** [comment]
If you are trying to see what the transformed SAM -> Cloudformation template looks like, you can also use sam cli's handy sam validate --debug command which will showcase the final Cloudformation template.

However, keep in mind that full blown instrinsic resolution as done within the Cloudformation service will not be available when running this command locally.
