### ISSUE TITLE
False positive InvalidResourceException

### ISSUE THREAD

**Issue by scottkennedy** [aws/serverless-application-model#2125]
### Description:
Running `sam-translate.py` on a template that includes a Lambda function without `InlineCode` or `CodeUri` results in:
`samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('LambdaFunction', "Only one of 'InlineCode' or 'CodeUri' can be set.")]`.

However, the SAM template is compeltely valid and works fine with `sam deploy`, and If I add a dummy value (like `CodeUri: s3://bucket/key`), it translates, then I can remove the `"Code": { "S3Bucket": "bucket", "S3Key": "key" },` from the output, and that template works fine too.

### Steps to reproduce:

test.yaml:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: some-test
      Handler: some.test.package.Handler::handleRequest
      Runtime: java11
      MemorySize: 512
```

`python serverless-application-model/bin/sam-translate.py --template-file=test.yaml --output-template=out.json`

### Observed result:
```
Traceback (most recent call last):
  File "serverless-application-model/bin/sam-translate.py", line 107, in transform_template
    cloud_formation_template = transform(sam_template, {}, ManagedPolicyLoader(iam_client), feature_toggle)
  File "serverless-application-model/bin/../samtranslator/translator/transform.py", line 16, in transform
    return translator.translate(input_fragment, parameter_values=parameter_values, feature_toggle=feature_toggle)
  File "serverless-application-model/bin/../samtranslator/translator/translator.py", line 190, in translate
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('LambdaFunction', "Only one of 'InlineCode' or 'CodeUri' can be set.")]
```

### Expected result:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "FunctionName": "some-test",
        "Handler": "some.test.package.Handler::handleRequest",
        "MemorySize": 512,
        "Role": {
          "Fn::GetAtt": [
            "LambdaFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "java11",
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      }
    },
    "LambdaFunctionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      }
    }
  }
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.5.2
2. If using SAM CLI, `sam --version`:
3. AWS region: us-east-2

**Comment by jfuss** [comment]
@scottkennedy Why are you running `sam-translate.py`? It really only there to help with testing. 

The template is invalid. You need `InlineCode` or `CodeUri` otherwise the Lambda Function doesn't have any code associated with it. `sam deploy` default a `CodeUri` to the current directory to "be helpful".

So this is by design and I do not recommend using `sam-translate.py` for anything but testing a change you want to make to SAM's codebase.

**Comment by scottkennedy** [comment]
The SAM CLI doesn't have a local (offline) way to test SQS, so I'm using [LocalStack](https://github.com/localstack/localstack), so I needed to get a proper CloudFormation template in order to deploy there, for which I followed https://www.packetmischief.ca/2020/12/30/converting-from-aws-sam-to-cloudformation/

I guess if there were `sam local start-sqs` functionality, I wouldn't need any of this.

But based on your response, I'll try to get something sane set up for `CodeUri`.

Thanks

**Comment by jfuss** [comment]
`sam validate --debug` will print the transform template to stdout. Not sure how that wires up to LocalStack but that would be my proposal over some helper script we have in this repo for testing.

**Comment by scottkennedy** [comment]
Ugh that's so much easier.  Thanks.
