### ISSUE TITLE
Policy template for Lambda Function to describe step function execution

### ISSUE THREAD

**Issue by huanjiayang-ibm** [aws/serverless-application-model#2181]
### Describe your idea/feature/enhancement

I wish the policy template would contain a step function policy, potentially called StepFunctionsDescribeExecutionPolicy or similar, that would allow Lambda functions to describe a step function execution.
This would serve a common use case where a Lambda Function triggers a Step Function workflow and needs to block until it completes with an output.

### Proposal

Add the following policy to the sam policy template json file:
`    "StepFunctionsDescribeExecutionPolicy": {
      "Description": "Gives permission to describe a Step Functions state machine execution",
      "Parameters": {
        "StateMachineName": {
          "Description":"The name of the state machine to execute."
        }
      },
      "Definition": {
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "states:DescribeExecution"
            ],
            "Resource": {
              "Fn::Sub": [
                "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${stateMachineName}",
                {
                  "stateMachineName": {
                    "Ref": "StateMachineName"
                  }
                }
              ]
            }
          }
        ]
      }
    },`

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details
While triggering a step function through a API gateway endpoint, there is no option to block and wait for the output. We had to add a Lambda function between the API Gateway and the Step Function to trigger and return the output of the step function workflow.
I can imagine this would be a common use case even in a Lambda function that is not integrated with API Gateway.
Such Lambda functions can gain the permission to start execution of Step functions through the StepFunctionsExecutionPolicy in the policy template, but it also needs to keep describing the execution in order to watch its status and eventually getting its output, for which the permission states:DescribeExecution is required but not provided in any policy template.
Hence raising this feature request to add such a policy template.

**Comment by ssenchenko** [comment]
In October 2022 we lunched a new Serverless resource type [Connector](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html). The purpose is to remove pain of giving permissions to different serverless services so they can work together smoothly. We provide a set of ready to use connector profiles and among them there is one for Lambda-Step Function pair which includes [`"states:DescribeStateMachine"`](https://github.com/ssenchenko/serverless-application-model/blob/develop/samtranslator/model/connector_profiles/profiles.json#L316).  You can find more on connectors usage [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html).
