### ISSUE TITLE
Sam build failing with  Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document

### ISSUE THREAD

**Issue by FedericoBorra** [aws/serverless-application-model#2185]
### Description:

We are using SAM for our Lambdas and http APIs. The definition of the Api are written in a separated file using openapi: 3.0.1.  This has been working flawlessly for 1 year (yestergday everything was fine). However today when I deployed the stack it failed with the response:
`
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 3. Resource with id [BackendLambda] is invalid. Event with id [CountReferences] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template. Resource with id [BackendLambda2] is invalid. Event with id [GetReferenceInIndex] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template. Resource with id [BackendLambda3] is invalid. Event with id [AudiomatchSuccess] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template.
`

### Observed result:

`
2021-10-15 13:27:54,897 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '00f333ce-9f98-4b8a-acef-664b53d75167', 'installationId': '0c348a49-08ef-4cfb-bd5d-0319f0e694fe', 'sessionId': '19bd268c-0697-4e20-a929-0a6fc88c885b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.33.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': 'eu-central-1', 'commandName': 'sam deploy', 'duration': 14474, 'exitReason': 'ChangeSetError', 'exitCode': 1}}]}
2021-10-15 13:27:55,619 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: audiomatch-backend-dev, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 3. Resource with id [BackendLambda] is invalid. Event with id [CountReferences] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template. Resource with id [BackendLambda2] is invalid. Event with id [GetReferenceInIndex] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template. Resource with id [BackendLambda3] is invalid. Event with id [AudiomatchSuccess] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template.
`

### Expected result:
Success

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 11.3.1
2. If using SAM CLI, `sam --version`: 1.33.0
3. AWS region: eu-central-1

**Comment by jfuss** [comment]
@FedericoBorra Can you give us a min example based on your template? We attempted to patch a failure case: https://github.com/aws/serverless-application-model/pull/2159 and want to validate if we missed an edge case or something else is happening.

**Comment by jfuss** [comment]
@FedericoBorra Thanks for providing that. 

I think the best way forward it to update you template. Right now you have a Function that has an event type `API` but `RestApiId` references a `AWS::Serverless::HttpApi`. Which actually creates a `AWS::Serverless::Api` (turns into a Rest not Http API). I know this might have worked in the past but it's actually a pretty bad bug (creating a different resource than you actually expected).

Sorry for the inconvenience this causes but I think its actually better than keeping the old behavior.
