### ISSUE TITLE
Support APIGateWay Invocations with new SAM policy template

### ISSUE THREAD

**Issue by DanielLoyAugmedix** [aws/serverless-application-model#2202]
### Add AmazonAPIGatewayInvoke for specific Stage in Sam

I need a simple managed policy that I can attach in my SAM template  (in a Lambda in my case) that will allow me to have access to 

```
"execute-api:Invoke",
"execute-api:ManageConnections"
```

for a specific stage in api Gateway

I am actively doing this outside of SAM and I would like to not have this extra step in my workflow. 

### Proposal

This will require an extension to [policy_template.json](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json)

The new policy will need to be instantiated with stage. API id and region can be handled with the standard template language. 

Documentation [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated with this new policy

**Comment by xazhao** [comment]
Close this issue since it has been inactive for 1 month now. Feel free to reopen this if you have any other questions.
