### ISSUE TITLE
Unable to use the latest version of the lambda layer when enable canary deployment

### ISSUE THREAD

**Issue by faboulaye** [aws/serverless-application-model#2220]
### Description:

When we make a change on our layer and deploy change with canary deployment enabled our lambda don't call the latest version.

### Steps to reproduce:

1. Create a SAM template with one lambda  which call one function defined in the **layer** (This function we can just return something like `Version 0`). Add HttpAPi event on the lambda to make it available by http call
2. Enable the canary deployment.
3. For the first deployment everything is OK when we call our API with 
`curl --location --request GET 'https://<API_URL>/Prod/hello` we get `Version 0`
4. Now let's change the return function in the layer to `Version 1` and deploy once again
5. When we call our API we get `Version 1` instead of `Version 0` despite the fact that we can see the new version of layer apply to the lambda. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 
2. `sam --version`: 1.35.0
3. AWS region: eu-central-1

`Add --debug flag to command you are running`

**Comment by faboulaye** [comment]
It work but it can lead to a big issue on the long run if someone forget to do that.

**Comment by moelasmar** [comment]
I agree, this is just a workaround, and we will work on a fix for this issue

**Comment by faboulaye** [comment]
Any news on this issue ?

**Comment by jamesbellamy99** [comment]
Bumping this issue - would love to hear some news as it’s approaching a year

**Comment by aaythapa** [comment]
Thank you guys for reporting this, could you comment an exact SAM template that would help reproducing the issue you've had?

**Comment by faboulaye** [comment]
Hi of course you can find the code in this repository https://github.com/faboulaye/test-autopublish-alias-layer

**Comment by aaythapa** [comment]
Hi there, upon further investigation this change would break backwards compatibility. For now we should stick with the workaround that is mentioned above. This is connected to a larger issue with the AutoPublishAlias property that we hope have a fix for when we version bump SAM. Going to keep this ticket open till then.
