### ISSUE TITLE
AWS SAM generates Event Rules names longer than 64 characters

### ISSUE THREAD

**Issue by danemauland** [aws/serverless-application-model#2227]
### Description:
When creating an EventSource of type EventBridgeRule in a StateMachine resource definition, SAM generates a name for it by taking the StateMachine ID, and appending to it the EventSource ID and the string "StepFunctionsTarget". If this resulting name is over 64 characters, the stack update will fail. 

### Steps to reproduce:

Deploy a stack with a StateMachine resource that also defines an EventBridgeRule event source, where the length of the state machine ID and event bridge rule ID sum to at least 45, such as the following:

`"StateMachineIdWith30Characters": {
  "Type": "AWS::Serverless::StateMachine",
  "Properties": {
    "Events": {
      "EventIdWith23Characters": {
        "Type": "EventBridgeRule",
        "Properties": {
          "EventBusName": {
            "Fn::ImportValue": {
              "Fn::Sub": "${Environment}-ImproovyEventBusName"
            }
          },
          "InputPath": "$.detail",
          "Pattern": {
            "source": [
              "ImproovyWebHook"
            ],
            "detail-type": [
              "JustcallSms"
            ]
          }
        }
      }
    },
  },
},`

### Observed result:
1 validation error detected: Value 'StateMachineIdWith30CharactersEventIdWith23CharactersStepFunctionsTarget' at 'targets.1.member.id' failed  to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ...; Proxy: null)

### Expected result:
SAM to either truncate the generated name or provide a way to override the generated name.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux
2. `sam --version`: SAM CLI, version 1.31.0
3. AWS region: US-East-1

**Comment by ScottKelly** [comment]
I just ran into this issue as well. In case anyone else has this same problem, I'm going to try to use the normal CloudFormation Events Rule to work around it.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

**Comment by farski** [comment]
Probably this should have the same functionality available as Functions [got a while back](https://github.com/aws/serverless-application-model/pull/1747/files)

**Comment by xazhao** [comment]
Hello! I add a new property `Target` to `EventBridgeRule` so you can specify the Id of the target. It's quite similar with this one https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html#eventbridge-Type-Target-Id.

The change is currently in release so it should be available next week in all regions. Closing this issue.
