### ISSUE TITLE
lambda and API Gateway

### ISSUE THREAD

**Issue by moonming** [aws/serverless-application-model#2254]
### Describe your idea/feature/enhancement

We are adding support for AWS lambda in Apache APISIX: https://github.com/apache/apisix/pull/5594.

I am not sure whether SAM can be integrated with API Gateway? It would be better if you could provide more suggestions, thank you

**Comment by juzhiyuan** [comment]
👏

**Comment by xazhao** [comment]
Thanks for the feature request! I think this needs to be reviewed by our PM. Will create an internal task so the team is aware of this request.

**Comment by moonming** [comment]
> Thanks for the feature request! I think this needs to be reviewed by our PM. Will create an internal task so the team is aware of this request.

Sure, thanks. Please feel free to connect me if you need further information

**Comment by jfuss** [comment]
@moonming I am not sure what the ask is here. SAM does allow for you to specify a Lambda Function and wire it to API Gateway. Some doc links: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html, https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html, and https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html.

Is that what you are after? If not, can you be more specific on what you are looking for.

**Comment by jfuss** [comment]
Closing given no response. Feel free to re-open if https://github.com/aws/serverless-application-model/issues/2254#issuecomment-1055909759 did not answer the original question.
