### ISSUE TITLE
sam logs need to take care of profile option

### ISSUE THREAD

**Issue by yudao** [aws/serverless-application-model#2255]
### Description:

I work for multi accounts and need to target the right profile.

```javascript
sam init --runtime nodejs14.x --app-template quick-start-from-scratch --name sam-app
```

I can watch by profile
```javascript
sam sync --watch --stack-name sam-app --profile myProfile
```

But sam logs don't
```javascript
sam logs --stack-name sam-app --name HelloWorldFunction ---profile myProfile
Usage: sam logs [OPTIONS]
Try 'sam logs -h' for help.

Error: no such option: ---profile
```

### Steps to reproduce:

See commands up.

### Observed result:

See commands up.

### Expected result:

I wish the SAM logs would take care of profile option (--profile)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: 
```
  OS: macOS Monterey
  Version: 12.0.1 
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2,6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1715.40.15.0.0 (iBridge: 19.16.10549.0.0,0)
  OS Loader Version:	540.40.4~45
  Activation Lock Status:	Enabled

```
2. If using SAM CLI, `sam --version`:
```
SAM CLI, version 1.36.0 (installed by brew)
```
3. AWS region:
eu-west-1

**Comment by jfuss** [comment]
@yudao The command you ran use 3 dashes `---profile myProfile`. `--profile` is supported and can be seen in the `sam logs --help` output. 

Closing this as it is supported already
