### ISSUE TITLE
Enable moving resources between Applications/Stacks for easier refactoring

### ISSUE THREAD

**Issue by vleandersson** [aws/serverless-application-model#2257]
### Describe your idea/feature/enhancement

Ever so often, we engineers discover that a template is just growing out of hand and we need to break out parts of it to a new nested application / stack. For some resources, this is easily done (where deleting and setting up the new resource is simple, like standalone lambdas) but for other resources, like the API Gateway, this become a cumbersome operation using SAM.

### Proposal

It would be great to add in the import feature in the core engine for SAM, allowing moving a resource, like AWS API Gateway and its lambdas, into a new template and reference this one to the original stack (nested stacks). This could potentially be done by relying on the existing import functionality (read more on how to do this manually [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/refactor-stacks.html) )

As renaming and importing at the same time would be difficult to support, we could limit this feature to only support moving a resource without changing its name. This way, we could rely on the name to identify resources that has been moved and need to be imported. 

Logic
- If resource name is gone from parent stack:
  - check child stack if resource name is present -> run new import logic
  - if resource name is not present -> delete
  - if name is present in both parent and nested child stack -> throw an error

Suggested we would start supporting API Gateway for this feature (if decided to be implemented) as it is widely used, and a simple example where this is a challenge :)

### Additional Details

Supported resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

First feature request here, so a bit ruff on the edges 🙌  Comments, thoughts and feedback welcome!

**Comment by xazhao** [comment]
Hi Viktor! Thanks for proposing this feature. For this feature we need to get it reviewed by our PM first. I have created an internal task to keep track of it. We will post here once we have any updates from the team.

**Comment by vleandersson** [comment]
Brilliant @xazhao 
If you have a good approach for this (and believe this is a reasonable feature), but no time to implement, feel free to add it here and we can see if the community got time to pick it up

**Comment by ducpv-1774** [comment]
any update guys?

**Comment by ssenchenko** [comment]
Implementation of such a feature would have to deal with a lot of pitfalls. We'd like to see that that many customers are interested in this addition. Since this issue hasn't got many "thumbs-up" we haven't prioritized it yet and it's not in our road map so far.

There is a similar discussion https://github.com/aws/serverless-application-model/discussions/3303 please vote it up and comment there.

**Comment by paul-uz** [comment]
Can I suggest we reopen this issue as its specifically about moving resources which the other ticket doesn't really cover.

I would love to see this implemented but need it immediately so need to come up with another solution which is likely to just be a long winded upgrade path to slowly move resources to other template files.
