### ISSUE TITLE
Path Parameter Type Validation

### ISSUE THREAD

**Issue by stevehogdahl** [aws/serverless-application-model#2260]
We started using the ValidateParameters recently which has allowed us to strip out a lot of repetitive validations. Most of our path parameters are integers that we still have to cast to an int and validate. I haven't found a way to handle this more gracefully via the templates and was wondering if this is feasible enough to add as an enhancement request.

**Comment by ssenchenko** [comment]
Do you mean `ValidateParameters` from Request model (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestmodel.html)? Can you please also give an example?

**Comment by stevehogdahl** [comment]
Yeah, i was wondering if a possible feature enhancement would be to validate the types the path parameters. For example, most of our path parameters are integers, but always get to the API's as string so we have to parse them and validate as a positive integer. We're using `ValidateParameters` in this path `/accounts/{accountId}/status` and it works properly by requiring it, but `accountId` still needs to be parsed and validated.

**Comment by mndeveci** [comment]
Thanks for raising this issue @stevehogdahl!

This sounds like a feature request for APIGW -> Lambda integration. We will take this request to their PMs to investigate it further. I would also recommend for you to get in touch with support to raise this feature request with these teams.

In the meantime, please let us know if we can do anything at SAM side, which should improve the experience there.

Thanks!

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.
