### ISSUE TITLE
Drop Python2.7

### ISSUE THREAD

**Issue by JohnPreston** [aws/serverless-application-model#2266]
AWS Lambda has now dropped Python2.7 so I doubt there is much point keeping this compatible with python2 at all ?
If anything, this is a security concern and deprecation problem.

So what is the plan to address that ?

**Comment by mildaniel** [comment]
Thanks for opening this issue. Please refer to the following issue for more info https://github.com/aws/serverless-application-model/issues/2291

**Comment by jfuss** [comment]
Duplicate of https://github.com/aws/serverless-application-model/issues/1872

Closing
