### ISSUE TITLE
DisableExecuteApiEndpoint not working with SAM for Rest APIs

### ISSUE THREAD

**Issue by sattigar** [aws/serverless-application-model#2270]
### Description:
DisableExecuteApiEndpoint property is not working when created from SAM template.

### Steps to reproduce:
1. Created a simply API definition using DisableExecuteApiEndpoint property set as true.
2. Upload the SAM template to CF console.
3. Try invoking REST API with Default/ExecuteApiEndpoint URL.
Ideally, the API should not be successfully invoked. But with SAM template, it is not working as expected.
You can also find that the property is missed from processed template in CF console page.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by sattigar** [comment]
Working on the fix.

**Comment by ashanpw** [comment]
When will this be released to mainline? Additionally, SAM CDK doesn't support the new field yet. Could you add it? https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sam.CfnApi.html

**Comment by sattigar** [comment]
> When will this be released to mainline? Additionally, SAM CDK doesn't support the new field yet. Could you add it? https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sam.CfnApi.html

Property will be release in mainline by January 15th. SAM CDK is NOT been discussed/ in priority queue right now. But I will have a word with my team and let you know any details I can share.

**Comment by ashanpw** [comment]
Thanks for the update. We might be able to bypass the missing field in CDK by adding an override. I'll give it a shot and see!
`this.addPropertyOverride('DisableExecuteApiEndpoint', true);`

**Comment by sattigar** [comment]
Sorry about the delay but property isn't available yet, because of some test failures in deployment. SAM is working on getting the fixed and is expected to be available in next 2 days.

**Comment by sattigar** [comment]
CDK request : SAM spec used by the CDK is quite out of date, and we have no proposed solution for keeping it up to date automatically (see #13507)

**Comment by ashanpw** [comment]
Thanks for the info. Since the override seems to work, this is not a big issue for us :)

**Comment by sattigar** [comment]
Issue resolved and property ready to use. Closing.
