### ISSUE TITLE
Add policy template for textract:AnalyzeExpense

### ISSUE THREAD

**Issue by asunar** [aws/serverless-application-model#2274]
I wish the SAM Translator would provide a policy template for `AnalyzeExpense` command for Textract.

Currently, have to grant full access with [TextractPolicy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#textract-policy) just to call `AnalyzeExpense` which does not follow the `least privilege` guideline.

Thank you.

**Comment by c2tarun** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by ssenchenko** [comment]
transferring to discussions https://github.com/aws/serverless-application-model/discussions/3263
