### ISSUE TITLE
Unable to define Tags on Simple table

### ISSUE THREAD

**Issue by alexgurman** [aws/serverless-application-model#2280]
### Description:

Unable to define Tags on AWS::Serverless::SimpleTable table in json, getting an error "Invalid Serverless Application Specification document"

### Steps to reproduce:

1. Define Cloud Formation Template (attached) - first without tags on dynamo table, then with tags. 
2. Attempt to deploy.

### Observed result:

Getting the error

### Expected result:

Dynamo table to be created

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. If using SAM CLI, `sam --version`:
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`
![Capture-Error](https://user-images.githubusercontent.com/3374431/148587163-f9bc88d6-0849-41ef-bd25-79b133abaf2b.JPG)
[cloudformation-terraformresources.txt](https://github.com/aws/serverless-application-model/files/7830522/cloudformation-terraformresources.txt)

**Comment by chrisoverzero** [comment]
That is not how tags are structured on the resource type `AWS::Serverless::SimpleTable`. From [the documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html#sam-simpletable-tags):

> The Tags property in SAM consists of Key:Value pairs; in CloudFormation it consists of a list of Tag objects.

**Comment by mildaniel** [comment]
Thanks for submitting the issue and thanks @chrisoverzero for the response. Please comment if the issue persists.

**Comment by alexgurman** [comment]
> 

Awesome, thank you, worked!
