### ISSUE TITLE
SAM deployed output API Gateway URL is not adapted to the China region.

### ISSUE THREAD

**Issue by netcmcc** [aws/serverless-application-model#2287]
### Description:

SAM Deoloyed output API Gateway URL is not adapted to the China region.

wrong: 
https://71ekipxcbe.execute-api.cn-north-1.amazonaws.com/Prod/hello/

correct：
https://71ekipxcbe.execute-api.cn-north-1.amazonaws.com.cn/Stage/hello

### Steps to reproduce:

sam deploy --guided

### Observed result:

```
CloudFormation outputs from deployed stack
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Outputs
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Key                 HelloEfsApi
Description         API Gateway endpoint URL for Prod stage for Hello EFS function
Value               https://71ekipxcbe.execute-api.cn-north-1.amazonaws.com/Prod/hello/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Successfully created/updated stack - sam-app in cn-north-1
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.37.0
3. AWS region: cn-north-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mildaniel** [comment]
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by hawflau** [comment]
Hi @netcmcc, can you provide the template you used for us to investigate? It seems like you are using the templates provisioned by running `sam init`, but want to confirm.

**Comment by mingkun2020** [comment]
Hi @netcmcc any updates on this issue? Could you provide the template for us to investigate?

**Comment by moelasmar** [comment]
This issue is inactive with no more info provided for long time. We will close it, Feel free to open a new issue if you still have the same problem or any other problems.
