### ISSUE TITLE
Support for PartiQL in DynamoDB policy templates

### ISSUE THREAD

**Issue by adriaandejonge** [aws/serverless-application-model#2288]
### Describe your idea/feature/enhancement

AWS SAM policy templates `DynamoDBCrudPolicy`, `DynamoDBReadPolicy` and `DynamoDBWritePolicy` make it easy to assign policies to Lambda functions that interact with DynamoDB. Since November 2020, DynamoDB supports an SQL-like query language called PartiQL as an alternative way of creating/updating/reading/deleting items in a DynamoDB table. 

I wish that the AWS SAM policy templates allowed PartiQL queries without requiring additional custom policies/permissions.

### Proposal

To the policy `DynamoDBCrudPolicy`, add:
 * `dynamodb:PartiQLSelect`
 * `dynamodb:PartiQLUpdate`
 * `dynamodb:PartiQLInsert`
 * `dynamodb:PartiQLDelete`

To the policy `DynamoDBReadPolicy`, add:
 * `dynamodb:PartiQLSelect`

To the policy `DynamoDBWritePolicy`, add:
 * `dynamodb:PartiQLUpdate`
 * `dynamodb:PartiQLInsert`

Things to consider:
[X] The [SAM documentation with the policy template list](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html) will need to be updated --> See PR awsdocs/aws-sam-developer-guide#140

**Comment by mildaniel** [comment]
Thank you for your contribution! We really appreciate it. Once a PR is submitted we weigh it against our roadmap, do regression testing, make sure it’s backwards compatible and maintainable. Please watch this channel from more updates, and feel free to reach out.

**Comment by hawflau** [comment]
@adriaandejonge Thanks for raising the issue. Feel free to raise a PR for this. Contributions are welcomed!

**Comment by adriaandejonge** [comment]
> @adriaandejonge Thanks for raising the issue. Feel free to raise a PR for this. Contributions are welcomed!

Thanks @hawflau - I have already raised PR #2289 for this.

**Comment by mndeveci** [comment]
@adriaandejonge thanks for raising the PR, really appreciated!

I saw that there were some change requests made for it, would you able to address them?

**Comment by adriaandejonge** [comment]
> @adriaandejonge thanks for raising the PR, really appreciated!
> 
> I saw that there were some change requests made for it, would you able to address them?

Thanks @mndeveci Yes, I'll work on this and get back.

**Comment by hoffa** [comment]
You can use a [connector](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html) as such:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: FunctionLogicalId
    Destination:
      Id: TableLogicalId
    Permissions:
      - Read
      - Write
```

It supports PartiQL permissions, see:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L192-L232
