### ISSUE TITLE
SAM Validator Does Not Support SSM Parameter Types

### ISSUE THREAD

**Issue by CoshUS** [aws/serverless-application-model#2301]
### Description:

SSM parameter types:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types

SAM validate does not support these parameter types and will error out in the validator.
https://github.com/aws/serverless-application-model/blob/develop/samtranslator/validator/sam_schema/definitions/parameter.json

### Observed result:

```
"Template schema validation reported the following errors: Parameters.SecurityGroupSSMEntry.Type]'AWS::SSM::Parameter::Value<List<AWS::EC2::SecurityGroup::Id>>'isnotoneof['String''Number''List<Number>''CommaDelimitedList''AWS::EC2::AvailabilityZone::Name''AWS::EC2::Image::Id''AWS::EC2::Instance::Id''AWS::EC2::KeyPair::KeyName''AWS::EC2::SecurityGroup::GroupName''AWS::EC2::SecurityGroup::Id''AWS::EC2::Subnet::Id''AWS::EC2::Volume::Id''AWS::EC2::VPC::Id''AWS::Route53::HostedZone::Id''List<AWS::EC2::AvailabilityZone::Name>''List<AWS::EC2::Image::Id>''List<AWS::EC2::Instance::Id>''List<AWS::EC2::SecurityGroup::GroupName>''List<AWS::EC2::SecurityGroup::Id>''List<AWS::EC2::Subnet::Id>''List<AWS::EC2::Volume::Id>''List<AWS::EC2::VPC::Id>''List<AWS::Route53::HostedZone::Id>''List<String>']".
```

### Expected result:

SSM Parameter types should be valid.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by ljayatRabbit** [comment]
The same happened to us :(

**Comment by ljayatRabbit** [comment]
@CoshUS
I went through the docs and, correct me if I'm wrong, I think the problem lies here: https://github.com/aws/serverless-application-model/blob/develop/samtranslator/validator/sam_schema/definitions/parameter.json#L37

Could adding the new type the enum solve this problem? 
Something like:
```json
        "Type": {
          "enum": [
            "String",
            "Number",
            "List<Number>",
            "CommaDelimitedList",
            "AWS::EC2::AvailabilityZone::Name",
            "AWS::EC2::Image::Id",
            "AWS::EC2::Instance::Id",
            "AWS::EC2::KeyPair::KeyName",
            "AWS::EC2::SecurityGroup::GroupName",
            "AWS::EC2::SecurityGroup::Id",
            "AWS::EC2::Subnet::Id",
            "AWS::EC2::Volume::Id",
            "AWS::EC2::VPC::Id",
            "AWS::Route53::HostedZone::Id",
//==>   "AWS::SSM::Parameter::Value<String>",  <== //
            "List<AWS::EC2::AvailabilityZone::Name>",
            "List<AWS::EC2::Image::Id>",
            "List<AWS::EC2::Instance::Id>",
            "List<AWS::EC2::SecurityGroup::GroupName>",
            "List<AWS::EC2::SecurityGroup::Id>",
            "List<AWS::EC2::Subnet::Id>",
            "List<AWS::EC2::Volume::Id>",
            "List<AWS::EC2::VPC::Id>",
            "List<AWS::Route53::HostedZone::Id>",
            "List<String>"
          ],
          "type": "string"
        }
      },
```
If that is the case, I might have time to make a PR this same week.

**Comment by hawflau** [comment]
@ljayatRabbit feel free to raise a PR and get us to review it! In the PR! Please ensure to include tests for the change (tests for Validator is organized [here](https://github.com/aws/serverless-application-model/tree/develop/tests/validator)). Feel free to ask us if you have any question when working on the PR. Thanks!

**Comment by ljayatRabbit** [comment]
Hi @hawflau, and thanks for the insights.
I will try to setup all the dev environment, since I'm not a native python speaker :), and then I will submit the changes.
I will probably do this from my personal account.
Have a nice rest of the week.

**Comment by LautaroJayat** [comment]
@hawflau 
I have submitted a PR with a fix for this issue, and with some missing tests as well: https://github.com/aws/serverless-application-model/pull/246

Please ping me on this account if something needs to be changed and/or improved.

**Comment by LautaroJayat** [comment]
It seems the last PR #2469 was merged into `develop`.
If everything is OK I could add all the Parameters appearing in the following list: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types-supported.

I might have some time to do it this month, maybe the next week.

**Comment by aaythapa** [comment]
Looks like the issue was fixed with #2469, @LautaroJayat thank you for the PR, did you want to add anything else or should I close this issue

**Comment by LautaroJayat** [comment]
Hi @aaythapa, that PR only solves the case where you query for strings stored in the SSM Parameter Store.
I think the original issue is broader, is for when there are numbers, lists, and other things stored in there.
For me, #2469 solved my particular case, but I don't know if we can consider this issue as fully solved.

I will leave the criteria to the maintenance team

**Comment by aaythapa** [comment]
Ok, I'll leave the issue open and create a PR to add the other types

**Comment by aahung** [comment]
@aaythapa do we need any doc update to close it?

**Comment by aaythapa** [comment]
> @aaythapa do we need any doc update to close it?

Nope, we should be able to close this now
