### ISSUE TITLE
optionally use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [aws/serverless-application-model#2344]
### Description:
Could you please consider to use unittest.mock at least optionally when mock is not installed?

**Comment by jfuss** [comment]
We no longer use mock: https://github.com/aws/serverless-application-model/blob/develop/requirements/base.txt and was there when we needed to support version that didn't have `unittest.mock` in the stdlib.

This hasn't been released to pypi but we moved away from it already.

**Comment by pgajdos** [comment]
@jfuss, yeah, https://github.com/aws/serverless-application-model/commit/a308593bb8cefd3ddc644f928032fb5507635647
Not sure why I have not looked on the current state. Sorry for noise and thanks!
