### ISSUE TITLE
Add support for managed AWS transcribe policies

### ISSUE THREAD

**Issue by allanchua101** [aws/serverless-application-model#2364]
### Describe your idea/feature/enhancement

It seems that we have managed policy templates for Rekognition, Polly and Textract but we don't have one for Transcribe. It will be great to have Transcribe too on the list of available SAM policies.

### Proposal

Add a pre-built managed policy for AWS Transcribe.

**Comment by hawflau** [comment]
Thanks for suggesting the idea. We also welcome contributions! Feel free to submit a PR to add the policy template for Transcribe!

**Comment by Shiva953** [comment]
I would like to work on this, can you assign me?

**Comment by aaythapa** [comment]
Hi @Shiva953, you can open a PR with your work any time. You can use the [development guide](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md) as a starting point. Looking forward to reviewing.

**Comment by ssenchenko** [comment]
Transferring it the discussion https://github.com/aws/serverless-application-model/discussions/3263
