### ISSUE TITLE
Serverless Application Repository will not accept template that contains an AWS::Serverless::Function resource with a FunctionUrlConfig

### ISSUE THREAD

**Issue by mbklein** [aws/serverless-application-model#2421]
The SAM CLI's `build`, `package`, `validate`, and `deploy` commands  seem to support the [FunctionUrlConfig](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-functionurlconfig.html) property just fine, but when I try to submit my application to the repository (either using `sam publish` or `aws serverlessrepo create-application`, I get an error:

```
An error occurred (BadRequestException) when calling the CreateApplication operation: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [IiifFunction] is invalid. property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function
```

Since the functionality to make use of `FunctionUrlConfig` is clearly in the translator, is this just an issue of adding the right property of the right type to a schema document? I'd be happy to submit a PR for this, but I've looked through `samtranslator/validator/sam_schema` in this repo and I'm not entirely clear on where it would need to go in order to get the Serverless Repository API pick it up – if that's even how this works.

Any pointers in the right direction would be greatly appreciated.

**Comment by jfuss** [comment]
This doesn't relate to a schema at all. The Serverless Application Repository runs SAM within their service (this lib) which does the checking. They should be updated at this point. Will check them a ticket internally.

**Comment by jfuss** [comment]
@mbklein Actually no need for an example, I was able to track down. Serverless Application repository has not deployed support. Will update with information I can but we are waiting for that team to deploy the latest SAM changes to their service.

**Comment by mndeveci** [comment]
@mbklein it seems like SAR have resolved this issue, I've tried to publish an application which contains a `AWS::Serverless::Function` with `FunctionUrlConfig` and I was able to publish it.

I am resolving this issue for now, but please let us know if you are still experiencing problems with it.
