### ISSUE TITLE
Feature request: Support jsonschema 4.x

### ISSUE THREAD

**Issue by musicinmybrain** [aws/serverless-application-model#2426]
### Describe your idea/feature/enhancement

I wish the version specification for the `jsonschema` dependency allowed version 4.x; currently it is SemVer-pinned to `~=3.2`.

### Proposal

Update `requirements/base.txt`.

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details

In my testing in the downstream `python-aws-sam-translator` package for Fedora Linux, the tests still pass when using `jsonschema` 4.6.0, except:

```
=================================== FAILURES ===================================
_____________ TestValidatorApi.test_errors_13_error_definitionuri ______________

a = (<tests.validator.test_validator_api.TestValidatorApi testMethod=test_errors_13_error_definitionuri>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

/usr/lib/python3.11/site-packages/parameterized/parameterized.py:637: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/validator/test_validator_api.py:49: in test_errors
    self._test_validator_error(os.path.join(INPUT_FOLDER, template), os.path.join(OUTPUT_FOLDER, template))
tests/validator/test_validator.py:41: in _test_validator_error
    self.fail(
E   AssertionError: Expected 7 errors, found 9:
E   [Resources.ApiDefinitionUriBucketEmpty.Properties.DefinitionUri.Bucket] Must not be empty
E   [Resources.ApiDefinitionUriBucketMissing.Properties.DefinitionUri] 'Bucket' is a required property
E   [Resources.ApiDefinitionUriBucketNotIntrinsic.Properties.DefinitionUri.Bucket] {'Not': 'Intrinsic'} is not of type 'string', 'intrinsic'
E   [Resources.ApiDefinitionUriBucketNotString.Properties.DefinitionUri.Bucket] 3 is not of type 'string', 'intrinsic'
E   [Resources.ApiDefinitionUriEmpty.Properties.DefinitionUri] Must not be empty
E   [Resources.ApiDefinitionUriKeyEmpty.Properties.DefinitionUri.Key] Must not be empty
E   [Resources.ApiDefinitionUriKeyMissing.Properties.DefinitionUri] 'Key' is a required property
E   [Resources.ApiDefinitionUriKeyNotString.Properties.DefinitionUri.Key] {'Not': 'Intrinsic'} is not of type 'string', 'intrinsic'
E   [Resources.ApiDefinitionUriNotStringOrObject.Properties.DefinitionUri] 3 is not of type 'string', 'object'
```

Since the test is asserting an exact number of errors from validation, it seems at a glance that this is a matter of the test being too strict rather than a real problem.

**Comment by jfuss** [comment]
Looks like we have a PR for this already. I do have some concerns in bumping, as this can impact other tools. So we need to think this through slightly before accepting any version bumps. We have had some struggles in the past here, which is why I am calling it out.

**Comment by shaleh** [comment]
I would love to use moto (mock boto3) but I cannot because it uses this package which is forcing an older jsonschema. We use jsonschema 4.x elsewhere in the code. Totally understand this is not a quick, trivial change. But it would be welcomed.

**Comment by Wurstnase** [comment]
Did non of the both merge requests hit the requirement to merge into the main branch?
https://github.com/aws/serverless-application-model/pull/2441
https://github.com/aws/serverless-application-model/pull/2511

**Comment by ArthurVernon-TPG** [comment]
https://github.com/aws/serverless-application-model/pull/2511 addresses the concern of an unbounded jsonschema version and tests are passing. What is the blocker on having this approved so that this issue can be closed out and the moto world (that inherits this problem via moto_cloudformation) will be a better place for not tying users to an old version of jsonschema.

**Comment by threewordphrase** [comment]
Can this get merged in? This is a major-ish papercut for my team.

**Comment by bblommers** [comment]
With JSONschema unbound, is it also necessary to unpin the types-dependency? That is still stuck to 3.2:
https://github.com/aws/serverless-application-model/blob/a2c97c331e9258609185ab86df5fc2efc4a222b1/requirements/dev.txt#L37

**Comment by jordanvance** [comment]
any word on whether this will be coming out in a release soon?

**Comment by hoffa** [comment]
> any word on whether this will be coming out in a release soon?

Don't have specific dates, but we only release new versions to PyPI once they've rolled out to the SAM transform--which can take some time.

**Comment by aahung** [comment]
https://github.com/aws/serverless-application-model/releases/tag/v1.56.0
