### ISSUE TITLE
Feature request: SecretTargetAttachment support for RDS proxy?

### ISSUE THREAD

**Issue by xplsek03** [aws/serverless-application-model#2439]
Shouldn't AWS::SecretsManager::SecretTargetAttachment also have a support for RDS proxy? I am connecting to aurora-postgres cluster through it and going through real trouble passing connection details to rotation lambda function.

**Comment by mndeveci** [comment]
Can you give more details about this issue?

If this is a feature request to `AWS::SecretsManager::SecretTargetAttachment` CloudFormation resource (which is not managed by SAM), I would recommend checking with AWS Support to send this feature request to corresponding team.

Thanks!

**Comment by xplsek03** [comment]
Oh yeah, i didn't realize this is on their side. Closing.
