### ISSUE TITLE
Allow users to add 'Schedule' event source rules to a specific Event Bus

### ISSUE THREAD

**Issue by dgard1981** [aws/serverless-application-model#2449]
### Describe your idea/feature/enhancement

I wish the SAM Translator would  allow me to add a `Schedule` event source rules to a specific Event Bus. Currently they are added to the default Event Bus, which is undesirable.

### Proposal

The [`Schedule` event source](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html#sam-property-function-schedule--examples) should allow uses to specify an Event Bus in the same way as is possible with the [`EventBridgeRule` event source](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html).

For example -

```yml
Type: Schedule
Properties:
  EventBusName: my-event-bus
  Description: My scheduler
  Enabled: true
  Schedule: cron(0 3 1 * ? *)
```

Things to consider:
[✔️] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated. The description of the `EventBusName` property should be exactly the same as in in the `EventBridtRule` event source documentatoin.

 > EventBusName  
 > &nbsp;&nbsp;The event bus to associate with this rule. If you omit this property, AWS SAM uses the default event bus.
 >
 > &nbsp;&nbsp;Type: String
 >
 > &nbsp;&nbsp;Required: No
 >
 > &nbsp;&nbsp;Default: Default event bus
 >
 > AWS CloudFormation compatibility: This property is passed directly to the [EventBusName](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventbusname) property of an AWS::Events::Rule resource.

### Additional Details

While there is no technical need to add `Schedule` event source rules to a specific Event Bus, this is desirable. Essentially it makes no sense that we can create `EventBridgeRule` event source rules on a specific Event Bus, but not `Schedule` event source rules, as both are just EventBridge rules.

**Comment by qingchm** [comment]
Thanks for opening this issue! So the output event rule for a event schedule would be something like this I assume? @dgard1981 
```
    "ScheduleEvent": {
      "Type": "AWS::Events::Rule", 
      "Properties": {
        "State": "DISABLED", 
        "ScheduleExpression": "rate(1 minute)", 
        "Name": "Schedule", 
        "EventBusName": "some arn"
        "Description": "test schedule", 
        "Targets": [
          {
            "RoleArn": "role"
            "Id": "something", 
            "Arn": "arn"
          }
        ]
      }
    }
```

**Comment by dgard1981** [comment]
@qingchm, that was my original thought, but actually it looks like my request is not actionable :(

When I try to manually add a scheduled event to a custom Event Bus, a warning is displayed -
> Schedule rule is not supported when custom or partner event bus is selected.

![image](https://user-images.githubusercontent.com/43265354/180741281-d0ccf88f-c574-44ab-a4eb-9b73a66d5f74.png)

So I think that for some reason AWS do not support this, which is rather frustrating as now it means we have rules for our application on two different Event Busses - `default` and `my-event-bus`.

**Comment by qingchm** [comment]
@dgard1981 That's unfortunate to hear! Maybe there was a specific reason for you to use a different bus but seems like for now the only solution would be uniting them onto the default bus. Anyways since it's not actionable yet I will just mark this issue as closed now. Feel free to reopen any time when this feature can be realized!
