### ISSUE TITLE
Slack invitation is closed

### ISSUE THREAD

**Issue by AndrewKvalheim** [aws/serverless-application-model#2460]
The [Slack invitation](https://github.com/aws/serverless-application-model/blob/develop/README.md?plain=1#L101) is currently closed with the message:

> The email address must match one of the domains listed below. Please try another email.

> You can use any account with the domain:
>
>   - weave.works
>   - netcracker.com
>   - zimpler.com
>   - doctolib.com
>
> Don’t have an email address from one of those domains? Contact the workspace administrator at AWS Developers for an invitation.

Looks like a reoccurrence of #1875.

**Comment by jfuss** [comment]
Thanks for reaching out @AndrewKvalheim. I will need to generate another link (we currently do not have a better way :(). Going to assign this to myself but may not get back to it until the end of the week.

**Comment by peterschmidt85** [comment]
Hi @jfuss. Any update on this one? It would be great to have the link working again! 
Thank you in advance for your help!

**Comment by jfuss** [comment]
Sorry. Just taking me a while to get through some other things first. 

Does this link work? https://join.slack.com/t/awsdevelopers/shared_invite/zt-yryddays-C9fkWrmguDv0h2EEDzCqvw

**Comment by mndeveci** [comment]
This should be updated with following PR https://github.com/aws/serverless-application-model/pull/2490, resolving it.
