### ISSUE TITLE
GetMetricData Policy template

### ISSUE THREAD

**Issue by ilfoxo** [aws/serverless-application-model#2464]
Hi, 

I defined in my SAM Template some lambda function to get custom metrics information from CloudWatch. But, I haven't found in doc the right policy for reading metrics from CloudWatch. Do you know any way to do it?

Thanks in advance!

**Comment by jfuss** [comment]
@ilfoxo SAM does not provide a policy template with `getMetricData` actions. If you are wanting your Lambda access to specific Actions, you will need to construct a policy and attach it to the Role of your Lambda function.
