### ISSUE TITLE
Question: Multiple Swagger files in one API

### ISSUE THREAD

**Issue by SZubarev** [aws/serverless-application-model#2505]
Is it possible to deploy one API using multiple Swagger files where each file specified subset of resources?

**Comment by sriram-mv** [comment]
Can you describe what you are trying to do? by subset of resources, do you mean API paths?

**Comment by hoffa** [comment]
Closing due to missing information. You can [start a new discussion](https://github.com/aws/serverless-application-model/discussions) if you still have questions.
