### ISSUE TITLE
Feature request: New feature to convert SAM template to CloudFormation (CFn) template using sam cli.

### ISSUE THREAD

**Issue by beansandroasters** [aws/serverless-application-model#2556]
### Describe your idea/feature/enhancement

 I wish SAM cli has a feature to convert sam template to CFn template.
 
The way to define resources with SAM is really useful and reduces the burden to write compared to CFn.
However, SAM is not available with some services such as CFn StackSets.

To use those services, we need to convert SAM template to CFn template. 
In my understanding, the only way to achieve that is actually deploy SAM template and check the CFn console.

### Proposal

Deploying SAM template is meaningless just to get converted template.
I know you guys  provide the script in this repository to achieve what I want, but that would be better if
the implementation gets included in SAM cli, which makes it easier to handle.

Thank you

**Comment by hoffa** [comment]
One way to transform a template without full deployment is by creating a change set (but not executing it).

For example saving something like this (as a rough idea; not prod-ready) as `transform.py`:

```python
import json
import sys
import uuid

import boto3


def transform(template: str) -> str:
    cfn = boto3.client("cloudformation")
    name = f"transform-{uuid.uuid4()}"
    change_set = cfn.create_change_set(
        TemplateBody=template,
        StackName=name,
        ChangeSetName=name,
        ChangeSetType="CREATE",
        Capabilities=[
            "CAPABILITY_IAM",
            "CAPABILITY_AUTO_EXPAND",
        ],
    )
    change_set_id = change_set["Id"]
    waiter = cfn.get_waiter("change_set_create_complete")
    waiter.wait(
        ChangeSetName=change_set_id,
        WaiterConfig={
            "Delay": 5,
        },
    )
    transformed = cfn.get_template(ChangeSetName=change_set_id)
    cfn.delete_stack(StackName=name)
    return json.dumps(transformed["TemplateBody"])


def main():
    print(transform(sys.stdin.read()))


if __name__ == "__main__":
    main()
```

You can then get the transformed template with:

```bash
python transform.py < sam-template.yaml > cfn-template.json
```

It's not a perfect but could be an alternative.

In SAM CLI you can use `sam validate --debug` which will display the transformed template (with the caveat that it's not always 100% accurate as it needs to account for local paths and other functionality it supports).

**Comment by hoffa** [comment]
I hope that helps at least somewhat. I'll close this in favor of the existing https://github.com/aws/aws-sam-cli/issues/1141 feature request.
