### ISSUE TITLE
(stepfunctions): the service does not support JSON paths for MaxConcurrency on a Map state in SAM definition state machine asl.json file

### ISSUE THREAD

**Issue by natamo** [aws/serverless-application-model#2572]
### Description:

JSON paths are not actually supported for the MaxConcurrency key in a Map state by Step Functions, and using SAM return an error 

### Steps to reproduce:
In the file step_functions.asl.json for the state machine definition in the Map state in the parameter MaxConcurrency:

"MaxConcurrency": "$.max_concurrency", 

### Observed result:
when i execute sam build , there is no exceptions, but when i deploy it i caught this exception :

sam deploy

<img width="1439" alt="Captura de Pantalla 2022-10-31 a la(s) 14 18 42" src="https://user-images.githubusercontent.com/33498584/199102778-cf06a953-8b40-4bed-bba8-24496f97842f.png">

### Expected result:
I need to define in the step_functions.asl.json file  like: 

"MaxConcurrency": "$.max_concurrency", 

so can i change it for dynamic behaviour 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.55.0
3. AWS region: us-west-2

**Comment by natamo** [comment]
#20152

**Comment by natamo** [comment]
[In cdk there is a workarround](https://github.com/aws/aws-cdk/issues/20835)

**Comment by ssenchenko** [comment]
Step Functions support only integer for this property. SAM Transform doesn't touch `step_functions.asl.json` or anything in a Step Function definition. CDK is different because they actually provide as TS (or any other language) wrapper around step function definition. That's why they can create a workaround.

**Comment by ssenchenko** [comment]
We are not planning to process Step Function ASL soon.

**Comment by ssenchenko** [comment]
By the way, have you tried to use `DefinitionSubstitutions` in `AWS::Serverless::StateMachine` for your use case? Would it help?
