### ISSUE TITLE
Bug: Source directory bin/ is installed into site-packages

### ISSUE THREAD

**Issue by musicinmybrain** [aws/serverless-application-model#2588]
### Description:

Since 1.54.0, the source directory `bin/` is installed into `site-packages`.

### Steps to reproduce:

```
$ python3 -m venv _e
$ . _e/bin/activate
(_e) $ pip install aws-sam-translator==1.54.0
(_e) $ ls -1 _e/lib/python*/site-packages/bin/
```

### Observed result:

```
add_transform_test.py
_file_formatter.py
__init__.py
json-format.py
__pycache__
sam-translate.py
yaml-format.py
```

### Expected result:

```
ls: cannot access '_e/lib/python3.10/site-packages/bin/': No such file or directory
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Fedora Linux 36 x86_64; but the issue is platform-independent
2. If using SAM CLI, `sam --version`: N/A
3. AWS region: N/A

**Comment by aahung** [comment]
@musicinmybrain thanks for reporting that, the PR to remove it is on the way!
