### ISSUE TITLE
Refactoring: pass-through props

### ISSUE THREAD

**Issue by ssenchenko** [aws/serverless-application-model#2590]
@hoffa [suggested](https://github.com/aws/serverless-application-model/pull/2583#discussion_r1018232898)
> for pass-through properties, we should really have a super-low-effort "any type" that doesn't require us to sprinkle `dict`/`Dict`/etc. in the code
For example in [`push.py`](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py) we have a class with a bunch of properties which are just passed through to an underlying resource types which are created in the process
```
class SNS(PushEventSource):
    """SNS topic event source for SAM Functions."""
    resource_type = "SNS"
    principal = "sns.amazonaws.com"
    property_types = {
        "Topic": PropertyType(True, is_str()),
        "Region": PropertyType(False, is_str()),
        "FilterPolicy": PropertyType(False, dict_of(is_str(), list_of(one_of(is_str(), is_type(dict))))),
        "SqsSubscription": PropertyType(False, one_of(is_type(bool), is_type(dict))),
        "RedrivePolicy": PropertyType(False, is_type(dict))
```

Either `any` like suggested above or maybe use smth like `PropertyOf(typeName, propertyName)` which will make it clear that it's a pass-through property.

**Comment by hoffa** [comment]
We have `Property` now that has strict typing (but the type can be `Any`), and it's easy to specify a pass-through property:

```python
"Foo": Property(False, any_type())
```

See e.g. https://github.com/aws/serverless-application-model/pull/2492/files
