### ISSUE TITLE
AWS::Serverless::Function CodeUri with Ref not working properly

### ISSUE THREAD

**Issue by jikuja** [aws/serverless-application-model#271]
I have following set of parameters:
```json
   "Parameters" : {
      "DeployBucket" : {
         "Type" : "String",
         "Default": "a"
      },
      "DeployKey" : {
         "Type" : "String",
         "Default" : "b"
      },
      "DeployString": {
         "Type" : "String",
         "Default" : "s3://<some-bucket>/<somefile>"
      }
   }
```

in my template for testing.

# hardcoded S3 URI inside CodeUri works

If I use `"CodeUri" : "s3://<my-bucket>/<my-file>",` with `AWS::Serverless::Function` resource I run `aws deploy` properly.

# usage of key and bucket properties also works

Even using following
```json
"CodeUri" : {
               "Key": {"Ref": "DeployKey"},
               "Bucket": {"Ref": "DeployBucket"}
            }
```
and running `aws deploy -parameter-overrides DeployBucket=<bucket-name> DeployKey=<file-name>` works properly

# using Ref to fetch string value does not work

As soon as I use 
```json
"CodeUri" : {"Ref": "DeployString"}
```

changeset creation fails with message:

    FAILED - Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless 
    Application Specification document. Number of errors found: 1. Resource with
    id [xxx] is invalid. 'CodeUri' requires Bucket and Key properties to be specified`

In this case I use `aws deploy` command without passing any parameters => stack creation should have used hardcoded parameter value from `Parameters` section.

[Documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) states that usage of String or S3 location object is supported with CodeUri property. In this case it seems like Ref function can not be used to fetch string data for CodeUri property.

**Comment by sanathkr** [comment]
Yes! This is how it is supposed to work. You cannot directly !Ref the string. Instead you should use the {Bucket, Key} notation - https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#using-intrinsic-functions

SAM needs to parse CodeUri string into bucket/key, but unfortunately it cannot resolve runtime parameter values passed through !Ref.

**Comment by jikuja** [comment]
> You cannot directly !Ref the string. Instead you should use the {Bucket, Key} notation

Well. Worth of mention on documentation.

**Comment by zoltanhomoki** [comment]
Are there any plans to support this feature? It would be great to use the same Cloud Formation file both locally and when we deploy and passing the CodeUri as a CF parameter (locally the local folder/zip and the s3 bucket during deployment)

**Comment by msolimans** [comment]
@zoltanhomoki as a workaround, set CodeUri as `local path` and when you want to deploy, s3 bucket deploymemt,  use `sam package`

**Comment by monkut** [comment]
This is confusing since the documentation says you can use `local file path`:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codeuri
```
CodeUri
The Amazon S3 URI, local file path, or FunctionCode object of the function code.

If an Amazon S3 URI or FunctionCode object is provided, the Amazon S3 object referenced must be a valid Lambda deployment package.

If a local file path is provided, the template must go through the workflow that includes the sam deploy or sam package command, in order for the code to be transformed properly.
```

_was using `aws cloudformation create-stack` command, will try with `sam deploy`_

**Comment by adamarla** [comment]
When it comes to layers, while using sam-local one can do
```
ContentUri: !Ref LayerRequestsUri.
```
But when using sam package + sam deploy, it has to be in the format
```
ContentUri:
  Bucket: !Ref LayerBucket
  Key: !Ref LayerRequestsPath
```
With a common format (either of the above) at least one won't have to hack the deployment process to accommodate both.

**Comment by lestephane** [comment]
I was tripped up by this too. Whatever you think you did that warrants closing this issue, I can't see it.
The doc does not mention anything about this limitation.

**Comment by hoffa** [comment]
Try adding `AWS::LanguageExtensions` to the `Transform`s as such:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

Haven't tested this specific use case, but `AWS::LanguageExtensions` resolves intrinsic functions out of the box (only ones that can be known before deployment). See https://github.com/aws/serverless-application-model/issues/2533.

**Comment by hoffa** [comment]
https://github.com/aws/serverless-application-model/issues/778
