### ISSUE TITLE
Feature request: AutoPublishAlias limit generated versions 

### ISSUE THREAD

**Issue by awsdiegorad** [aws/serverless-application-model#2719]
Currently, when AutoPublishAlias is enabled on the Serverless::Function resource, SAM will create a new Lambda Alias and Lambda Version resource [1], the lambda version resource generated by this will have its deletion policy set to "Retain" by default. 

On each update to the lambda function the previous function version is disassociated from the stack, but not deleted due to the deletion policy, after many updates this results in a large amount of lambda versions being stored, eating into the Code Storage service limit of 75 GB [2]. 

Currently, the best ways to manage function versions this is to either not use AutoPublishAlias, or to manually delete old unwanted versions. 

I request that a new property get added to the Serverless::Function resource that will compliment the AutoPublishAlias property. This new property will set the desired amount of existing lambda versions generated by AutoPublishAlias. 

For example, when the value for this property is set to 5, then after 5 function versions are created by AutoPublishAlias, when a new one is created the oldest version is deleted. 

Resources:
[1] https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-function.html#sam-specification-generated-resources-function-autopublishalias
[2] https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

**Comment by ssenchenko** [comment]
I confirm what @jfuss said. SAM doesn't track deployments and created versions. CloudFormation doesn't provide any tools to delete versions after a number of deployments either

**Comment by carpnick** [comment]
This feels like an incorrect answer - what is the reasoning for setting version retain?  Why can't we set something to not do this by default.

**Comment by rahuldeverani** [comment]
Can we have a way to set the deletion policy as Delete instead of Retain (which SAM is generating for Lambda version resource when AutoPublishAlias is specified) ?
