### ISSUE TITLE
Path to using upstream py27hash as a dependency?

### ISSUE THREAD

**Issue by musicinmybrain** [aws/serverless-application-model#2815]
The [bundled copy](https://github.com/aws/serverless-application-model/tree/c61b6802dfcc00ea0bd132602ceca706901bcb4a/samtranslator/third_party/py27hash) of https://github.com/neuml/py27hash/ is quite close to upstream. It has some “ignore” type annotations added, some if statements were reordered (apparently to put this library’s common case first for performance), and an LRU cache layer was added.

Is there a path to adding `py27hash` as an external dependency rather than keeping it as a bundled and slightly forked copy? I was even doing this downstream in the [Fedora Linux `python-aws-sam-translator` package](https://src.fedoraproject.org/rpms/python-aws-sam-translator) until the LRU cache change.

It seems like it should still be possible to add a dependency on `py27hash >= 1.0.2` (for 32-bit fixes), drop `samtranslator.third_party.py27hash`, and add the LRU cache etc. via a wrapper. After all, the calls to this code are all through the [`samtranslator.utils.py27hash_fix` wrapper](https://github.com/aws/serverless-application-model/blob/c61b6802dfcc00ea0bd132602ceca706901bcb4a/samtranslator/utils/py27hash_fix.py) anyway.

What do you think? Is this something you would be interested in? Would you consider a PR that attempted it?

(I am required to make this request under Fedora’s [guidelines for bundled dependencies](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling).)

**Comment by hoffa** [comment]
I appreciate this is to comply with Fedora packaging guidelines. Unfortunately due to how the SAM transform is consumed this would be a little tricky, so unless there's customer impact, it's not something we're looking to change at this time.

**Comment by musicinmybrain** [comment]
> I appreciate this is to comply with Fedora packaging guidelines. Unfortunately due to how the SAM transform is consumed this would be a little tricky, so unless there's customer impact, it's not something we're looking to change at this time.

Understandable. Thank you for following up.
