### ISSUE TITLE
SESBulkTemplatedCrudPolicy lacks template permission

### ISSUE THREAD

**Issue by sukrit007** [aws/serverless-application-model#2844]
### Description

The SES Policy templates SESBulkTemplatedCrudPolicy lacks resource for template ARN when performing ses:SendTemplatedEmail .  

https://github.com/aws/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L1890

### Steps to reproduce
Use the SESBulkTemplatedCrudPolicy and specify verified Identity as parameter.

### Observed result
Lambda fails to send email,  as it lacks ses:SendTemplatedEmail on template. 

After manually modifying the policy and also adding ARN for template,  it works

### Expected result

We need to add TemplateName as parameter to  SESBulkTemplatedCrudPolicy

### Additional environment details

1. OS:  Mac 12.6.2
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: 1.67.0
3. AWS region: us-east-2

**Comment by awood45** [comment]
We'll probably need to make a new policy template for this, because unfortunately while we would need to add this to get the resource constraint applied, it would break any templates that have this and have applied a workaround. Looking in to adding a policy template for this.

**Comment by berger501** [comment]
Hello,
  i discovered this issue because we are using sam with SESBulkTemplatedCrudPolicy and we received a SES Security notification because of that i'm assuming that the policy created by sam will not be sufficient to send emails after 4th of april because no resource for the template is created. If i understand it correctly, this issue should fix this?

**Comment by acristin** [comment]
Hi, I'm not familiar with the specific campaign from SES, but we expect that the new policy template will suffice. This will be one of the acceptance criteria for the change.
