### ISSUE TITLE
ModuleNotFoundError: No module named 'samtranslator'

### ISSUE THREAD

**Issue by kelly1266** [aws/serverless-application-model#2873]
### Description
Hi, I run an [AWS shell script](https://docs.aws.amazon.com/vsts/latest/userguide/awsshell.html) as part of a build pipeline for my project. The build pipeline hasn't been changed for a few weeks and just started failing a few hours ago with a module not found error. I was hoping that someone could help me figure out why 'samtranslator' would suddenly be missing? I don't know this repo or python very well, could it possibly be because [this PR](https://github.com/aws/serverless-application-model/commit/278594f4f0201e7073d810b0f3987ec3bde70c76#diff-374723333b8c5a2946cf581f3c1be7906cbd3a35c61907113ccb6f57c39af1a7) removed the path insert?

### Steps to reproduce
Run the following bash commands:
```
git clone https://github.com/aws/serverless-application-model.git
pip install -r serverless-application-model/requirements/base.txt
pip install pyyaml
pip install cfn-flip
python serverless-application-model/bin/sam-translate.py --template-file=packaged.yaml --output-template=cft.json
```

### Observed result
```
File "/path/serverless-application-model/bin/sam-translate.py", line 18, in <module>
    from samtranslator.model.exceptions import InvalidDocumentException
ModuleNotFoundError: No module named 'samtranslator'
```

### Expected result
Expect the module to be found

### Additional environment details
AWS region: eu-west-1

**Comment by aahung** [comment]
thanks for reporting, the removal of the following code should be the cause. We are working on bring it back.

```py
_path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, my_path + "/..")
```

**Comment by hoffa** [comment]
We've added the script parent directory back to `sys.path` in https://github.com/aws/serverless-application-model/pull/2875; should work now.

**Comment by kelly1266** [comment]
Awesome, its working again. Thanks for the quick response!
