### ISSUE TITLE
AddDefaultAuthorizerToCorsPreflight should default to False

### ISSUE THREAD

**Issue by Univac1107** [aws/serverless-application-model#3054]
As stated in: [https://fetch.spec.whatwg.org/#cors-protocol-and-credentials](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials), _a CORS-preflight request never includes credentials._

So, what is the point of attaching the Authenticator to OPTIONS methods by default?
This causes a lot of problems when using SAM. It should default to False.

**Comment by GavinZZ** [comment]
Hi there, thanks for opening an issue. I understand your concern, however, it would be a backward incompatible change to change the default value for `AddDefaultAuthorizerToCorsPreflight`. I'll add this suggestion to a list of breaking changes that we keep track of internally.
