### ISSUE TITLE
DynamoDB Streams is converting Numeric values to Strings

### ISSUE THREAD

**Issue by AkshatNGupta** [aws/serverless-application-model#3123]
Hello Hiveminds, 

I was basically developing a sample application using AWS SAM where i wanted to test out event source mapping, batch size, and batch window type of features. 

What i created are:
1. Employee table -> To store employee id, name, department, age, salary and has a stream type of NEW_AND_OLD_IMAGE, with PrimaryKey as "EmpId" and SortKey as "Department"
2. Post & Put & Get & Delete Employee Lambda -> which are meant to do their basic job to store, update, fetch and delete the employee from Employee table.
3. DepartmentManagementLambda ->It has batch size of 3 and batch window of 60 seconds, It will calculate the MaxSalary, MinSalary, AverageSalary, NumEmployees and TotalSalary into the Department Table, it does not have any event source mapping / event filtering attached to its configuration.
4. DepartmentTable -> It stores  MaxSalary, MinSalary, AverageSalary, NumEmployees and TotalSalary, with PrimaryKey as Department with no SortKey.
5. Tax Management Lambda -> this lambda will get the employee id, salary and department and calculate the tax and save it to the tax table,  but has `FilterCriteria` with `Filters` and the pattern is as follows
```
- Pattern: '{ "dynamodb" : { "NewImage" : { "Salary" : { "N" : [ { "numeric" : [ ">", 50000 ] } ] } } } }'
```
6. Tax Table -> which has which will basically store the employee id, department and the tax and PrimaryKey is EmpId and SortKey is Department.

Problem Description - 
When i create an Employee, it successfully gets created into Employee table, which in turn runs the stream lambda for Department based on the batch sizes/window, basically it does its job since there are no filters attached to it.
The main problem i am facing is, 
The lambda for tax management which has filter event which checks for only if Salary is greater than 50000 then only trigger the lambda, this filter operation is failing because the Stream event which is sent by the Employee table, has converted the Salary which was previously as Numeric value into a String, the event source mapping is not able to apply the filter pattern as it expects a numeric value but is returned a stream with numeric values converted to string. 
You can see the below item log, i.e the stream event received by DepartmentManagement lambda, this shows the stream is sending Numerics as Strings, that is why tax management lambda is never triggered as the filter pattern is not satisfied. 😭
```
"dynamodb": {
                "ApproximateCreationDateTime": 1682273382,
                "Keys": {
                    "Department": {
                        "S": "Marketing"
                    },
                    "EmpId": {
                        "N": "6789"
                    }
                },
                "OldImage": {
                    "Salary": {
                        "N": "11000"  //-> This is coming as string from the stream processor
                    },
                    "Department": {
                        "S": "Marketing"
                    },
                    "EmpId": {
                        "N": "6789"
                    },
                    "Age": {
                        "N": "27"
                    },
                    "Name": {
                        "S": "Olivia Kim"
                    }
                },
                "SequenceNumber": "800000000026927133508",
                "SizeBytes": 82,
                "StreamViewType": "NEW_AND_OLD_IMAGES"
            },
```
How to fix this issue? Can Someone help?
Note: The code is deployed using SAM and Lambdas are written in Node.

**Comment by ssenchenko** [comment]
Hi @AkshatNGupta 
I'm sorry to hear about the problems you're facing. It's always annoying. However, I think that SAM translator (SAM-T) doesn't have anything to do with it. SAM-T transforms `Serverless` resource macros like `SimpleTable`, `Function` to their CloudFormation basic abstractions like `DynamoDb::Table and `Lambda::Function` respectively. 
Seems like an answer to your problem might be in DynamoDb streams documentation.

**Comment by gokhantuna** [comment]
@AkshatNGupta ,
Many weeks have passed; but I'd like to add a note for the ones arriving here via google:

Acccording to the documentation [here ](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-ddb), unfortunately and regrettably streams for DynamoDB does not support it. 

from the doc:

> DynamoDB event filtering doesn’t support the use of numeric operators (numeric equals and numeric range). Even if items in your table are stored as numbers, these parameters are converted to strings in the JSON record object.
