### ISSUE TITLE
Failed to create/update the stack. Run the following command to fetch the list of events leading up to the failure

### ISSUE THREAD

**Issue by sakigo9** [aws/serverless-application-model#3201]
### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region:

**Comment by SimonCMoore** [comment]
@sakigo9 There is insufficient information for us to investigate, if you are able to provide more details please reopen (if you using a tool to submit the issue perhaps there is also an issue in that).
Thanks
Simon
