### ISSUE TITLE
Import failure with pydantic 1.10.12

### ISSUE THREAD

**Issue by hajapy** [aws/serverless-application-model#3275]
### Description

When importing 
```
samtranslator.internal.schema_source.common
```
in an environment with pydantic 1.10.12, this error occurs:
```
❯ python
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydantic
>>> print(pydantic.__version__)
1.10.12
>>> from samtranslator.internal.schema_source.common import PassThroughProp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aachkar/mambaforge/envs/samtest/lib/python3.11/site-packages/samtranslator/internal/schema_source/common.py", line 19, in <module>
    class PassThroughProp(pydantic.BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)
```

Downgrading pydantic to 1.10.11 resolves the issue.

### Steps to reproduce

1. Create environment:
```
mamba create -n samtest aws-sam-translator==1.71.0
mamba activate samtest
```

2. Then run:
```
python -c "from samtranslator.internal.schema_source.common import PassThroughProp"
```
3. Observe traceback
4. Downgrade pydantic
```
mamba install pydantic==1.10.11
```
5. Repeat command in step 2, and observe problem is eliminated. 

This was noticed in the CI builds for cfn-lint in conda forge here: https://github.com/conda-forge/cfn-lint-feedstock/pull/172#issuecomment-1652661786

### Observed result

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aachkar/mambaforge/envs/samtest/lib/python3.11/site-packages/samtranslator/internal/schema_source/common.py", line 19, in <module>
    class PassThroughProp(pydantic.BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)
```

### Expected result

Exit without error

### Additional environment details

1. OS:
3. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
6. AWS region:

**Comment by hoffa** [comment]
I'm curious, how did you encounter this issue? Code under the `internal` module is [considered internal](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines) and should not be relied upon publicly.

**Comment by hajapy** [comment]
This was mostly likely a conda-forge specific issue with its build of pydantic (https://github.com/conda-forge/pydantic-feedstock/pull/98).

The issue is resolved now.
