### ISSUE TITLE
Splitting openapi files for a single api gateway

### ISSUE THREAD

**Issue by tirumerla** [aws/serverless-application-model#3318]
Opening a new issue to continue discussion with respect to #2058 

Hello @jfuss I'm currently running into the issue of openapi template being too large reaching limit of ~1MB. We have many paths specified in single openapi yaml including some mapping templates. We moved all the functions to nested stacks still we feel this is not viable plan to scale having a single api gateway. Is there any way to split single openapi yaml file into multiple openapi yaml file with single api gateway or do we have to create multiple api gateways to make it work. I know we can split into multiple openapi yaml files and use sam bundle to combine everything into single template but that would run into these limitations too. Wondering if you have any insights or tips on how to make this work with single api gateway and splitting multiple openapi yaml files.

**Comment by GavinZZ** [comment]
Hi @tirumerla, thanks for opening an issue. Unfortunately this would not be possible currently. You would have to create multiple api gateways to achieve it.

**Comment by GavinZZ** [comment]
Closing this issue as the workaround is to split into multiple API Gateways unfortunately. And we do not have plan to support splitting swagger file.

**Comment by tirumerla** [comment]
Thank you @GavinZZ for confirming

**Comment by Louis-Westar** [comment]
Hi @tirumerla ,
I'm facing the same issue as you.
Could you share your experience about how you split your openapi spec files into multiple API Gateways templates ?
Currently, I can split specs into multiple API gateways templates , but I also used custom domain name in API Gateways, I am a little confused on setting custom domain name to mapping those API Gateways. 
Looks like it can only set different sub paths to map those API Gateways.
I will appreciate your help with this situation.

**Comment by tirumerla** [comment]
Apologies for my delay in response @Louis-Westar 
> Could you share your experience about how you split your openapi spec files into multiple API Gateways templates ? 

We are using multiple custom domains to map to api gateways that we create. We split a single api gateway ( with one openapi yaml file ) into multiple api gateways ( with multiple openapi yamls one per component, that made sense to our usecase ).

We mapped one custom domain to each api gateway <- this made sense since this was mainly for internal api's and we updated these domains in our UI.

We created custom domains initially and mapped those domains using basepathmapping referencing the api gateway we want to map in cloudformation.
 


> I am a little confused on setting custom domain name to mapping those API Gateways. Looks like it can only set different sub paths to map those API Gateways. I will appreciate your help with this situation.

Is your goal to have same subpaths and hitting different endpoints? You could technically use same subpaths for different custom domains but you just have to map it accordingly on your client api or sdk.

```
abc.xyz.com ( custom domain ) -> /v1 -> prod stage for example (hits any endpoint paths by mapping abc.xyz.com/v1 on your client side)
def.xyz.com (custom domain ) -> /v2 ( base path ) -> prod stage ( hits any endpoint paths by mapping def.xyz.com/v2 on your client side )
abc.xyz.com ( custom domain ) -> /v2 -> prod -> hits when path is abc.xyz.com/v2
def.xyz.com ( custom domain ) -> /v1 -> prod  -> hits when path is def.xyz.com/v1
```

Hope this helps
