### ISSUE TITLE
Update SAM Schema to support `FunctionResponseTypes` for Lambda SQS event sources

### ISSUE THREAD

**Issue by andy2mrqz** [aws/serverless-application-model#3322]
## Summary
In October, 2022 there was [an issue](2256) to update the SAM documentation to
recognize `FunctionResponseTypes` as a valid option for Lambda SQS event sources.

While that is now live in the documentation, the current schema.json file does not list it as a valid attribute.  This results in the editor displaying an error when using this property in an SQS Event for Lambda.

## Request:

Please update the schema so the editor can properly check SQS event properties.

## Screenshots:
![image](https://github.com/aws/serverless-application-model/assets/17534437/affcc9d2-fa17-46d2-8ba3-7a97a0baecf0)
^ the error in the template.yaml file
![image](https://github.com/aws/serverless-application-model/assets/17534437/05ce430e-ac8d-4711-b9be-4c40827583f6)
^ the SQSEventProperties schema, missing `FunctionResponseTypes`

**Comment by GavinZZ** [comment]
Hi @andy2mrqz, thanks for raising an issue. I'll investigate it. Meanwhile we also welcome and appreciate any contribution.

**Comment by andy2mrqz** [comment]
> Hi @andy2mrqz, thanks for raising an issue. I'll investigate it. Meanwhile we also welcome and appreciate any contribution.

Thanks @GavinZZ.  I added a PR to address this - attempted to follow the development guidelines (mentioned in the PR).

Hope that helps!

**Comment by GavinZZ** [comment]
Thanks @andy2mrqz, the PR has been merged. Please give it 2~3 weeks for the changes to roll out. Closing this issue/
