### ISSUE TITLE
AWS Parameter Store and Secrets Manager Layer with AWS Signer

### ISSUE THREAD

**Issue by darkcl0ud** [aws/serverless-application-model#3354]
Hello,

I am currently integrating the [new(ish) Lambda Layer](https://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/) for securely caching secrets from Secrets Manager and Parameter Store in the Lambda Execution Environment. It has really helped our company to reduce API calls made to Secrets Manager, however the issue I have comes to [Lambda Signing](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codesigningconfigarn). 

## Error Message & Cause
You __CAN'T SIGN__ a Lambda Function if a Layer being used does not belong to you because you can't verify its authenticity ([AWS Secrets Caching Layer](https://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/)). The issue I am getting is listed below along with the commands to recreate it using the contents in [examples.zip](https://github.com/aws/serverless-application-model/files/12731632/examples.zip):

*Note: To run the recreation commands you need to add a AWS Signer Profile Version ARN into the stack parameters. Here is a quick command to obtain one.*
 - ```
   SIGNATURE_ARN=$(aws signer put-signing-profile --platform-id "AWSLambda-SHA384-ECDSA" --profile-name test --signature-validity-period '{"value" : 3, "type" : "MONTHS"}' --region eu-west-2 | jq '.profileVersionArn')```
```
sam build --template-file layer-signed-failed.yml
sam deploy --capabilities CAPABILITY_NAMED_IAM --region eu-west-2 --guided

...
...
...

CREATE_FAILED                          AWS::Lambda::Function                  GetSecret                              Resource handler returned message:   
                                                                                                                     "Lambda cannot deploy the function.  
                                                                                                                     The function or layer might be       
                                                                                                                     signed using a signature that the    
                                                                                                                     client is not configured to accept.  
                                                                                                                     Check the provided signature for     
                                                                                                                     arn:aws:lambda:eu-                   
                                                                                                                     west-2:133256977650:layer:AWS-       
                                                                                                                     Parameters-and-Secrets-Lambda-       
                                                                                                                     Extension:10." (RequestToken: f3cd7f 
                                                                                                                     18-6c69-feed-5f0d-d095486a3932,      
                                                                                                                     HandlerErrorCode: InvalidRequest)    
ROLLBACK_IN_PROGRESS                   AWS::CloudFormation::Stack             sam-app                                The following resource(s) failed to  
                                                                                                                     create: [GetSecret]. Rollback        
                                                                                                                     requested by user.         
```

## Workarounds
At the moment the only fixes I have are:
- Not signing the function
- Signing but not [enforcing](https://aws.amazon.com/blogs/aws/new-code-signing-a-trust-and-integrity-control-for-aws-lambda/)
- Signing it without the layer and using the `boto3` libraries which mean making an API call for every Lambda invocation to retrieve secrets (which is not ideal). 

*Note: Examples for all of the above are also in [examples.zip](https://github.com/aws/serverless-application-model/files/12731632/examples.zip).*

Commands to recreate are:
- To deploy with the layer but without signing the Lambda function:
  ```
  sam build --template-file layer-unsigned-working.yml
  sam deploy --capabilities CAPABILITY_NAMED_IAM --region eu-west-2 --guided
  ```
- To deploy without the layer but signing the Lambda function:
  ```
  sam build --template-file sdk-signed-workingyml
  sam deploy --capabilities CAPABILITY_NAMED_IAM --region eu-west-2 --guided
  ```

I am not sure if there is a possible solution for this issue I have searched online and there was nothing I could find I understand it is quite specific. 

The other possible option I mentioned is changing `AWS::Lambda::CodeSigningConfig` to have `UntrustedArtifactOnDeployment` set to `Warn` in `layer-signed-failed.yml` (technically better than `layer-unsigned-working.yml`). However this wont let us enforce code signing and will allow you to change the main code without signing it.

For example if you change the value to `Warn` you will then be able to upload a .zip file unsigned to replace the lambda code. Compared to `Enforce` which provides back this message:
```
Lambda cannot deploy the function. The function or layer might be signed using a signature that the client is not configured to accept. Check the provided signature for arn:aws:lambda:eu-west-2:xxxxxxxxxxxx:function:sam-app-get-secret.
```

**Comment by GavinZZ** [comment]
Hi thanks for opening an issue with us. I took a deep dive into this issue and followed the guide mentioned in [this link](https://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/). I can confirm that I'm encountering the same issue. 

However, SAM treat [`CodeSigningConfigArn`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codesigningconfigarn) as a pass-through property, meaning that we do not do any extra handling and directly pass this property to the lambda function. There is, unfortunately, not much we can do on SAM Transform side to help with this issue. I would recommend reaching out to the CloudFormation team.

**Comment by darkcl0ud** [comment]
Hi @GavinZZ, thanks for the reply. Yeah it makes sense it wouldn't be a SAM issue. I will get in touch with the CloudFormation team and go from there however I believe this will be more of a Lambda issue specifically as the issue is not linked to just CloudFormation, but instead seems to be Lambda actually denying the request because of the way it's set up to work when it comes to signing.
