### ISSUE TITLE
sam deploy drops (removes) cognito authorizer "security" scopes section for endpoints

### ISSUE THREAD

**Issue by bmckinle** [aws/serverless-application-model#3356]
The _**security**_ section in our openapi_bundled.yaml in our pipeline is present at the time sam deploy occurs. After sam deploy runs successfully, the security section in the exported api gateway yaml (stage) does not contain the security section, yet all other api sections are present and correct.  The functionality of the API is correct, except that no API bearer token is checked for at runtime and the API is insecure.  

**Why is sam deploy dropping the security section from the included openapi_bundled.yaml?**  

Originally, we included the Domain section in the api gateway (template.yaml) resource but decided to factor it out into a BasePathMapping resource to allow for multiple APIs with different base paths to share a single account api subdomain (e.g., api.company.com/api1, api.company.com/api2, etc.).  Cognito security was working as expected before the refactoring (expected 403 and got it on negative tests). After the refactoring, the authorization stopped working (expecting 403 but no security checking done and calls succeed, breaking security).  The original Domain section-based code had been working across redeploys for about three years.   We have no clue why the security section is being dropped during sam deploy but it is provably doing just that.  See the api gw console where we expect a cognito authorizer to be present on the method request but it is None.

# openapi.yaml 

These excerpts include a recurring sample in many supporting module endpoint sets.  Shown is one module endpoint (GET) to provide enough context to demonstrate the problem.  The SAM template.yaml includes openapi_bundled.yaml, which contains all $refs replaced with all endpoint modules.  This is required by AWS::Serverless::Api.  The large include is required due to the size of the API, which exceeds AWS limits.  the s3 bucket openapi_bundled.yaml has been confirmed to contain the security section just before sam deploy occurs.
```
...
paths:
...
  /accounts:
    $ref: './accounts.yaml'.  # inlined  via openapi bundler (one file required by cloudformation include).
```
# ./accounts.yaml
...
```
get:
  tags:
    - accounts
  summary: Find accounts
  parameters.
  operationId: findAccounts
  parameters:
    - in: query
      name: filter
      required: false
      schema:
        $ref: './schemas/Account.yaml#/AccountQueryParameters'
      style: form
      explode: true
    - $ref: './schemas/Headers.yaml#/SlaterUserParam'
    - $ref: './schemas/Headers.yaml#/DbVersionParam'
  responses:
    '200':
      description: successful operation
      headers: # CORS responses required for interactive API
        Content-Type:
          schema:
            type: string
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: './schemas/Account.yaml#/MetadataPaginatedAccounts'
    '400':
      description: Bad Request
    '401':
        description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not found
    '500':
      description: Server error.  Try again.
      ##### THIS REMOVED AFTER sam deploy #####
  security:  # cognito scopes defined here at sam deploy-time but removed post-deploy per api gateway openapi export
    - slater-auth1:  
      - "slater/read"
      - "slater/write"
      - "slater/delete"
      - "slater-ro/read"  
      ######
  x-amazon-apigateway-request-validator: params-only
  x-amazon-apigateway-integration:
    type: aws_proxy
    uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FinderFunction/invocations'
    httpMethod: POST
    passthroughBehavior: when_no_match
    contentHandling: CONVERT_TO_TEXT
    responses:
      default:
        statusCode: 200
        responseParameters:
          # Support for CORS as API DOC is served from another origin server, not the API Gateway itself
          method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          method.response.header.Access-Control-Allow-Methods: "'*'"
          method.response.header.Access-Control-Allow-Origin: "'*'"`
          
# template.yaml:
 
SlaterApiGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [Accounts, !Ref "AWS::AccountId", StageName]
      DefinitionBody:
        Transform:
          Name: LargeInclude
          Parameters:
            BucketPrefix: "prsn-code-artifacts-us-east-1-"
            Key: "slater/temporary_openapi/openapi_bundled.yaml"  # large API so much use s3 interim storage 
      EndpointConfiguration: REGIONAL
#      Domain:   cognito authorization for endpoints original worked (on resource method in console) with above openapi.yaml security section but after
#                       factor Domain section out to BasePathMapping (below), cognito authorizer no longer associated with endpoint method on console (same for all request methods)
#    Original 
#        CertificateArn: !FindInMap
#          - Accounts
#          - !Ref AWS::AccountId
#          - AcmCertificateArn
#        DomainName: !FindInMap
#          - Accounts
#          - !Ref AWS::AccountId
#          - ApiDomainName
#        Route53:
#          HostedZoneId: !FindInMap
#            - Accounts
#            - !Ref AWS::AccountId
#            - HostedZoneId
#        BasePath:
#          - !Ref SlaterBasePath
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
      BinaryMediaTypes:
        - multipart/form-data

  SlaterBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref SlaterBasePath
      DomainName: !FindInMap [Accounts, !Ref AWS::AccountId, ApiDomainName]
      RestApiId: !Ref SlaterApiGateway
      Stage: !Ref SlaterApiGateway.Stage
```

<img width="2115" alt="Screenshot 2023-09-27 at 4 25 38 PM" src="https://github.com/aws/serverless-application-model/assets/3838735/63ab1a98-67ec-494e-815b-439ca42a4f66">

**Comment by GavinZZ** [comment]
Hi @bmckinle, thanks for reaching out. Based on the description, I've labeled this issue as a bug. However, I'll need a bit more information to help investigate the root cause. 
1. Were you using SAM to deploy the template previously and it did contains `security` section? 
2. Are you using `AWS::Serverless::Function` API event source along with the `AWS::Serverless::Api` resource? 
3. Would you be able to provide a minimally reproducible template?

**Comment by bmckinle** [comment]
1. Yes, using SAM CLI, version 1.91.0
2. Yes, we are using AWS::Serverless::Api in conjunction with AWS::Serverless::Function event sources that reference the Api resource
3. Not easily, no.  That said, AWS has a support case where the problem of sam deploy dropping the security section was independently confirmed, multiple times, in fact.  Is there an hello world sam template.yaml and openapi.yaml in examples you could recommend (prefer) to setup the problem?  This would offer the least burden to all concerned.

**Comment by GavinZZ** [comment]
Hi thanks for the quick response. 

There has been a previous issue which sounds very similar to the problem you're facing. When you use `AWS::Serverless::Function` in conjunction with `AWS::Serverless::Api`, and the API resource defines a `DefinitionBody` property, it would ignore the `Authorizer`, `ApiKeyRequired` property defined in the SAM Function event source [`Auth` property](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-apifunctionauth.html). 

It sounds very similar to your problem and we've introduced a fix to this problem by specifying `OverrideApiAuth`. See example:
```
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      ......
      Events:
        MyApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: get
            Auth:
              Authorizer: NONE
              OverrideApiAuth  ******* new property we introduced to fix this problem *******
```
This has just been released to all regions recently and we're working on documentation update on this property. 

Would you mind trying it out and including this property in your template and see if this fixes your issue?

**Comment by bmckinle** [comment]
Awesome!  I will give OverrideApiAuth a try!  Thank you!

**Comment by GavinZZ** [comment]
@bmckinle In my previous comment, I forgot to include `: true` to the end of `OverrideApiAuth` property. I've updated it. Make sure to use the updated format.

**Comment by bmckinle** [comment]
I gathered that it would need that.  I'll use that syntax.

**Comment by GavinZZ** [comment]
Don't think so, you should be able to use this property directly.

**Comment by GavinZZ** [comment]
Hi @bmckinle, curious if you had the chance to try this new property out? Does it fix the problem you described?

**Comment by bmckinle** [comment]
Success! (Kapla! [Klingon]). It worked but had to use our Authorizer: CognitoAuthorizer # not NONE.   Thank you, @GavinZZ !

**Comment by GavinZZ** [comment]
Great! Glad to hear that it's working. Marking this issue as resolved.

**Comment by bmckinle** [comment]
@GavinZZ Ok, when we tried this working section for one endpoint, sam deploy succeeded an authorization was honored (positive and negative tests worked for cognito token).  But, on multiple GET, POST, PUT, etc. endpoints, with identical sections just like the one below

`      Events:
        GetContactsApi:
          Type: Api
          Properties:
            RestApiId: !Ref "SlaterApiGateway"
            Path: /contacts
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
              OverrideApiAuth: true  # new property we introduced to fix no cognito security on each endpoint`

we get this misleading error during sam deploy

`Waiting for changeset to be created..
Error: Failed to create changeset for the stack: slater-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Structure of the SAM template is invalid. Value of '/ipsanddnsnames' path must be a dictionary according to Swagger spec.`

So we can make one endpoint work, but multiple endpoints across different methods do not.  We are trying just GETters with 2 and more incrementally to see if we can isolate the problem.  Can you suggest another solution?

**Comment by GavinZZ** [comment]
Hi @bmckinle, feel free to open a follow-up issue and reference this one from the new issue. Meanwhile I'll help investigate and see if I can reproduce something similar.

**Comment by GavinZZ** [comment]
Unfortunately, I am not able to reproduce the issue. Maybe there's something that I missed. Here is the template I tried with.
```
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        # Simple AWS Proxy API
        swagger: '2.0'
        info:
          version: '2016-09-23T22:23:23Z'
          title: Simple Api
        schemes:
        - https
        paths:
          /lambda-request:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations
                httpMethod: GET
                passthroughBehavior: when_no_match
          /lambda-request-override-none:
            post:
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations
                httpMethod: POST
                passthroughBehavior: when_no_match
          /lambda-request-override-cognito:
            put:
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations
                httpMethod: PUT
                passthroughBehavior: when_no_match
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn:
              Fn::GetAtt: MyCognitoUserPool.Arn
          MyLambdaRequestAuth:
            FunctionPayloadType: REQUEST
            FunctionArn:
              Fn::GetAtt: MyLambdaAuthFunction.Arn
            Identity:
              QueryStrings:
              - authorization
        DefaultAuthorizer: MyLambdaRequestAuth

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          return {
            statusCode: 200,
            body: 'Success'
          }
        }
      Handler: index.handler
      Runtime: nodejs16.x
      Events:
        LambdaRequest:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: get
            Auth:
              Authorizer: MyLambdaRequestAuth
            Path: /lambda-request
        LambdaRequestOverrideNone:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: post
            Auth:
              Authorizer: NONE
              OverrideApiAuth: true
            Path: /lambda-request-override-none
        LambdaRequestOverrideCognito:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: put
            Auth:
              Authorizer: MyCognitoAuthorizer
              OverrideApiAuth: true
            Path: /lambda-request-override-cognito

  MyLambdaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          const auth = event.queryStringParameters.authorization
          const policyDocument = {
            Version: '2012-10-17',
            Statement: [{
              Action: 'execute-api:Invoke',
              Effect: auth && auth.toLowerCase() === 'allow' ? 'Allow' : 'Deny',
              Resource: event.methodArn
            }]
          }
          
          return {
            principalId: 'user',
            context: {},
            policyDocument
          }
        }

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyCognitoUserPool

  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: MyCognitoUserPool
      ClientName: MyCognitoUserPoolClient
      GenerateSecret: false
```

This should match what you described. I first have a `MyApi` resource that has three different Path+Method, `get, post and put`. I have also defined `MyFunction` with API events and each event uses a different authorizer using `OverrideApiAuth` property. I am able to successfully upload the template and I verified that my API console is showing the expected data. 

Please let me know if I missed something.

**Comment by bmckinle** [comment]
@GavinZZ I'm reviewing your working code to see if it is possible to adapt it to our approach.  Two notable differences are:

1. template.yaml's use of  x-amazon-apigateway-integration in AWS::Serverless::Api Paths occurs in openapi_bundled.yaml in our coding approach; and
2. MyLambdaRequestAuth does not appear in our Auth section in AWS::Serverless::Api. <== This is of particular interest.

**Comment by bmckinle** [comment]
@GavinZZ I think the following is where the sam deploy problem may arise, assuming other template.yaml sections are equivalent between your test case and our ours.

openapi_bundled.yaml:

```
...
components:

  # See ./openapi/schema folder for factored schema components.

  # Cognito user pool linkages to API Gateway
  securitySchemes:
    slater-auth1:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
          - Fn::GetAtt: [ UserPool, Arn ]
        type: "cognito_user_pools"
```

template.yaml:
```
  SlaterApiGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [Accounts, !Ref "AWS::AccountId", StageName]
      DefinitionBody:
        Transform:
          Name: LargeInclude
          Parameters:
            BucketPrefix: "prsn-code-artifacts-us-east-1-"
            Key: "slater/temporary_openapi/openapi_bundled.yaml"
      EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
#          MyLambdaRequestAuth:  # this is defined in openapi_bundled.yaml but only with function arn and nothing else (see openapi_bundled.yaml snippet above)
#            FunctionPayloadType: REQUEST
#            FunctionArn:
#              Fn::GetAtt: MyLambdaAuthFunction.Arn
#            Identity:  # we don't have this
#              QueryStrings:
#                - authorization
#          DefaultAuthorizer: MyLambdaRequestAuth. # we dont have this
      BinaryMediaTypes:
        - multipart/form-data
 ...
      Events:
        GetAccountsApi:
          Type: Api
          Properties:
            RestApiId: !Ref "SlaterApiGateway"
            Path: /accounts
            Method: GET
            Auth:
               Authorizer: CognitoAuthorizer
                OverrideApiAuth: true  # new property we introduced to fix no cognito security on each endpoint
         ...70+ other GET, POST, DELETE, etc other endpoint defintions
```
