### ISSUE TITLE
Please tag release 1.77.0

### ISSUE THREAD

**Issue by musicinmybrain** [aws/serverless-application-model#3370]
### Description

Version 1.77.0 [was released on PyPI](https://pypi.org/project/aws-sam-translator/1.77.0/), but there is no [corresponding tag `v1.77.0`](https://github.com/aws/serverless-application-model/releases/tag/v1.77.0) in this repository.

Please push the tag, and consider whether anything might have changed recently in the release process to cause the missing tag. Thanks!

### Steps to reproduce

Go to https://github.com/aws/serverless-application-model/releases/tag/v1.77.0.

### Observed result

HTTP 404 error

### Expected result

Something like https://github.com/aws/serverless-application-model/releases/tag/v1.76.0
### Additional environment details

1. OS: N/A
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: N/A
3. AWS region: N/A

**Comment by GavinZZ** [comment]
Marking it as closed since it's resolved.
