### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by aahung** [aws/serverless-application-model#3400]
## Why

- Python 3.7 is EOL: https://devguide.python.org/versions/
- SAM CLI stopped publishing 3.7 to pypi: https://github.com/aws/aws-sam-cli/pull/6119
- Features like `TypedDict` and `Literal` are native in 3.8 and we can drop from importing `typing_extensions`

**Comment by xazhao** [comment]
Thanks for the issue @aahung. We will be starting to drop the suppor for Python3.7

**Comment by ssenchenko** [comment]
PR merged https://github.com/aws/serverless-application-model/pull/3403
