### ISSUE TITLE
AWS::EC2::SecurityGroup - SecurityGroupIngress (and Egress) display errors in VSCode when using !Select and !FindInMap for CidrIp and VpcId

### ISSUE THREAD

**Issue by jftjamf** [aws/serverless-application-model#3410]
I'm not sure if this is something you can fix or not in the `sam.schema.json` file or not. I am using `SAM CLI, version 1.100.0`.

In VSCode  version 1.84.0 and see these errors in VSCode, but the template itself if fine and is deployable.  In the screen shot, there are 3 errors: two for `CidrIp` and one for `VpcId` when trying to use `!Select` and `!FindInMap`.

Is this something that can be fixed on your end?  If not, do you have any ideas who I should report this to?

Thanks.
![VSCode_Errors](https://github.com/aws/serverless-application-model/assets/101215911/9b6c3edc-a927-4089-b92d-6ca1eb9fbaf1)

**Comment by GavinZZ** [comment]
SAM does not handle non SAM resources schema. We only take the schema files from CloudFormation and use it. Perhaps try this repository. https://github.com/aws-cloudformation/cloudformation-template-schema

**Comment by GavinZZ** [comment]
Closing this as this is technically unrelated to SAM.
