### ISSUE TITLE
GraphQL visibility private

### ISSUE THREAD

**Issue by achille1789** [aws/serverless-application-model#3422]
Hi,
I see that in CloudFormation there is the visibility property to set AppSync private, but I looked around and I didn't find anything for SAM.
Is it possible to set GraphQL (appsync) as private? Or any workaround available?
Thanks

**Comment by achille1789** [comment]
I am really sorry @hnnasit, let me open the issue in their repo then.
Thanks for the quick response.

**Comment by ssenchenko** [comment]
Thank you for letting us know @achille1789 CloudFormation has added it recently or at least after we released SAM resource. We're adding the same `Visibility` property soon

**Comment by ssenchenko** [comment]
It'll take about 2.5 weeks till `Visibility` will become available in every region

**Comment by achille1789** [comment]
That is awesome. Thanks a lot.
