### ISSUE TITLE
Bug: AWS SAM tag value on AWS::Serverless::Function empty when value is False

### ISSUE THREAD

**Issue by vandem9** [aws/serverless-application-model#3426]
### Description:
When setting tags on AWS::Serverless::Function and the value of the tag is False instead of "False" it becomes empty on the deployed resource. This is tested with the tags defined on Globals.

### Steps to reproduce:
Create a SAM template with a serverless function, provide it with tags on the globals object (not tested with tags on the resource itself). When you provide a tag with the value False and not "False" it becomes empty.

![Screenshot 2023-11-17 at 15 29 48](https://github.com/aws/aws-sam-cli/assets/38071372/232b0047-b9b5-4cef-a80f-28ca95907a7a)
![Screenshot 2023-11-17 at 15 29 05](https://github.com/aws/aws-sam-cli/assets/38071372/8a52a5c9-7de1-4cdb-8bee-af4f5bb44625)

**Comment by ConnorRobertson** [comment]
The PR has been merged so closing this issue, please let us know if this issue persists.
