### ISSUE TITLE
"Invalid OpenAPI input" when OpenAPI set to `3.1.0`

### ISSUE THREAD

**Issue by garretwilson** [aws/serverless-application-model#3449]
The latest [OpenAPI Specification](https://swagger.io/specification/) is at v3.1.0, and apparently has been [for over two and a half years](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0). Yet in [`AWS::Serverless::Api`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) if I set [`OpenApiVersion`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion) to `3.1.0`, my SAM deployment dies with:

> `Invalid OpenAPI input.`

I had to pull the OpenAPI version down to `3.0.3`.

Perhaps SAM can be updated to support the latest OpenAPI version? Currently SAM is forcing us to an old OpenAPI version that was released before the pandemic.

**Comment by GavinZZ** [comment]
What I will do is to help create an issue internally to CloudFormation team and ask for support for latest OpenApi version. Going to mark this issue as closed as SAM has no control over the deployable OpenApi version.

**Comment by garretwilson** [comment]
> What I will do is to help create an issue internally to CloudFormation team and ask for support for latest OpenApi version.

Thank you for filing that internal issue to the CloudFormation team.

But is there not a public GitHub project for submitting tickets to CloudFormation?

**Comment by GavinZZ** [comment]
There are a couple of CloudFormation open-source repositories, see https://github.com/aws-cloudformation. Unfortunately, I'm unsure which is the correct repo. You can also try creating an issue in one of the repo there, hopefully they can help transfer the issue to the correct repo.
