### ISSUE TITLE
AWS::Serverless::Api - setting "OpenApiVersion" causes "Stage" deployment to be skipped - why?

### ISSUE THREAD

**Issue by climbertjh2** [aws/serverless-application-model#3477]
### Description
I am trying to deploy an API without the `Stage` stage deployment.  The [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion) suggests that the `OpenApiVersion` value must be set in order for the `Stage` stage not to be created.

Why is this the case?

Why is deploying a `Stage` stage dependent on setting the `OpenApiVersion`?

### Steps to reproduce
Use CloudFormation `AWS::Serverless::Api` resource.  Don't set `OpenApiVersion`.  Set the `StageName` property.

### Observed result
Two stages are created: `Stage` and `StageName-value`.

### Expected result
One stage is created: `StageName-value`.

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region: us-east-1

**Comment by GavinZZ** [comment]
Hi @climbertjh2, this is due to a previous bug, see more detail in https://github.com/aws/serverless-application-model/issues/191. We attempted to fix the bug but it would have caused backward incompatible behaviour. We decided to add the fix under `OpenApiVersion` flag for this reason.

**Comment by GavinZZ** [comment]
Marking this issue as closed. Feel free to re-open it or open a new one if you have additional questions.

**Comment by climbertjh2** [comment]
Thanks @GavinZZ  - I am still reading through the referenced #191 .

**Comment by climbertjh2** [comment]
Note that there is more information / related information in #3447 .

I'm good for now with this and will just live with it.

**Comment by GavinZZ** [comment]
Sorry for the trouble, but in order to guarantee backward compatibility, our option is limited. And we don't want to continue introducing new properties for simple scenarios like this which may be very confusing to customers as well.

**Comment by anilbhaskaran** [comment]
Will this allow us to remove the "stage" from an API gateway which is already created?
