### ISSUE TITLE
Building features for AWS SAM

### ISSUE THREAD

**Issue by ghost** [aws/serverless-application-model#3506]
Thank you for taking a look at this issue.  Is there documentation how to run a git cloned AWS SAM repository (with the intentions of developing  features for the AWS SAM repository)?

**Comment by GavinZZ** [comment]
Hi there, AWS SAM values community involvement and appreciates any contributions that help improve the serverless application experience. We welcome feedback, issues, and pull requests from all users. Here is the [link](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md) on getting started with contributing to AWS SAM repo.

**Comment by GavinZZ** [comment]
Going to mark this issue as complete. If you have additional questions, please feel free to create new issue.
