### ISSUE TITLE
Layer code update not reflected on Lambda Function

### ISSUE THREAD

**Issue by Halembek** [aws/serverless-application-model#3540]
### Description:
Changes made to layer code are not reflected as a result of deploying a new version of the layer using sam deploy

### Steps to reproduce:
* Create a layer
* Create a group of lambda functions that depends on the created layer
* After deploying for the first time, update just the code of the layer, and make no changes to the Lambdas
* Deploy using sam deploy, since no changes were made to the lambdas just a new version of the layer is published and deployed

### Observed result:
* As a result the new version of the layer is assigned to existing lambdas but the updated code will not be reflected even when the new version of the layer is deployed and assigned to the lambdas

### Expected result:
Changes of the code in the new layer version should be reflected in the lambdas even if no new version of the lambdas was deployed 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 1.28.0

### Workaround

* Manually deploy a new versión of the lambda function using Aws Console and the changes to the layer will be reflected in the lambda functionality
* Another option would be to "force" the lambdas update/deploy by adding a comment or something that indicates sam that the function should be redeployed, nevertheless it is not clear in the documentation how sam decides that a resource should be updated in the stack

**Comment by paulhcsun** [comment]
As mentioned by @hawflau, the solution is to set `AutoPublishAliasAllProperties: true` in the Lambda Function. Closing this issue.

**Comment by niklas-palm** [comment]
This issue is still prevalent if you're not using `AutoPublishAlias`
