### ISSUE TITLE
Setup semantic release

### ISSUE THREAD

**Issue by sanathkr** [aws/serverless-application-model#360]
**Description:**

**Description:**

Set up semantic-release https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-use-semantic-release-to-publish-non-javascript-packages to facilitate automated releases based on semantic versioning and commit messages.

This requires us to follow conventional commits. We should incorporate something like https://github.com/marionebl/commitlint.

We should also update `DEVELOPMENT_GUIDE.rst` once this is setup.

**Comment by Nr18** [comment]
Wouldn't https://github.com/relekang/python-semantic-release be a better option? The one you mentioned is a npm module

**Comment by brettstack** [comment]
@Nr18 I have seen this package. My main concerns with it are support (the Node.js is significantly m ore popular; likely to have ongoing fixes, updates, support) and flexibility (the Node.js version is highly configurable).

I think it makes sense to investigate the Python version first, and fall back to the Node.js version only if it doesn't meet our needs.

**Comment by mgrandis** [comment]
Closing this as we are now using SemVer.
