### ISSUE TITLE
Feature request: Plugin system

### ISSUE THREAD

**Issue by marcy-terui** [aws/serverless-application-model#367]
**Description:** I want to add some features to SAM. For example, deployment hooks, language-specific packaging mechanisms, integration of the services outside AWS, and so on. However, I think that it is not realistic to implement all of them in the main system of SAM. So I hope a plugin system. If this request is accepted, I would like to support them as much as possible.

**Comment by toricls** [comment]
I'm also interested in this. maybe the aws-sam-local is the good place to be implemented that?

**Comment by marcy-terui** [comment]
> What i am missing is a way to have a generic place for your python packages during development. But > on a package action that only the requirements of that specific function are included.
>
> This will keep the packages small and only include stuff that is needed.
>
> Is that what you mean with a language specific package mechanism?

Yes. Each of us has some Makefile and/or Shell Script to deploy our functions. I think that it is better to integrate the best practices as plugins by language.

I think that it is better to integrate the packaging plugins in aws-cli for now. Anyway, I need some systems and guidelines to expand SAM myself.

**Comment by Nr18** [comment]
Right implementing it into the aws-cli would allow non-sam users to benefit too.

I found this issue that looks like that is heading that way: https://github.com/aws/aws-cli/issues/3213

**Comment by aletheia** [comment]
@marcy-terui do you mean adding the capability to specify a custom transform for CFN? Could be really cool!

**Comment by carlsborg** [comment]
Bump. User defined distributable plugins is one of the key advantages that the "serverless framework" offers. Its vital to have this in SAM as well. For example, there is an instrumentation library that requires you to add a decorator to every api function. There are plugins available for Serverless Framework, Chalice, and others that make this a one line change, but not SAM because there is no plugin framework. Are you open to design proposals or do you have something in mind already?

**Comment by txase** [comment]
Plugins seem like a great solution, but they eventually lead to huge problems. As plugins end up being community owned and maintained, there's no centralized mechanism to ensure they work well together.

See https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/9 for an example of how issues devolve to people listing all the plugins they use together to try to understand why things start breaking.

There are two ways you can achieve the same effect of plugins that are easier to maintain (and, imho, better abstractions anyways):

* For resource manipulation, use a CloudFormation Transformation. SAM itself is one giant transformation. The nice thing about transformations is they can be localized to specific parts of an application template. Even with a global transformation there's still a limited surface area for when transformations are run and what their inputs are.
* For code manipulation, the new SAM CLI build command will be flexible enough for you to specify customizations for how code packages are built. This is the right level to add code-level plugin-like functionality.

**Comment by jfuss** [comment]
We are considering plugins for SAM CLI (https://github.com/aws/aws-sam-cli/issues/3265). I don't see a path for a Plugin type system for the SAM Translator (what this repo is for). AWS CloudFormation has some things to help in this area now (hooks and modules) but not something SAM is directly looking at.

Closing this as it's not something we are tracking for SAM but are considering for SAM CLI (though no decisions have been made). If there is a reason to consider a plugin system for SAM Translator (the SAM Spec to raw CloudFormation resources translation), please open a new issue describing the use-case.
