### ISSUE TITLE
LatestVersionErrorMetricGreaterThanZeroAlarm example not logging data

### ISSUE THREAD

**Issue by simon-chettle** [aws/serverless-application-model#518]
**Description:**

Following https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#traffic-shifting-using-codedeploy

The Alarm `LatestVersionErrorMetricGreaterThanZeroAlarm` does not work. I believe this might be because the dimensions for the alarm include a full ARN in the Resource rather than just a name like `AliasErrorMetricGreaterThanZeroAlarm` uses. 

**Steps to reproduce the issue:**
1. Use the example SAM template to create the 2 alarms
2. Create an alarm manually pointing the newest lambda version (not yet live to all traffic)
3. Force an error on your Lambda - both in the live and new version

**Observed result:**
`LatestVersionErrorMetricGreaterThanZeroAlarm` has no data
Manual test alarm for newest version has data

**Expected result:**
`LatestVersionErrorMetricGreaterThanZeroAlarm` should have data

**Comment by sgrinich-98point6** [comment]
Hello @simon-chettle , did you ever find out how to reach the expected result?

**Comment by jfuss** [comment]
Clearing out old Github Issues that do not have traction/haven't had responses in over a year. If this is still an issue or needs attention please create a new Issues (linking to this one can be helpful) and we can re-look into things.

**Comment by Manouchehri** [comment]
I can't seem to get `LatestVersionErrorMetricGreaterThanZeroAlarm` or `AliasErrorMetricGreaterThanZeroAlarm` to work at all, neither seem to be valid alarms anymore.
