### ISSUE TITLE
Unable to define minimumCompressionSize and a few other API Gateway settings in template

### ISSUE THREAD

**Issue by zfoster** [aws/serverless-application-model#519]
I searched the issues and don't see a duplicate for any of the following keys that seem to be unsupported by `AWS::Serverless::Api`

Failing body is below with explanations. The seemingly unsupported keys are:

`MinimumCompressionSize`

and 

`MethodSettings`:
- `RequireAuthorizationForCacheControl`
- `UnauthorizedCacheControlHeaderStrategy`

As the CLI can create an API with these, I'd expect them to work with the serverless transform. I see the issue #248 has a lot of work for additional fields (some of which I'm even using 😄) but enabling these manually would essentially be a blocker for us at bustle trying to use SAM. Are there any workarounds or do these belong somewhere other than `Properties`, etc?

Note: the following will deploy with the comments removed, and will fail if any of these fields are added one off.

```
"MyAPI": {
      "Type": "AWS::Serverless::Api",
      "Properties": {
        "StageName": { "Ref": "environment" },
        "CacheClusterEnabled": true,
        // "MinimumCompressionSize": 1024,
        "CacheClusterSize": "6.1",
        "MethodSettings": [
          {
            "LoggingLevel": "ERROR",
            "ResourcePath": "/*",
            "HttpMethod": "POST, OPTIONS",
            "ThrottlingBurstLimit": 5000,
            "ThrottlingRateLimit": 10000
            // "RequireAuthorizationForCacheControl": true
            // "UnauthorizedCacheControlHeaderStrategy": "SUCCEED_WITH_RESPONSE_HEADER"
          },
          {
          "LoggingLevel": "ERROR",
          "CacheTtlInSeconds": 60,
          "ResourcePath": "/*",
          "HttpMethod": "GET",
          "ThrottlingBurstLimit": 5000,
          "ThrottlingRateLimit": 10000
          // "RequireAuthorizationForCacheControl": true
          // "UnauthorizedCacheControlHeaderStrategy": "SUCCEED_WITH_RESPONSE_HEADER"
        }],
```

Thanks in advance for any insight!

**Comment by zfoster** [comment]
Some follow up notes:

I was able to add minimumCompressionSize by including it as such in my swagger DefinitionBody:

```
"DefinitionBody": {
          "swagger": "2.0",
          "info": { "title": { "Ref": "AWS::StackName" } },
          "x-amazon-apigateway-minimum-compression-size": 1024
...
}
```

The other two fields,

`requireAuthorizationForCacheControl`

and

`UnauthorizedCacheControlHeaderStrategy`

seem to default to the values I have listed, however I would still prefer if all of these things were configurable without a custom resource.

**Comment by rm-hull** [comment]
Add minimum compression size is logged in issue #419

**Comment by brettstack** [comment]
`RequireAuthorizationForCacheControl` and `UnauthorizedCacheControlHeaderStrategy` are Stage level settings, and don't belong in `MethodSettings`. Unfortunately we haven't configured `AWS::Serverless::Api` to accept these two properties, but it should be a simple PR for anyone interested in adding them.

Main areas to modify are:

https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/apigateway.py#L28

https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/api/api_generator.py#L150

https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/sam_resources.py#L459

Then add tests and docs 👍

**Comment by eduardovra** [comment]
I would like to contribute on this issue, but couldn't find these parameters on the cloudformation docs. Can you confirm this is already supported ?

https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html

Thanks

**Comment by praneetap** [comment]
I see that MinimumCompressionSize support was released with this PR https://github.com/awslabs/serverless-application-model/pull/786 

I don't see the other two supported in CFN, you are right @eduardovra. We will reach out to the right teams with this information, thank you.

**Comment by aculnaig** [comment]
Hi, when I try `MinimumCompressionSize` to compress the response body, I receive an uncompressed json instead

`sam local start-api --warm-containers EAGER`

```
curl -svi -X GET 'http://127.0.0.1:3000/pets' -H 'Accept: application/json' -H 'Accept-Encoding: gzip'

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /pets HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.64.1
> Accept: application/json
> Accept-Encoding: gzip
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< content-type: application/json
content-type: application/json
< Content-Length: 111
Content-Length: 111
< Server: Werkzeug/1.0.1 Python/3.8.10
Server: Werkzeug/1.0.1 Python/3.8.10
< Date: Mon, 07 Jun 2021 14:43:19 GMT
Date: Mon, 07 Jun 2021 14:43:19 GMT

< 
* Closing connection 0
[{"id":1,"type":"dog","price":249.99},{"id":2,"type":"cat","price":124.99},{"id":3,"type":"fish","price":0.99}]
```

```
.
├── functions
│   └── GzipJsonFunction.js
└── template.yaml

1 directory, 2 files

```

`GzipJsonFunction.js`
```
exports.handler = async () => {
    const pets = [
        { 
            "id": 1, 
            "type": "dog", 
            "price": 249.99 
          }, 
          { 
            "id": 2, 
            "type": "cat", 
            "price": 124.99 
          }, 
          { 
            "id": 3, 
            "type": "fish", 
            "price": 0.99 
          } 
    ]

    return Promise.resolve({
        statusCode: 200,
        headers: {
            'content-type': 'application/json'
        },
        body: JSON.stringify(pets)
    })
}

```

`template.yaml`
```
Transform: AWS::Serverless-2016-10-31

Resources:
  GzipJsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      CodeUri: functions/
      Handler: GzipJsonFunction.handler
      Events:
        GzipJsonGet:
          Type: Api
          Properties:
            Method: GET
            Path: /pets
            RestApiId: !Ref GzipJsonApi
  GzipJsonApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      MinimumCompressionSize: 0

```

**Comment by jfuss** [comment]
Still looks like `RequireAuthorizationForCacheControl` and `UnauthorizedCacheControlHeaderStrategy` are still not in CloudFormation. 

`MinimumCompressionSize` is already supporting.

Closing. Given we don't have a current path on the outstanding ones, I am going to close this. Feel free to re-open once there is a path for support.
