### ISSUE TITLE
Feature Request: Support SimpleTable Tags in Globals Section

### ISSUE THREAD

**Issue by winsome** [aws/serverless-application-model#563]
Tags were recently added as a property for SimpleTable in #252 but don't seem to be supported in the Globals Section.

I tried it out while writing a new template and validation fails. This is also backed up by documentation here https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#supported-resources.

Would be nice for feature equality since Tags are already supported in Globals for Functions.

**Comment by brettstack** [comment]
Thanks @winsome, I've tagged this as a feature request. A PR for this would be appreciated. 🙌

**Comment by jfuss** [comment]
Updating labels.

**Comment by jfuss** [comment]
Cleaning up older issues that do not have traction and have lingered. If this is something still wanted, please open a new issue. 

This is a simple fix, which would require: 
1) adding "Tags" here: https://github.com/aws/serverless-application-model/blob/develop/samtranslator/plugins/globals/globals.py#L80
2) adding test cases to cover the use case.
