### ISSUE TITLE
Feature Request: Support Lambda AddPermission

### ISSUE THREAD

**Issue by willtong1234** [aws/serverless-application-model#583]
SAM currently supports the ability to specify an event source when defining an AWS::Serverless::Function. This currently does not support adding permissions for any other service principal (i.e. AWS Secrets Manager).

This request is to add support for the Lambda AddPermission API in SAM. This can either be done as an additional property of the AWS::Serverless::Function resource type or as a new resource type, such as AWS::Serverless::Permission, similar to the CFN equivalent: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html.

Please let us know if you would be open to a PR for this type of functionality.

**Comment by willtong1234** [comment]
AFAIK, when authoring applications for the Serverless Application Repository (SAR), you can only use SAM resources types in the SAM template and it does not support CFN syntax. Please let me know if I'm mistaken. Thanks!

**Comment by jlhood** [comment]
SAR requires the template to be a SAM template, but a subset of native CFN resource types is supported. Full details here:

https://docs.aws.amazon.com/serverlessrepo/latest/devguide/using-aws-sam.html

**Comment by willtong1234** [comment]
Ah ok, thanks for the information! Unfortunately, AWS::Lambda::Permission is not in the list of supported resource types. How do I go about requesting support for this resource in SAM?

**Comment by jlhood** [comment]
From the SAR docs linked above:

> If you want to request a new policy template to be added, do the following:
> 
> 1. Submit a pull request against the policy_templates.json source file in the develop branch of the AWS SAM GitHub project. You can find the source file here: policy_templates.json.
> 1. Submit an issue in the AWS SAM GitHub project that includes the reasons for your pull request and a link to the request. Use this link to submit a new issue: AWS Serverless Application Model: Issues.

However, AWS::Serverless::Function implicitly adds service principal lambda permissions based on the event type. Is there an event type you can add to SAM that would make sense for Secrets Manager? Then you could make the SAM transform add it for you. Adding a new event type isn't too difficult.

Here's an example (although incomplete) PR that could help you get started: #363

**Comment by jfuss** [comment]
SAR support `AWS::Lambda::Permission` now: https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html

Closing as the main driver was support within SAR at a time `AWS::Lambda::Permission` was not supported. If there is still added value for SAM to do this, please open up a new Github issue.
