### ISSUE TITLE
Add IAM Read only permissions to SAM Policy templates

### ISSUE THREAD

**Issue by turjachaudhuri** [aws/serverless-application-model#585]
**Description:**

I am creating a serverless app that will validate whether a specified AccessKey is valid or not and if valid , it will return some metadata like accesskeycreatedate ,lastuseddate and so on.

This requires the following permissions -
{  
                     "Action":[  
                        "iam:ListAccessKeys",
                        "iam:GetAccessKeyLastUsed",
                        "iam:ListUsers"
                     ],
                     "Effect":"Allow",
                     "Resource":"*"
                  }

Currently there is no Policy template is SAM which provides IAM Readonly permissions .  
Is it possible to add this as a policy template so that these kind of apps can be added to the serverless repo .

**Comment by aahung** [comment]
There is an IAM managed policy called "IAMReadOnlyAccess" which you can directly use in SAM function:

```
Properties:
  Policies:
    - arn:aws:iam::aws:policy/IAMReadOnlyAccess
```
