### ISSUE TITLE
Prob: Cannot offer Lambdas that manage Route53 for customers.

### ISSUE THREAD

**Issue by tristanls** [aws/serverless-application-model#588]
**Description:**

Cannot offer Lambdas that manage Route53 for customers due to lack of policy templates granting permission to update Route53 resources.

Pull Request to add Route53ChangeResourceRecordSetsPolicy: #587

**Comment by keetonian** [comment]
What is the specific use case for permission to update Route53 resources?

**Comment by jfuss** [comment]
You can still provide direct Policies on Lambda so this shouldn't be blocking anything for you. 

Given no reactions and how old this request is, I am going to close it. If this is still something needed, please open a new Issue (closed one are not well tracked).
