### ISSUE TITLE
Are nose and parameterized neccessary as dependencies?

### ISSUE THREAD

**Issue by RobRoseKnows** [aws/serverless-application-model#628]
Currently [in requirements/dev.txt](https://github.com/awslabs/serverless-application-model/blob/a2c69540ee93a673d03fa75bf7be4e4c75b80868/requirements/dev.txt#L12) both `nose` and `pytest` are listed as requirements. As far as I can tell though, `nose` isn't being used at all and could be cut from requirements. This would probably speed up Travis builds.

Additionally, I'm not sure `parameterized` is needed either since `pytest` has [built-in parameterization](https://docs.pytest.org/en/latest/parametrize.html#parametrize-basics). Some of the test decorators would have to be rewritten slightly to use `@pytest.mark.parametrize` instead of `@parameterize` but removing it as a dependency would also probably speed up CI. I can do that, but I want to make sure I'm not missing something first.

**Comment by keetonian** [comment]
`nose` can definitely be removed, that isn't being used anymore. 

As far as I can tell, `parameterized` could be replaced with the equivalent in pytest, but I am not sure if there was a specific reason why SAM uses `parameterized` over other alternatives.

**Comment by RobRoseKnows** [comment]
Ah, I think I figured out why SAM is using `parameterized` instead of pytest marks! The pytest parameterization marks don't work with `unittest.TestCase` objects. It shouldn't be terribly hard to switch them over from using `unittest`, but I didn't want to do that without checking with you first. Pytest-style tests have an array of benefits over unittest, as detailed [here](https://docs.pytest.org/en/latest/unittest.html) but they are a little weirder if you come from a JUnit world.

**Comment by brettstack** [comment]
There's some discussion over at #366 and a related PR #462

**Comment by mgrandis** [comment]
Closing as nose has been removed by #629
unittest is still being used and won't be removed.
