### ISSUE TITLE
Feature: Always deploy API option

### ISSUE THREAD

**Issue by keetonian** [aws/serverless-application-model#660]
**Description:**

Add a new property to always deploy your API even if we can't detect a change to the API.

**Steps to reproduce the issue:**
1. Deploy a SAM template with an API that references a function
2. Change the name of the function
3. Redeploy the template

**Observed result:**

The rest API does not redeploy with the updated function name

**Expected result:**

Rest API would redeploy with the updated function name

See issue #634

**Comment by jlhood** [comment]
Another edge case where a customer encountered an availability drop by a missed API deployment:

> In your case, from the name of your functions, I'm guessing you're explicitly hardcoding the function name using the FunctionName property. If you change the value of FunctionName without changing the logical id (key of the AWS::Serverless::Function resource), SAM will not detect that the API has changed and will not redeploy the API after it's been updated.
> 
> In this case, on deployment, CloudFormation creates a new function with the new name, updates the API Gateway REST definition to point to the new function name, does NOT do a deployment of this updated API definition (so the actual API is still referencing the function with the old name), then deletes the Lambda function with the old name (causing the API to now return 5xx errors).

**Comment by keetonian** [comment]
#1162 is another case that this would fix.

**Comment by jonathanyong81** [comment]
Has there been any progress on this?

For example if my swagger definition has an endpoint with the following

```
x-amazon-apigateway-integration:
  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}:${FunctionAlias}/invocations"
```

When I update the lambda (so a new version of the lambda, with a new alias pointing to that version), SAM doesn't deploy the API.  Although the API definition shows the endpoint integrated with the new lambda alias, the stage is NOT actually deployed.

To get around this, we would have to hardcode and increment the FunctionAlias in the swagger definition (so that SAM detects a swagger change) rather than using the variable.

**Comment by deepku2** [comment]
+1

**Comment by atharfaraz** [comment]
+1

**Comment by urvi-desai** [comment]
+1

**Comment by SanderAdamDXC** [comment]
+1

**Comment by ilietrasca** [comment]
+1

**Comment by elliottyates** [comment]
We experienced the same issue when updating an `HTTP_PROXY` URI and a stage variable using the SAM CLI. The URI shows up in the console/UI, and the stage variable gets changed on the stage, but the actual URI isn't changed (which you can see by exporting the stage spec) until you manually deploy the updated resources (we did this via the console).

**Comment by VanOvermeire** [comment]
Experiencing the same issue, is this somewhere on the road map?

**Comment by ncanibano** [comment]
Facing this issue as well. Any updates on when this feature is going to be available? Thanks!

**Comment by cb-manideep** [comment]
+1

**Comment by ni1402** [comment]
We also facing this issue with CORS update. ny updates on when this feature is going to be available?

**Comment by VanOvermeire** [comment]
Our (silly) workaround is to use `sed` to add a build number suffix to the name of our api gateway resource, thereby forcing a replacement. 

Does mean that even if there are no changes, the gateway is replaced. But this seems to add only 5-15 seconds to the deploy, which is acceptable for us. And much better than not getting our new endpoints!

```
// in our (groovy) jenkins pipeline; ApiGatewayApi is the name of our resource
sh "sed -i'.original' -e 's#ApiGatewayApi#ApiGatewayApi${env.BUILD_NUMBER}#' our-sam-template.yaml"
```

But obviously still hoping for a real fix :)

**Comment by AshMenhennett** [comment]
Hi

I believe this is related - https://github.com/aws/serverless-application-model/issues/1447

Ran into some issues with API Gateway config changes not redeploying the API - this feature request looks to resolve this issue.

**Comment by carlnordenfelt** [comment]
Experiencing the same issue when updating a Mock integrations Mapping Template.
There is an update o the API Definition (we inject the API specification via 
```
Api": {
      "Type": "AWS::Serverless::Api",
      "Properties": {
        "DefinitionBody": ...
```

it appears that some changes, like updating a Mapping Template, does not trigger an API deployment.

**Comment by hoffa** [comment]
One potential solution that would keep the transform deterministic would be to append a hash of the entire template to the API resource if a property is set (e.g. `AlwaysDeploy: true`). 🤔

**Comment by hoffa** [comment]
I'm working on a draft PR in https://github.com/aws/serverless-application-model/pull/2935 that adds a new property `AlwaysDeploy` (disabled by default), which as the name suggests would _always_ redeploy the API, even when neither the template nor parameters have changed.

**Comment by hoffa** [comment]
https://github.com/aws/serverless-application-model/pull/2935 has been merged and will roll out over the coming weeks.
