### ISSUE TITLE
Logical Id for LayerVersion not updated

### ISSUE THREAD

**Issue by dqvist** [aws/serverless-application-model#703]
**Description:**

When creating a AWS::Serverless::LayerVersion and using a combination of S3 Location Object and !Ref for the ContentUri the generated hash for the logical Id don't change.

Template in use:

  HelloWorldLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: hello-world
      Description: Simple Hello World Layer
      ContentUri:
          Bucket: !Ref ArtifactBucket
          Key: !Ref ArtifactKey
      CompatibleRuntimes:
        - python2.7
        - python3.6
        - python3.7
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain

**Steps to reproduce the issue:**
1. Deploy a LayerVersion using the template snippet above.
2. Update value for template parameter ArtifactKey
3. Redeploy the LayerVersion

**Observed result:**

Same logical Id generated and the old LayerVersion gets deleted.

**Expected result:**

A new logical Id is generated and old LayerVersion is preserved.

**Comment by keetonian** [comment]
Yes, I can see how this would happen, good find. We need to resolve the !Ref intrinsic in SAM instead of letting CFN do it.

Line to fix: https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/sam_resources.py#L653

**Comment by dqvist** [comment]
On the same topic. !Sub doesn't work either. It produce an error, sounds like the exact same root cause that intrinsic functions are nor resolved by SAM. Following produce an error:
ContentUri: !Sub s3://${ArtifactBucket}/${ArtifactKey}

**Comment by jfuss** [comment]
This seems to have been released in [v1.10](https://github.com/aws/serverless-application-model/releases/tag/v1.10.0) and therefore is already deployed to the service and released to PyPi. 

Closing, though if the above is not accurate please create a new issue.
