### ISSUE TITLE
InvokePermissions for multiple versions of the same Lambda function

### ISSUE THREAD

**Issue by hoegertn** [aws/serverless-application-model#738]
**Description:**

Currently, it is not possible to have invocation permissions for multiple versions of a function. If I use the `Events` property it attaches to `$LATEST` or the published alias and if I define it manually I can only target a specific version.

If I then update the stack and a new version gets deployed the old version loses its triggers.

The use case is to set a version as the target for an Alexa skill and then deploy new versions of the code and the point the development version of the skill to the new version but leaving production on the old version. This will no longer work because the ASK trigger is lost on the prod one.

**Observed result:**

Old version loses its trigger/invokePermission

**Expected result:**

There is a way to retain the trigger/invokePermission

**Comment by keetonian** [comment]
Is there a reason why using separate beta/dev and prod stacks or some sort of rolling deployment wouldn't work for this use case? I think the usual way to do this is to use separate stacks for develop and production stages; that way you're not altering your production environment any time you want to test something out or make changes, and can catch errors before it goes out to production.

**Comment by hoegertn** [comment]
With Alexa Skills you do not have classic dev/prod environments. You provide the ARN of a function (latest/alias/version) for your dev version of the Skill. After certification, this ARN is not changeable, and your skill is in prod. A new dev stage is created and you can provide a new ARN. You dev becomes prod, and a new dev appears. To use this with CI/CD, my idea was to update dev to the version and update this for every deployment. After certification, the version is fixed for prod and I can deploy new versions for the new dev stage. The thing is now, that the prod version loses its permissions and is not callable by Alexa anymore.

**Comment by jlhood** [comment]
We had some discussion on this and came up with a possible solution:

1. Have a way to scope the `FunctionName` property that's passed to the `AWS::Lambda::EventSourceMapping` resource to a specific version.
1. Have a way to set a [DeletionPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) to Retain on the EventSourceMapping that gets created.

We believe this would support your use case, but need to investigate further. Assigning this to @keetonian for further investigation.

@hoegertn Feel free to provide feedback or propose a SAM spec change if you agree with the above solution.

**Comment by hoegertn** [comment]
HI,
following your idea I tried this
```
  SkillFunctionPermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Retain
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref SkillFunction.Version
      Principal: alexa-appkit.amazon.com
```

But it does not work as the DeletionPolicy does not apply to Replacements. I think it will work if the logical name of the permission would change with every deployment.

**Comment by hoegertn** [comment]
Any idea on how to proceed with this topic? @keetonian @jlhood

**Comment by hoegertn** [comment]
Anything new on this topic? It would be great to have this in a future release

**Comment by brettstack** [comment]
We'd be open to a PR on this. Some relevant areas in code:

https://github.com/awslabs/serverless-application-model/blob/cbd4d9ad40a71b838f1e72b3b960689f30890bf9/samtranslator/model/eventsources/push.py#L514

https://github.com/awslabs/serverless-application-model/blob/0425efc396b659c8d0dea5b63c3287cb915d6b34/samtranslator/model/__init__.py#L42

**Comment by mndeveci** [comment]
Hi @hoegertn ,

We have released support for `UpdateReplacePolicy` for Serverless resources with [SAM v1.36.0](https://github.com/aws/serverless-application-model/releases/tag/v1.36.0).

You can read more about how resource level attributes are handled in SAM via our updated documentation; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resource-attributes.html

I am resolving this issue for now, but please feel free to re-open if you have issues with it.

Thanks!
