### ISSUE TITLE
Missing golang example for a lambda

### ISSUE THREAD

**Issue by kaihendry** [aws/serverless-application-model#896]
There is an example for API gateway here: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/hello-world-golang/main.go

But nothing for a standard lambda in Golang:
 https://github.com/awslabs/serverless-application-model/tree/master/examples/apps

This is related to https://github.com/awslabs/aws-sam-cli/issues/1136

Icing on top would be context demonstration for use with X-ray.

Thank you,

**Comment by jlhood** [comment]
Hi @kaihendry. The parts of the existing example that make it API Gateway specific are the [API event in the template](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/hello-world-golang/template.yaml#L15-L19) and the [expected request/response type of the Lambda function](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/hello-world-golang/main.go#L16).

A non-API Gateway example would be almost identical, but with different event types in the template and different request/response types. For example, if you wanted to write a Lambda function in Golang that triggers from SNS, you can add an [SNS event source](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sns) to the template and use the [SNS event types](https://github.com/aws/aws-lambda-go/blob/master/events/sns.go) in your Lambda function.

If you're interested in contributing a PR with this example, that'd be great!

**Comment by jfuss** [comment]
Examples have been moved to SAM CLI's app template structure. The repo for all SAM examples (that are  `sam init`able) is https://github.com/aws/aws-sam-cli-app-templates. We do have a basic example of Golang with API gateway. If there is something further missing, feel free to open an issue on the `aws-sam-cli-app-templates` Github.
