### ISSUE TITLE
Policies not supported in Globals

### ISSUE THREAD

**Issue by kaitlynbrown** [aws/serverless-application-model#969]
**Description:**
I'd like to run all of my AWS functions inside of a VPC. I was able to add VpcConfig to the Globals section of my template, but found that I still needed to add the VPCAccessPolicy Policy for it to work. It works fine if I add Policies to each Function definition, but if I try adding it to Globals, I get an error

**Steps to reproduce the issue:**
1. Define a SAM Template with at least one function and a trigger for it
2. Add a VpcConfig section under `Globals:` > `Function:` containing details of a vpc to run the functions in
3. Add the following Policies under `Globals:` > `Function:`
```
      Policies:
      - VPCAccessPolicy: {}
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
```
4. Package and deploy the template

**Observed result:**
I see the error:
```
'Globals' section is invalid. 'Policies' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions']
```
If I add the Policies to each individual function, the error disappears
**Expected result:**
Putting the policies in Globals should have the same effect as adding them to every function, without the above error

**Comment by AyushG3112** [comment]
+1

My use case is that all my Lambdas neeed to invoke a single Lambda for session Management. So I need to attach `AWSLambdaRole` across the service, which is not(I think) the optimal way

**Comment by keetonian** [comment]
The original decision was to not support `Policies` or `Role` in the globals field because it could result in a security issue (too broad / improper permissions on some resources). https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#unsupported-properties

However, in this particular use case, I can see the value of including `Policies` to the globals. We will discuss this further and perhaps revisit this decision.

**Comment by jfuss** [comment]
This is the same request as https://github.com/aws/serverless-application-model/issues/2009. After discussion with the team, we not planning to support `Policies` in Globals. 

Closing with not accepting.
